Remove z3 string theory from String wrapper
UnitTestBot/UTBotJava pull request #1050
Opened 2022-10-01 19:45 UTC by dtim

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-10-06 10:05 UTC, Damtev requested changes
Overall, LGTM, just some minor issues

2022-10-10 07:48 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Byte.java
> +        } else {
Done, thank you.

2022-10-10 07:49 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Byte.java
> +            }
Implemented as a special case with early return.

2022-10-10 07:49 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Byte.java
> +                reversed[offset] = (char) ('0' + value % 10);
Done

2022-10-10 07:49 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Byte.java
> +                value = value / 10;
Yes, done.

2022-10-10 07:50 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Long.java
> +        }
Fixed, thank you.

2022-10-10 07:50 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Short.java
>          assumeOrExecuteConcretely(s >= -10000);
Sure, missed it. Replaced with `assume` with regular limits for `short`.

2022-10-10 07:51 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Short.java
> +        }
Fixed.

2022-10-10 07:53 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/strings/UtString.java
> +    public String[] splitWithLimitImpl(String regex, int limit) {
It seems that it is not necessary now, made the method private.

2022-10-10 07:53 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/strings/UtString.java
> +        preconditionCheck();
Removed redundant call to `preconditionCheck()`.

2022-10-10 07:53 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/strings/UtString.java
> +        preconditionCheck();
Fixed.

2022-10-10 07:53 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Extensions.kt
>          // empty string because we want to have a default value of the same sort as the items stored in the strings array
Yes, it seems to be not relevant anymore.

2022-10-10 07:55 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +            }
I was refactoring code to make `split` symbolic, but in this PR these branches are redundant, removed them.

2022-10-10 07:55 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +        val matching = (rgxGen.generate())
I think I just forgot to remove them after some experiments.

2022-10-10 08:02 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +            MethodResult(UtTrue.toBoolValue(), matchingConstraints.asHardConstraint()),
In this method, each of these constants occur only once. I am not sure that we should make them constants because `toBoolValue()` uses Soot globals, that are initialized using the specific JDK. Maybe getters could work, but I don't want to complicate things for just one use. (I am not sure: maybe there would be no problems at all).

I hope I'll eventually complete the second part of String wrapper redesign (symbolic implementation of all regex stuff, so I'll make boolean results easier to construct. Now I think it would better to keep this single usage simple.

2022-10-12 06:01 UTC, Damtev approved these changes
LGTM, perhaps @CaelmBleidd has some functional issues

2022-10-13 09:48 UTC, CaelmBleidd requested changes

2022-10-13 09:48 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Integer.java
> +            value /= value;
Why? Shouldn't it be `value /= 10`?

2022-10-13 09:48 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Long.java
> +            value /= value;
Same about a division

2022-10-13 09:48 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Integer.java
> +        assume(i <= 0x7FFFFFFF); // java.lang.Integer.MAX_VALUE
Why do we have `<=`, but for Byte we have just less?

2022-10-13 09:48 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Integer.java
> +        assume(i != 0);
These are redundant assumes, aren't they?

2022-10-13 09:48 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Short.java
> +
Please, add brackets or write it in one line

2022-10-13 13:22 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Integer.java
> +            value /= value;
Sure. It seems I was too distracted when I fixed the previous comment. I should have noticed it myself.

2022-10-13 13:23 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Long.java
> +            value /= value;
Yes, same "copy-paste" type error.

2022-10-13 13:24 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Short.java
> +
Fixed, thank you.

2022-10-13 13:25 UTC, dtim commented on utbot-framework/src/main/java/org/utbot/engine/overrides/Integer.java
> +        assume(i <= 0x7FFFFFFF); // java.lang.Integer.MAX_VALUE
For `Byte`, the comparison was with "max byte + 1". Replaced it with `< 127` to have the same comparison in all cases.

2022-10-16 05:53 UTC, CaelmBleidd approved these changes

2022-10-16 05:55 UTC, merged