We create temporary files a lot, we have to clean it either
UnitTestBot/UTBotJava pull request #1089
Opened 2022-10-04 17:51 UTC by Vassiliy-Kudryashov

# Description

New cleaning stage was added for files outside "UTBot" directory

## Type of Change

- Minor bug fix (non-breaking small changes)

# How Has This Been Tested?

## Manual Scenario 

Check tempDir, it may contain a lot of small files named like:
- Graph-vis***
- {some digits}-0
- byteBuddyAgent***.jar
- mockitoboot***.jar
We never clean it but we have to.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings

2022-10-05 09:42 UTC, Vassiliy-Kudryashov commented
[Windows never automatically cleans the %TEMP% directory by default. In Windows 10 you have to enable this feature in Settings, and with earlier versions you must delete the files yourself or use programs like Disk Cleanup or cCleaner.
](https://superuser.com/questions/296824/when-is-a-windows-users-temp-directory-cleaned-out#:~:text=Windows%20never%20automatically%20cleans%20the,to%20clean%20up%20after%20themselves.)

2022-10-05 11:11 UTC, Damtev requested changes

2022-10-05 11:11 UTC, Damtev commented on utbot-core/src/main/kotlin/org/utbot/common/FileUtil.kt
> +                        || name.matches(Regex("mockitoboot\\d{10,}\\.jar")))
I suggest extracting these regular expressions out of the loop for a little performance improvement.

Also, are you sure all these files are always created by UnitTestBot? Shouldn't we check a creator?

2022-10-05 11:11 UTC, Damtev commented on utbot-core/src/main/kotlin/org/utbot/common/FileUtil.kt
> +                return@listFiles (TimeUnit.MILLISECONDS.toDays(currentTimeInMillis - creationTime.toMillis()) > daysLimit)
Guess we can introduce a function for this usage and the same usage above

2022-10-06 10:37 UTC, Vassiliy-Kudryashov commented on utbot-core/src/main/kotlin/org/utbot/common/FileUtil.kt
> +                        || name.matches(Regex("mockitoboot\\d{10,}\\.jar")))
"Graph-vis" comes from GraphVix.kt:32 -> moved inside UTBot directory
"cmd-args" comes from Api.kt:1317 -> moved inside UTBot directory

Got rid of:
"\\d{10,}-0" not sure what is the source
"mockitoboot" comes from library code InlineDelegateByteBuddyMockMaker.java:123 but I cannot see new ones anymore
"byteBuddyAgent" comes from library we use via mockito but i cannot see new ones either

2022-10-06 10:37 UTC, Vassiliy-Kudryashov commented on utbot-core/src/main/kotlin/org/utbot/common/FileUtil.kt
> +                return@listFiles (TimeUnit.MILLISECONDS.toDays(currentTimeInMillis - creationTime.toMillis()) > daysLimit)
Done

2022-10-07 04:53 UTC, Damtev approved these changes
LGTM

2022-10-07 04:53 UTC, merged