Useless throws in methods signature
UnitTestBot/UTBotJava pull request #112
Opened 2022-06-01 13:20 UTC by EgorkaKulikov

2022-06-02 14:42 UTC, Damtev requested changes

2022-06-02 14:42 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +        }
Is it correct behavior? I mean, `Class::forName` method, for example, throws `ClassNotFoundException` that is a checked exception and has to be rendered in `throws` block.

2022-06-02 14:42 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            else -> error("Unknown util method $this")
Not util but builtin

2022-06-02 14:42 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            currentTestClass.getArrayLengthMethodId -> emptySet()
I suggest using `with(currentClass)` here

2022-06-02 14:42 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            currentTestClass.getUnsafeInstanceMethodId -> setOf(Exception::class.id)
Could you specify particular thrown exceptions for these methods, please?

2022-06-02 14:45 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +        }
Yes, I added special checks particullary to avoid rendering of these exceptions. They are not required in signatures

2022-06-02 14:46 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            else -> error("Unknown util method $this")
No, util! Because if it is not an util one, we do not go to when statement. It allows us to use error here.

2022-06-02 14:55 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            currentTestClass.getUnsafeInstanceMethodId -> setOf(Exception::class.id)
Sure, will be done in https://github.com/UnitTestBot/UTBotJava/issues/140

2022-06-02 14:55 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            currentTestClass.getArrayLengthMethodId -> emptySet()
Included it in https://github.com/UnitTestBot/UTBotJava/issues/140

2022-06-02 15:32 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            currentTestClass.getArrayLengthMethodId -> emptySet()
Already fixed

2022-06-02 16:17 UTC, denis-fokin commented
Please, link the PR to the issue, and provide a PR description

2022-06-03 10:26 UTC, Damtev approved these changes

2022-06-03 10:34 UTC, merged