Disable test generation for synthetic methods of data classes #1191
UnitTestBot/UTBotJava pull request #1192
Opened 2022-10-19 20:10 UTC by volivan239

# Description

Added filters so that autogenerated by Kotlin methods of data classes are not tested by plugin/cli/contestEstimator

Fixes #1191

## Type of Change

- Minor bug fix (non-breaking small changes)

# How Has This Been Tested? 

## Manual Scenario 

Tested the behavior in plugin -- autogenerated tests are not added to memberlist (unless they are overridden)

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-10-26 02:58 UTC, Damtev requested changes
Add a bit more docs, please

2022-10-26 02:58 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    return false
`when` may be better here, I suppose

2022-10-26 02:58 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +        "copy\\\$default",
What is this method? Add some comments about it, please

2022-10-26 02:58 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    /** List with names of data classes methods that are autogenerated in Kotlin */
Mention that they are actually regexps, please

2022-10-26 03:03 UTC, Damtev requested changes
What about overridden methods in data classes for CLI?

2022-10-26 03:03 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +        return KnownSyntheticMethodNames.dataClassSyntheticMethodNames.any { it.matches(method.name) }
Am I right that CLI will not generate test methods for overridden "synthetic" methods in data classes (`equals`, for example)?

2022-10-26 14:32 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    return false
Is it possible here? `isEnum` and `isData` are just properties...

2022-10-26 14:33 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +        "copy\\\$default",
It is JVM-synthetic and needed when copy is called with default parameters, after last commit it is not needed here.

2022-10-26 14:34 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    /** List with names of data classes methods that are autogenerated in Kotlin */
Fixed, also changed the property name for more clarity

2022-10-26 14:37 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +        return KnownSyntheticMethodNames.dataClassSyntheticMethodNames.any { it.matches(method.name) }
Yes, and it seems difficult (or impossible) to check if the method is not compiler-generated but overridden by user (but if you know the way, I would appreciate hearing it)

2022-10-26 14:40 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    return false
Just a simple one, like
```kotlin
when {
    method.classId.isEnum -> ...
    method.classId.isData -> ...
    else -> ...
}
```

2022-10-26 15:01 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntheticMethods.kt
> +    return false
Done

2022-10-28 10:18 UTC, Damtev approved these changes

2022-10-31 10:28 UTC, merged