Python, JS and Go support #1197
UnitTestBot/UTBotJava pull request #1199
Opened 2022-10-20 12:06 UTC by tamarinvs19

# Description

We added Python and JavaScript tests generation.

### UI

To expand UtBot UI functionality we added next new modules:

* `utbot-ui-common` module:
  - in this module we used no language-specific IntelliJ SDK API
  - this gradle module contains common to all languages logic form `utbot-intellij` to avoid cyclic dependencies in project building
  - `LanguageAssistant` access to dynamically connect API from language dependent modules. Now exists Python, JS and JVM assistants.
  - `BaseTestModel` - parent class for `PythonTestModel`, `JsTestModel` and `GenerateTestModel`. This class was created because `GenerateTestModel` use JVM specific functions
  
* `utbot-intellij-python`, `utbot-intellij-js` modules:
  These modules contain language-specific implementations of `LanguageAssistans`, `BaseTestModel`, `DialogWindow` and other classes.

### Code generation

Previous solution of the problem with different logic for different languages (Java and Kotlin) in code generation which used `CodegenLanguage` should not be used with new languages.

Our solution suggest to use abstract class `CgLanguageAssistant` which contains information about code generation language (e.g. `languageKeywords`, getters for `CgNameGenerator`, `CgMethodConstructor`...). In language-specific modules we can create implementations with language-specific logic.

We did not delete `CodegenLanguage.JAVA` and `CodegenLanguage.Kotln`, but it is possible if our solution will be approved.
Base implementation for `Java` and `Kotlin` we have already added in `org.utbot.framework.plugin.api`.

Analogically we added `LanguageTestFrameworkManager` to organize test framework logic for different languages.

### CLI

Modules `utbot-cli-python` and `utbot-cli-js` contain command line generation and run tests interface for Python and JavaScript. They depends on `utbot-cli` module.

### Main language modules:

Modules `utbot-python` and `utbot-js` can be used from IntelliJ-plugin and from CLI. They contain independent of PSI logic, for example, language `UtModel`s, fuzzing and code generation declarated there.

Fixes #1197

## Type of Change

Please delete options that are not relevant.

- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

We have code examples for testing how UtBot works:
* `utbot-python/samples/`
   There are script `generate_test_samples.sh` for automatic run generation test from cli and `run_test_samples.sh` for run generated tests.
* `utbot-js/samples/`

## Manual Scenario 

* Open Python-, JavaScript-project in IDEA and run UtBot plugin.
* Or, generate and run test with CLI.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-10-24 08:47 UTC, Markoutte requested changes
I tried to merge this branch onto main and it looks like that here still some problems with with branch: 
1. java codegen creates uncompilable tests
2. runIde does start with IC platform
3. many red code

2022-10-25 15:02 UTC, tamarinvs19 commented
> I tried to merge this branch onto main and it looks like that here still some problems with the branch:
> 
> 1. java codegen creates uncompilable tests
> 2. runIde does not start with IC platform
> 3. many red code

1. I fixed bug with test class name, now I can generate valid tests for java

2022-10-27 05:13 UTC, Markoutte commented on utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/ui/components/TestFolderComboWithBrowseButton.kt
> +        setButtonEnabled(false)
Looks like this class is different to main branch at the moment. Can cause regressions

2022-10-27 05:13 UTC, Markoutte commented on utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/ui/utils/ModuleUtils.kt
> +    //if (project.isBuildWithGradle) return null
Looks like this class is different to main branch at the moment. Can cause regressions

2022-10-27 05:15 UTC, Markoutte commented on gradle.properties
> +ideType=IU
Till "IU", but I think it is better if this option is IC by default

2022-10-27 05:22 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/tree/CgElement.kt
> +open class CgGetClass(val classId: ClassId) : CgReferenceExpression {
Possibly can break some "when" statements

2022-10-27 05:28 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DependencyPatterns.kt
> +        else -> throw UnsupportedOperationException()
I think it is better to not throwing anything from methods like these. Can the logic be more robust in appropriate method calls?

2022-10-27 05:33 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/framework/concrete/MockValueConstructor.kt
> +            else -> throw UnsupportedOperationException()
Again, I don't know how's good to add an exception to the logic. It can cause some problems if there's no handlers for it. Maybe some "special" value can be introduced to stub non-Java models?

2022-10-27 05:49 UTC, Markoutte requested changes
Please, see comments. Also, there's a bunch of changes in codegen module. @EgorkaKulikov , could you, please, review them?

2022-10-27 09:51 UTC, alisevych commented
Please check the size of the plugin - there is a restriction to keep it below 100 MB
Now you have 769 MB in the build from this branch:
![image](https://user-images.githubusercontent.com/37301492/198252694-a8831a13-7120-4cae-a3eb-318a123ce295.png)

2022-10-27 10:33 UTC, tamarinvs19 commented on utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/ui/components/TestFolderComboWithBrowseButton.kt
> +        setButtonEnabled(false)
Fixed

2022-10-27 13:24 UTC, alisevych commented
For the [new build from this branch](https://github.com/UnitTestBot/UTBotJava/actions/runs/3336631113)

<details>
<summary>
Installation of the plugin is failing - IDEA is requiring restart - after restart there is no plugin installed. 
When user chose "restart later", the following exception fell in IDEA (2022.1.4)
</summary>
update failed for AnAction(org.utbot.intellij.plugin.ui.actions.GenerateTestsAction, id=org.utbot.intellij.plugin.ui.actions.GenerateTestsAction) with text=Generate Tests with UnitTestBot...

java.lang.IllegalStateException: Unknown language id: TEXT
	at org.utbot.intellij.plugin.language.agnostic.LanguageAssistantKt.loadWithException(LanguageAssistant.kt:35)
	at org.utbot.intellij.plugin.language.agnostic.LanguageAssistantKt.access$loadWithException(LanguageAssistant.kt:1)
	at org.utbot.intellij.plugin.language.agnostic.LanguageAssistant$Companion.get(LanguageAssistant.kt:18)
	at org.utbot.intellij.plugin.ui.actions.GenerateTestsAction.update(GenerateTestsAction.kt:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:645)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:210)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:208)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

</details>

2022-10-28 08:16 UTC, Markoutte reviewed
At the moment it looks good to me

2022-10-28 08:17 UTC, Markoutte submitted a review, later dismissed

2022-10-31 09:35 UTC, Damtev requested changes
Except for some moments, it looks working. But, to be honest, there are a lot of code style (and, moreover, code quality) problems, that are very recommended to be fixed. I suggest making several iterations of code review before merging this PR to the main branch.

2022-10-31 09:48 UTC, zishkaz commented on utbot-cli-js/src/main/kotlin/org/utbot/cli/js/Application.kt
> +class UtBotCli : CliktCommand(name = "UnitTestBot JavaScript Command Line Interface") {
Fixed

2022-10-31 09:50 UTC, zishkaz commented on utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsDialogWindow.kt
> +        //TODO: fix.
This comment references a line of code below it, as we haven't completed the search for a path to NodeJs.exe

2022-10-31 09:55 UTC, zishkaz commented on utbot-js/src/main/kotlin/framework/api/js/JsApi.kt
> +class JsEmptyClassId : JsClassId("empty")
This class is used to mock JsClassId when UtModel is constructed. Located in `utbot-js/src/main/kotlin/api/JsUtModelConstructor.kt`, constructor ingores JsEmptyClassId and uses only value itself to make UtModel.

2022-10-31 09:57 UTC, zishkaz commented on utbot-js/src/main/kotlin/service/BasicCoverageService.kt
> +            throw e
It was used for `finally` segment, since we really want to remove all temp files even though this function failed. However, this block of code will be discussed with our mentor

2022-10-31 09:58 UTC, zishkaz commented on utbot-js/src/main/kotlin/service/CoverageServiceProvider.kt
> +            "const fs = require(\"fs\")\n\n"
Answered in the first comment tackling this issue

2022-10-31 11:53 UTC, tamarinvs19 commented on utbot-cli-python/src/main/kotlin/org/utbot/cli/language/python/Application.kt
> +class UtBotCli : CliktCommand(name = "UnitTestBot Python Command Line Interface") {
Fixed

2022-10-31 11:57 UTC, tamarinvs19 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt
> +            else -> UtConcreteValue(null, model.classId.jClass)
No, we don't have. I changed this line to UnsupportedExeption, we cannot use ConcreveValue now and so this branch too.

2022-10-31 11:58 UTC, tamarinvs19 commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/CodeGenerator.kt
>      // null if no util class needed, e.g. when we are generating utils directly into test class
Fixed

2022-10-31 12:38 UTC, zishkaz commented on utbot-js/src/main/kotlin/framework/codegen/JsDomain.kt
> +    override val methodSourceAnnotationFqn = "Parameterized tests are not supported for Mocha"
Fixed

2022-10-31 13:00 UTC, rudolf101 commented on utbot-js/src/main/kotlin/service/BasicCoverageService.kt
> +                val resFile = File("$utbotDirPath/$tempFileName$index.json")
This solution proved to be good on both UNIX and Windows. Due to the problems described in [this answer](https://github.com/UnitTestBot/UTBotJava/pull/1199#discussion_r1009215478), we adhere to this solution.

2022-10-31 13:25 UTC, zishkaz commented on utbot-js/src/main/kotlin/api/JsTestGenerator.kt
> +        Thread.currentThread().contextClassLoader = Context::class.java.classLoader
Fixed

2022-11-01 09:58 UTC, rudolf101 commented on utbot-js/src/main/kotlin/service/BasicCoverageService.kt
> +            throw e
Removed

2022-11-01 10:13 UTC, rudolf101 commented on utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsDialogWindow.kt
> +        //TODO: fix.
Fixed weak comments

2022-11-01 10:57 UTC, tochilinak commented on utbot-framework/src/main/kotlin/org/utbot/framework/minimization/Minimization.kt
> +        else -> 0
In module utbot-framework PythonModel and JsUtModel are not seen, for Idea type IC JS is even turned off completely. To calculate sizes for them all this logic should be moved somewhere else.

In JS for now all models have the same size. In Python they might be different, but structure of Python models are completely different from Java UtModels (at least for now).

Is it worth working on right now? It doesn't seem to make a lot of difference in result.

2022-11-01 11:38 UTC, denis-fokin commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DependencyPatterns.kt
> +        else -> throw UnsupportedOperationException()
Looks like if we got a test library that we had not expected it is a problem that we do not want to be concealed. I would leave it this way so far.

2022-11-01 11:43 UTC, denis-fokin commented on utbot-framework/src/main/kotlin/org/utbot/framework/concrete/MockValueConstructor.kt
> +            else -> throw UnsupportedOperationException()
I do not think that a "special" value is a better solution. But some improvement deserves deeper investigation.

2022-11-01 11:57 UTC, denis-fokin commented on utbot-framework/src/main/kotlin/org/utbot/framework/minimization/Minimization.kt
> +        else -> 0
Let's create an issue for this and resolve the problem afterwards. The main consideration now is to include the solutions in our infrastructure and do not break our Java/Kotlin parts.

2022-11-01 12:07 UTC, Damtev approved these changes

2022-11-02 09:15 UTC, tamarinvs19 commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/tree/CgElement.kt
> +open class CgGetClass(val classId: ClassId) : CgReferenceExpression {
Now this class is sealed

2022-11-09 07:36 UTC, merged