Rd & logs refactoring
UnitTestBot/UTBotJava pull request #1399
Opened 2022-11-18 10:16 UTC by Domonion

# Description

Multiple refactorings and enhacements for process starting. 
Removed ```UtSettings.logConcreteExecutionErrors``` and ```UtSettings.engineProcessLogLevel``` switches. 
Logs for engine and concrete executor processes are always enabled. 
Switched log configuration to ```utbot-intellij/log4j2.xml```. 
Use ```UtSettings#getIdeaProcessLogConfigFile``` from ```~/.utbot/settings.properties``` to configure logs for engine and concrete executor processes without rebuilding plugin.

## Type of Change

- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

CI

2022-11-22 09:31 UTC, korifey approved these changes

2022-11-22 11:36 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * @see org.utbot.intellij.plugin.process.EngineProcess
I would suggest the next wording, what do you think?

The property is useful only for  the IntelliJ IDEs. If the property is set in true the engine process opens a debug port.

2022-11-22 11:37 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * Port which will be used for debugging engine process
In order to get rid of the pasive voice:

The engine process debug port number

2022-11-22 11:43 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var engineProcessDebugSuspendPolicy by getBooleanProperty(true)
I would say that `policy` usually suggests a set of rules. What about a statement that assumes true/false questions?

suspendEngineProcesExecutionInDebugMode

2022-11-22 12:17 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * Whether engine process should suspend until debugger attached
Value of the suspend mode for the JDWP agent of the engine process. If the value is true, the engine process will suspend until a debugger attaches to it.

2022-11-22 12:21 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * Port which will be used for debugging instrumented process
The JDWP agent's port of the instrumented process. A debugger attaches to the port in order to debug the process.

2022-11-22 12:22 UTC, denis-fokin commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var instrumentedProcessSuspendPolicy by getBooleanProperty(true)
I would change the wording the similar way I suggested with 'engineProcessDebugSuspendPolicy'

2022-11-23 06:59 UTC, sergeypospelov approved these changes

2022-11-23 06:59 UTC, sergeypospelov commented on docs/contributing/InterProcessDebugging.md
>  2. Set `runIdeaProcessWithDebug` property to _true_. This enables `EngineProcess.debugArgument`.
Looks like we don't have such property. Perhaps, the author meant `runEngineProcessWithDebug`.

2022-11-23 06:59 UTC, sergeypospelov commented on docs/RD for UnitTestBot.md
> +	- ```UtInstrumentationProcess``` - encapsulates logic for preparing instrumented process for executing arbitary commands. Exposes ```protocolModel``` for communicating with instrumented process.
I guess, you mean  `InstrumentedProcess` instead of `UtInstrumentationProcess`

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/InstrumentedProcess.kt
> +    val chidlProcessModel: InstrumentedProcessModel = onSchedulerBlocking { protocol.instrumentedProcessModel }
Typo: `childProcessModel`

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/ConcreteExecutor.kt
> -            Runtime.getRuntime().addShutdownHook(thread(start = false) { defaultPool.close() })
How does the pool close now?

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/CodeGenerationController.kt
> +                            proceedTestReport(proccess, model)
Why did you change the order?

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-rd/src/main/kotlin/org/utbot/rd/ClientProcessUtil.kt
> +internal fun signalInstrumentedReady(port: Int) {
Do you sure it's for the instrumented process only? Looks like, it's also used in the engine process.

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-rd/src/main/kotlin/org/utbot/rd/RdSettingsContainer.kt
> +                    throw NotImplementedError("Setting properties allowed only from plugin process")
Minor: maybe throw an illegal state exception?

2022-11-23 06:59 UTC, sergeypospelov commented on utbot-rd/src/main/kotlin/org/utbot/rd/UtRdCoroutineScope.kt
> +            // only to initialize load and initialize class
I didn't get it.

2022-11-23 07:01 UTC, sergeypospelov requested changes
Due to missclick :)

2022-11-25 10:06 UTC, Domonion commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/ConcreteExecutor.kt
> -            Runtime.getRuntime().addShutdownHook(thread(start = false) { defaultPool.close() })
From now not only ConcreteExecutor, but all LifetimedProcesses are closed at the end of the process. See `LifetimedProcess.kt`

2022-11-25 10:08 UTC, Domonion commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/CodeGenerationController.kt
> +                            proceedTestReport(proccess, model)
Because previously test report was generation on UI thread blocking it, while it nor WL nor WIL required.

2022-11-25 10:20 UTC, Domonion commented on utbot-rd/src/main/kotlin/org/utbot/rd/UtRdCoroutineScope.kt
> +            // only to initialize load and initialize class
Rd has it's own Coroutine scope. It is singleton, initialized statically and uses Dispatchers.Default. 
Also IDEA has it's own RdCoroutineHost. We can't reference IDEA's RD as it will break plugin because we would try to load classes with the same name from different jars.
UtBot overrides it for it's own logic with LifetimedProcess and simplifying choice. But as it is still just companion object(static class) - we need to initialize it. This function is solely for this purpose

2022-11-25 10:26 UTC, Domonion commented
@denis-fokin @sergeypospelov @olganaumenko please, read design docs

2022-11-25 13:35 UTC, denis-fokin approved these changes

2022-11-25 13:46 UTC, Domonion commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/generated/InstrumentedProcessRoot.Generated.kt
> +
This code is automatically generated by rdgen, I bumped version and regenerated models

2022-11-25 14:22 UTC, Domonion commented on utbot-rd/src/main/kotlin/org/utbot/rd/exceptions/InstantProcessDeathException.kt
> +                text += " Process requested debug on port - $debugPort, check if port is open."
Because concatenation does not add space between cancatinated strings

2022-11-26 03:10 UTC, sergeypospelov approved these changes

2022-11-26 03:10 UTC, sergeypospelov commented on docs/RD for UnitTestBot.md
> +3. `InstrumentedProces` - process where concrete execution takes place.
```suggestion
3. `InstrumentedProcess` - process where concrete execution takes place.
```

2022-11-26 03:10 UTC, merged