RD_for_UnitTestBot.md reviewed
UnitTestBot/UTBotJava pull request #1453
Opened 2022-12-05 10:58 UTC by olganaumenko

# Description

The review for RD_for_UnitTestBot.md -- linguistic fixes added.

## Type of Change

Documentation review.

# How Has This Been Tested?

IntelliJ IDEA preview (rendered) for the text itself.

# Checklist (remove irrelevant options):

- [+ ] New documentation is provided or existed one is altered

2022-12-05 12:36 UTC, Domonion requested changes

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> -## Table of content
Why remove table of content&

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +These processes are built on top of the [Reactive distributed communication framework (Rd)](https://github.com/JetBrains/rd) developed by JetBrains. Understanding Rd is crucial for understanding Unit
> Understanding Rd is crucial for understanding

I would better use different working

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +instances of `LifetimeDefinition` and thus they can be terminated. You can register callbacks in the `Lifetime` object and then terminate it — all the registered callbacks will be executed upon the t
1. > `Lifetime` is an abstract class, with `Lifetime` and `LifetimeDefinition` as its inheritors.

Lifetime is an abstract class, not its inheritor
2. > The `Lifetime` objects are 
instances of `LifetimeDefinition` and thus they can be terminated.

IMO sentence indicates that you can terminate Lifetime because it is lifetime definition, but it is not true. The main idea - only LifetimeDefinition can be terminated. This is very important info.
2. > You can register callbacks in the `Lifetime` object and then terminate it

It seems like you can terminate `Lifetime`, but it is not true.

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `onTermination` executes _lambda_/_closeable_ when the `Lifetime` object is terminated. If an object has been
> `Lifetime` object

`Lifetime` instance. it looks like Lifetime has some other internal object for termination, i would change all occurence of `Lifetime object` to `Lifetime instance`.

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +  object is not terminated until _lambda_ execution is complete.
1. Object. 
2. I would use future tense to emphasize that it will be alive through all lambda execution, as  `is not terminated` -> `will not be terminated`, `is complete -> will complete`. IMO current wording it seems like lifetime guaranteed to be alive only at start

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `createdNested` creates the _child_ `LifetimeDefinition` object that is terminated along with the _parent_ one.
> Along with parent

Not along, it either
1. terminates if parent terminates
2. can be terminated separately, and parent ___will not be terminated___. 

This is important to emphasize as it is one of the key features of lifetimes - structured concurrency, they are structured as tree and you can terminate subtree separately

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `Eternal` prevents a `Lifetime` object from being terminated.
1. object
2. This is completely different:
`Lifetime.Eternal` is ___another___ Lifetime instance, specially hardcoded as the one that will not be terminated. ` It is not method or property, this is separate global object. It has nothing to with other Lifetime instances

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `Terminated` makes a `Lifetime` object terminated.
Same as `Eternal` - it is different instance of Lifetime, global instance of already terminated one, specially hardcoded

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +These are Rd entities:
IMO it is useful to indicate that it is only subset of all rd entities

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `RdCall`is the remote procedure call.
space

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +multiple `Root` extensions to the `Protocol`. To generate the auxiliary structures, define them as direct fields.
why `,` here instead of `-`?

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +	- Both processes create protocols. Bind the model and setup callbacks.
It is not clear who should `bind the model and setup callbacks`.

2022-12-05 12:36 UTC, Domonion commented on docs/RD for UnitTestBot.md
> +- `packages` — `.java` package names to search in toplevels, delimited by `,`. Example: `com.jetbrains.rd.model.nova,com,org`.
Not `.java` package name as models are defined in kotlin `.kt` files. I meant exactly Java Packages.

2022-12-05 12:59 UTC, olganaumenko commented on docs/RD for UnitTestBot.md
> -## Table of content
It is already here -- the autogenerated GitHub TOC.

2022-12-05 15:39 UTC, olganaumenko commented on docs/RD for UnitTestBot.md
> +multiple `Root` extensions to the `Protocol`. To generate the auxiliary structures, define them as direct fields.
As far as I know, an introductory infinitive phrase usually looks like this:
[To get a seat, you'd better come early.](https://owl.purdue.edu/owl/general_writing/punctuation/commas/extended_rules_for_commas.html#:~:text=To%20get%20a%20seat%2C%20you%27d%20better%20come%20early.)
[To be a diplomat, one must speak a number of languages, including doubletalk.](https://www.grammar-monster.com/glossary/infinitive_phrase.htm#:~:text=To%20be%20a%20diplomat%2C%20one%20must%20speak%20a%20number%20of%20languages%2C%20including%20doubletalk.)

2022-12-06 09:51 UTC, Domonion approved these changes

2022-12-06 10:02 UTC, merged