Wrappers for concurrency classes
UnitTestBot/UTBotJava pull request #1535
Opened 2022-12-16 08:15 UTC by Damtev

# Description

In this PR implemented wrappers for several classes for concurrency:

- `java.lang.Thread`
- `java.lang.ThreadGroup`
- `java.util.concurrent.CompletableFuture`
- `java.util.concurrent.ExecutorService`
- `java.util.concurrent.CountDownLatch`

Fixes #1534.

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Regression and integration tests

Not applicable.

## Automated Testing

New tests in the package `org.utbot.examples.threads`.

## Manual Scenario 

Tested on the closed customer project.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

2022-12-30 06:55 UTC, CaelmBleidd requested changes

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/CompletableFuture.java
> +            return new UtCompletableFuture<>(value).toCompletableFuture();
Why do you create a wrapper from a wrapper instead of creating an instance of the original class?

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtCompletableFuture.java
> +public class UtCompletableFuture<T> implements Future<T>, ScheduledFuture<T>, CompletionStage<T> {
Redundant `Future<T>`

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtCompletableFuture.java
> +        visit(this);
Do we need this `alreadyVisited`? It is suppose to reduce number of instructions we process for a wrapper's instance, but here there is only one instruction `eqGenericType`, and we make two additional operations `visit` and `alreadyVisited`

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtExecutorService.java
> +public class UtExecutorService implements ExecutorService, ScheduledExecutorService {
Redundant `ExecutorService`

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtExecutorService.java
> +    }
This precondition check doesn't do anything

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtThread.java
> +        this(null, target, name, 0);
here and everywhere else -- constants without names

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtThreadGroup.java
> +        for (int i = 0 ; i < ngroups ; i++) {
Formatting

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +                    previousFieldValues.remove(sootField)
Why? Add a comment about it

2022-12-30 06:55 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/ThreadWrappers.kt
> +    get() = utCompletableFutureClass.getMethodByName(UtCompletableFuture<*>::eqGenericType.name).signature
These ones could be implemented without `get`

2022-12-30 08:53 UTC, Damtev commented on utbot-sample/src/main/java/org/utbot/examples/threads/FutureExamples.java
> +        final CompletableFuture<Integer> future = CompletableFuture.supplyAsync(() -> 42);
Already added

2022-12-30 09:18 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        memory.fieldValue(field, addr)?.let {
I am not sure it really looks better - the first option requires a bit more code, and the second can hide early-return for a developer

2022-12-30 09:18 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/types/TypeResolver.kt
> +internal val CLASS_REF_SOOT_CLASS = Scene.v().getSootClass(CLASS_REF_CLASSNAME)
Already fixed

2022-12-30 09:23 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/ObjectWrappers.kt
> +    val selectOperationTypeIndex: Int
Properties in interfaces are always open

2022-12-30 09:24 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/CompletableFuture.java
> +            return new UtCompletableFuture<>(value).toCompletableFuture();
Added a note in the PR description

2022-12-30 09:30 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/threads/UtThread.java
> +        this(null, target, name, 0);
Unfortunately, it's Java code

2022-12-30 09:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +                    previousFieldValues.remove(sootField)
It is used in a condition depending on `classIdToClearStatics`, so I think it should be obvious for a reader

2022-12-30 10:10 UTC, Damtev commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/threads/ExecutorServiceExamplesTest.kt
> +// and should not be used for testing conrete or code generation since they are possibly flaky in the real execution
It is not very obvious what should we do in such cases on the concrete execution side. I created a task for it #1610.

2023-01-03 02:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SootUtils.kt
> +    org.utbot.framework.plugin.api.visible.UtStreamConsumingException::class,
It is not `utbot-api` module, it is `utbot-framework-api` which is not an actual API. This package is called `visible` since this class should be visible in almost all parts of the tool - Soot, engine, concrete execution, and code generation.

2023-01-03 02:56 UTC, CaelmBleidd approved these changes

2023-01-03 05:44 UTC, merged