Utbot logging
UnitTestBot/UTBotJava pull request #1547
Opened 2022-12-16 14:10 UTC by Domonion

# Description

1. Added Logger model to rd
2. InstrumentedProcess is now sending all logs to EngineProcess, which then writes to its own file
3. Removed instrumentedProcessLogLevel
4. auxiliary log functions
5. stop process rdcall
6. UtRd Loggers redesigned to have the same logging parttern

Fixes # (issue)

## Type of Change

- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-01-27 09:19 UTC, sergeypospelov requested changes
Looks OK after fixing remarks, but I didn't dive into details deeply. I guess, you need to update docs.

2023-01-27 09:19 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgMethodConstructor.kt
> +//            }
Why is it commented?

2023-01-27 09:19 UTC, sergeypospelov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/InstrumentedProcessMain.kt
> -        logger.debug { "received invokeMethod request: ${params.classname}, ${params.signature}" }
Why did we lost this?

2023-01-27 09:19 UTC, sergeypospelov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/ConcreteExecutor.kt
> +//                    }
Remove if we don't need it.

2023-01-27 09:49 UTC, Domonion commented on utbot-core/src/main/kotlin/org/utbot/common/Logging.kt
> +inline fun <T> silent(block: () -> T): T? {
Used - ProcessWithRdServer

2023-01-27 15:31 UTC, Domonion commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/InstrumentedProcessMain.kt
> -        logger.debug { "received invokeMethod request: ${params.classname}, ${params.signature}" }
fixed

2023-01-31 07:12 UTC, sergeypospelov approved these changes

2023-02-02 10:27 UTC, alisevych commented
@Domonion Please add logging of Summarization phase: started - ended.

2023-02-07 15:14 UTC, EgorkaKulikov reviewed
LVGNP2m

2023-02-07 15:14 UTC, EgorkaKulikov commented on utbot-rd/src/main/kotlin/org/utbot/rd/loggers/UtRdRemoteLogger.kt
> +        // On every protocol send/receive event RD to its own loggers.
sends

2023-02-07 15:14 UTC, EgorkaKulikov commented on utbot-rd/src/main/kotlin/org/utbot/rd/loggers/UtRdRemoteLogger.kt
> +        internal val threadLocalExecuting get() = threadLocalExecutingBackingFiled.get()
do not change it to by Threadlocal

2023-02-07 15:14 UTC, EgorkaKulikov commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +fun UtMethodTestSet.summarizeOne(searchDirectory: Path, sourceFile: File?): UtMethodTestSet = logger.info().bracket({ "Summarization for ${this.method}"} ){
Make it private please

2023-02-08 08:41 UTC, Domonion commented on docs/InterprocessLogging.md
> +```kotlin
It is already in javadoc, it is just mentioned for clarification that this option is available

2023-02-08 13:54 UTC, EgorkaKulikov approved these changes

2023-02-08 14:32 UTC, merged