Add options for clinit sections
UnitTestBot/UTBotJava pull request #1636
Opened 2023-01-09 08:31 UTC by CaelmBleidd

# Description

Add two options for clinit sections: one for processing all clinit sections concretely and one for not processing them at all. 
Depending on these options, we can disable some parts of the analysis and significantly increase our performance. 

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Regression and integration tests

The same as automatic tests.

## Automated Testing

Tests from `org.utbot.examples.objects.ClassForTestClinitSectionsTest`

## Manual Scenario 

Checked on contest estimator and `guava-26` project

# Checklist:

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2023-01-09 08:43 UTC, Damtev requested changes

2023-01-09 08:43 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * If [disableClinitSectionsAnalysis] is true, it disables effect of this function as well.
Not a `function` but an `option`, I guess

2023-01-09 08:43 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/testcheckers/SettingsModificators.kt
> +
Could you add a value to set as a parameter to these functions and rename the first function with `with` prefix, please? It's a bit more convenient

2023-01-09 08:43 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        }
Perhaps, move these checks to the top of the method? These checks are more trivial than `shouldProcessStaticFieldConcretely` one

2023-01-09 10:11 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        }
No, because otherwise we might lose enums initialization

2023-01-10 03:58 UTC, Damtev requested changes

2023-01-10 03:58 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +     * If [enableClinitSectionsAnalysis] is true, it disables effect of this option as well.
If [enableClinitSectionsAnalysis] is **FALSE**, I guess

2023-01-10 04:07 UTC, Damtev approved these changes

2023-01-10 04:23 UTC, merged