Redesign for Concrete Executor timeout
UnitTestBot/UTBotJava pull request #1728
Opened 2023-01-20 14:15 UTC by Domonion

# Redesign for Concrete Executor timeout

## Description

Fix #1726 

### Manual tests

See #1726 for repro - should fix

2023-01-26 17:12 UTC, Domonion reviewed
@sergeypospelov

2023-01-26 17:12 UTC, Domonion commented on docs/ResultAndErrorHandlingApiOfTheInstrumentedProcess.md
> +## UtConcreteExecutionInstrumentation
There are no such class, consider `UtExecutionInstrumentation` @sergeypospelov

2023-01-26 17:12 UTC, Domonion commented on docs/ResultAndErrorHandlingApiOfTheInstrumentedProcess.md
> +The clients cannot depend that cancellation request immediately breaks the invocation inside the _instrumented process_. The invocation is guaranteed to finish in the time of passed timeout, but not
It is a bit not clear, I think better wording is:
> The invocation is guaranteed to finish in the time of passed timeout. It may or ***may not*** finish earlier. Already started query in instrumented process is ***uncancellable*** - this as designed.

2023-01-27 07:49 UTC, sergeypospelov requested changes

2023-01-27 07:49 UTC, sergeypospelov commented on .github/workflows/build-and-run-tests-from-branch.yml
> +        continue-on-error: true
Why?

2023-01-27 07:49 UTC, sergeypospelov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> +            var savedStatics: Map<FieldId, Any?>? = null
It smells, IMO. I suggest adding a field in the `postprocessingPhase` holding stored statics.

2023-01-27 07:49 UTC, sergeypospelov commented on utbot-junit-contest/build.gradle
> +    implementation group: 'com.jetbrains.rd', name: 'rd-core', version: rdVersion
For what?

2023-01-27 08:43 UTC, Domonion commented on .github/workflows/build-and-run-tests-from-branch.yml
> +        continue-on-error: true
Discussed with @bissquit

2023-01-27 08:45 UTC, Domonion commented on utbot-junit-contest/build.gradle
> +    implementation group: 'com.jetbrains.rd', name: 'rd-core', version: rdVersion
fixed

2023-01-27 08:56 UTC, Domonion commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> +            var savedStatics: Map<FieldId, Any?>? = null
fixed

2023-01-27 09:21 UTC, sergeypospelov approved these changes

2023-01-27 09:21 UTC, merged