Add support for virtual invokes on enums
UnitTestBot/UTBotJava pull request #1746
Opened 2023-01-24 15:41 UTC by CaelmBleidd

## Description

Now we create enum instances without concrete type when it comes as a parameter into a function. This allows us to support virtual invokes on enum instances.

Also, this request contains some a fix related to resolving enum instances retrieved from concrete and its instantiation in the Resolver: we should use everywhere not a type for some enum constant, but a type of its superclass (since an enum constant is not an instance of Enum). Corresponding comments are added to the code.

Fixes #1704, SAT-1686

## How to test

### Automated tests

Tests from class `org.utbot.examples.enums.ClassWithEnumTest`

### Manual tests

There are no manual tests.

## Self-check list

Check off the item if the statement is true:

- [ ] I've set the proper **labels** for my PR (at least, for category and component).
- [ ] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments**, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-01-24 15:47 UTC, Damtev commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/enums/ClassWithEnumTest.kt
> +            eq(2),
Why it is not `between(2..3)` as above? The second matcher matches 2 branches

2023-01-24 15:54 UTC, Damtev commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/enums/ClassWithEnumTest.kt
> +                // we cannot check x since it is not a meaningful value
Please, add more comments why it is not meaningful

2023-01-24 15:56 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    // We check a superclass here since we added a superclass in here, not enum instances
This comment is not very clear, please rewrite it somehow

2023-01-24 15:56 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    // We check a superclass here since we added a superclass in here, not enum instances
Same about comment

2023-01-24 15:57 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        val typeStorage = typeResolver.constructTypeStorage(type, useConcreteType = false)
Add a comment about the importance of this `false`, please

2023-01-25 08:17 UTC, CaelmBleidd commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/enums/ClassWithEnumTest.kt
> +            eq(2),
Because in this method only two branches exist: when we have a parameter that is equal to `READY` and when we do not.

2023-01-25 09:25 UTC, Damtev requested changes

2023-01-25 09:25 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +        }
Please, extract a common function for this method and the same in Memory

2023-01-25 09:48 UTC, Damtev approved these changes

2023-01-25 10:36 UTC, merged