Update python unit test generation
UnitTestBot/UTBotJava pull request #1763
Opened 2023-01-31 11:44 UTC by tamarinvs19

## Description

It is a new version of Python UTBot.

Updates:
* Now we use only new fuzzing platform
* New python object serialization and deserialization strategy
* New type inference algorithm
* Remove `python3parser` (it was the biggest dependency)
* Simple state after / state before asserts

## How to test

### Manual tests

We have some examples in `/utbot-python/samples` directory.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-02-06 08:48 UTC, Markoutte commented
At the moment it throws an exception for a method that isn't declared with class:

```python
def test(self, x):
    if (x < 0):
        return -1
    return x*x

print(test(2))
```

When trying to generate for method `test` it throws:

```
java.lang.NullPointerException
	at org.utbot.python.PythonTestCaseGenerator.findMethodByDescription(PythonTestCaseGenerator.kt:54)
	at org.utbot.python.PythonTestCaseGenerator.generate(PythonTestCaseGenerator.kt:98)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration(PythonTestGenerationProcessor.kt:109)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration$default(PythonTestGenerationProcessor.kt:32)
	at org.utbot.intellij.plugin.language.python.PythonDialogProcessor$createTests$1.run(PythonDialogProcessor.kt:161)
```

2023-02-06 08:50 UTC, Markoutte requested changes
Please, update branch to make it compilable with changes in JS module

2023-02-10 09:38 UTC, Markoutte approved these changes

2023-02-10 10:47 UTC, tamarinvs19 commented on utbot-python-parser/build.gradle
> +
Fixed

2023-02-10 10:47 UTC, merged