Add python and js docker images building #942
UnitTestBot/UTBotJava pull request #1764
Opened 2023-02-01 06:53 UTC by bissquit

## Description

Add docker image publishing for python and js

Fixes #942

## How to test

### Automated tests

Not applicable

### Manual tests

Run image publishing from a branch manually

## Self-check list

- [ ] build cli locally for each language*
- [ ] run pipeline from a branch**

\* use the following command to repeat building environment at your local PC/laptop
```shell
docker run -it --rm --name=build-cli --workdir=/data -v "<path-to-repo>:/data" unittestbot/java-env:java11-zulu-jdk-gradle7.4.2-kotlinc1.7.0 /bin/bash
# the following command you'll run inside container
cd <utbot-cli/utbot-cli-js/utbot-cli-python>
VERSION="$(date +%Y).$(date +%-m)"
gradle build --no-daemon --build-cache --no-parallel -Dorg.gradle.jvmargs=-Xmx2g -Dkotlin.daemon.jvm.options=-Xmx4g -x test -PsemVer=${VERSION}
# wait for BUILD SUCCESSFUL or fix issues
```
** change conditions in a pipeline to publish images

2023-02-06 07:07 UTC, victoriafomina requested changes

2023-02-06 07:07 UTC, victoriafomina commented on .github/workflows/build-and-run-tests.yml
> +            dockerfile_path: docker/Dockerfile_Python
Dockerfile_java_cli, Dockerfile_javascript and Dockerfile_Python: different naming of docker files

2023-02-06 08:17 UTC, victoriafomina approved these changes
LGTM

2023-02-22 08:01 UTC, denis-fokin approved these changes

2023-03-02 08:50 UTC, merged