[draft] Support test class fields rendering (Spring support)
UnitTestBot/UTBotJava pull request #1788
Opened 2023-02-13 14:45 UTC by sofurihafe

## Description

TBD

Fixes # (issue)

## How to test

### Automated tests

TBD

### Manual tests

TBD

2023-02-15 06:47 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/Domain.kt
> +    abstract val beforeEachAnnotation: String
We should not forget that these annotations are different in JUnit4, JUnit5 and TestNg, so take it into account in naming, please, and locate corresponding overrides it test framework related classes.

2023-02-15 07:04 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> +class CgFieldDeclaration(
Possibly we should have `classId` of the class containing field here too...

2023-02-18 15:31 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> +class CgFieldDeclaration(
Done.

2023-02-18 15:33 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/Domain.kt
> +    abstract val beforeEachAnnotation: String
There were equivalents of BeforeEach annotation from JUnit5.
Renamed and removed them from abstract vals.

2023-02-27 13:25 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/TestClassModel.kt
> +    val injectedMockModels: List<UtModel> = listOf(),
May be a Set here?

2023-02-27 13:25 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +                execution.stateBefore.thisInstance?.let { allModelsInExecution += it; thisInstances += it }
Lets split it: one statement per line

2023-02-27 13:26 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +            .filter { it != classUnderTest }
This check is out of date. May be something like `it !in injectedModels`

2023-02-27 13:32 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +        if (allModels.any { it === currentModel }) {
It's seems to be ok, an `IdentityHashMap` used in `AssembleModelGenerator` is used for keys reference equality there too. I suggest to remove TODO.

2023-02-27 13:33 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt
> +        }
`println()` here ?

2023-02-27 13:35 UTC, EgorkaKulikov commented
Currently crashed on the following method from out sample project:

```java
public List<Order> getOrders(boolean flag) {
        if (flag) {
            return orderRepository.findAll();
        }

        return new ArrayList<>();
    }
```

Crash reason is:

```
        // Couldn't generate some tests. List of errors:
        // 
        // 1 occurrences of:
        /* class org.utbot.framework.plugin.api.UtAssembleModel cannot be cast to class org.utbot.framework.plugin.api.UtCompositeModel (org.utbot.framework.plugin.api.UtAssembleModel and
        org.utbot.framework.plugin.api.UtCompositeModel are in unnamed module of loader 'app') */
```

2023-02-27 13:42 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
> +        val mockedModelsVariables: MutableMap<List<UtModel>, CgValue> = mutableMapOf()
We should find a better way than a companion, but it does not seem obvious. Need to discuss.

2023-02-27 13:47 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val groupedInjectedModelsByClassId = testClassModel.injectedMockModels.groupBy { it.classId }
I think we should do this `groupBy` in a place where we prepare `SpringTestClassModel`. 
And store `Map<ClassId, List<UtModel>> in it is this structure is actually required here.

Similarly for `groupedMockedModelsByClassId`.

2023-02-27 13:54 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val declaration =
```java
val declaration = CgDeclaration(classId, name, initializer = null)
```

2023-02-27 14:12 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +        isMock: Boolean
It seems to be a reduntant parameter. It should be possible to take an information, should we mock or not, from `groupedModelsByClassId`.

2023-02-27 14:39 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +        groupedModelsByClassId: Map<ClassId, List<UtModel>>,
Seems that just one UtModel will be enough here

2023-02-28 15:32 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +        groupedModelsByClassId: Map<ClassId, List<UtModel>>,
No.
Later, we do the following:
https://github.com/UnitTestBot/UTBotJava/blob/f213dded608dee0e8009908cb9d3d6dec8cbb165/utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt#L110

2023-02-28 16:13 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/TestClassModel.kt
> +    val injectedMockModels: List<UtModel> = listOf(),
It's Map<ClassId, List<UtModel>> now. I guess, it's not relevant.

2023-02-28 16:13 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +                execution.stateBefore.thisInstance?.let { allModelsInExecution += it; thisInstances += it }
Done.

2023-02-28 16:13 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +            .filter { it != classUnderTest }
Done.

2023-02-28 16:14 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt
> +        }
Done.

2023-02-28 16:14 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val groupedInjectedModelsByClassId = testClassModel.injectedMockModels.groupBy { it.classId }
Ok.

2023-02-28 16:15 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val declaration =
Done.

2023-02-28 16:15 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +        isMock: Boolean
Removed.

2023-02-28 16:16 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val createdValue = variableConstructor.getOrCreateVariable(listOfUtModels.first(), name)
There can't be empty list by using **groupBy** method. But added a little check. Just in case.

2023-03-01 10:15 UTC, Damtev requested changes

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val declaration = CgDeclaration(classId, name, null)
Add named arguments to constants, please. And add some comments the `null` argument is used here, please

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val createdValue = variableConstructor.getOrCreateVariable(model, name)
`name` passed here is just a base name - it will be used in the name generator and does not have to be the real name of the created variable

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +                else -> error("Unexpected annotation ClassId")
Please, pass the `annotationClassId` to the error description

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +                else -> error("Unexpected annotation ClassId")
Minor: this condition does not depend on loop body - you can introduce a local function with a required behavior before the loop

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +    private fun constructMockitoCloseables(): Pair<CgFieldDeclaration, CgMethodsCluster> {
Why? These closeables were supposed to be local variables for static mocks in each test method

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
> +    private fun findCgValueByModel(model: UtModel, collection: Map<List<UtModel>, CgValue>): CgValue? =
Actually, `Map` is not a collection

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
> +            .filter { it.key.contains(model) }
`contains` in a `List` requires linear time - consider using `Set` here

2023-03-01 10:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
> +        val injectedMocksModelsVariables: MutableMap<List<UtModel>, CgValue> = mutableMapOf()
Please, do not use such statics - it often leads to unexpected and hard-to-catch errors

2023-03-01 10:15 UTC, Damtev commented on utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/constructor/visitor/CgPythonRenderer.kt
> +    }
Same about override

2023-03-06 14:23 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
> +            val model = listOfUtModels.firstOrNull() ?: return@forEach
**return@forEach** in this case works like **continue** in for-loop.

For example,
```kotlin
val a = listOf(1, 2, 3, 4, 5, 6, 7, 8)
a.forEach { if (it == 3) return@forEach else println(it) }
```
will produce the following output:
```kotlin
1
2
4
5
6
7
8
```

Actually, we do not expect **listOfUtModels** to be empty at all because of previous grouping by class ids. And, **listOfUtModels.first()** looks a little rough, so it was added just in case of unexpected situation.

2023-03-21 16:00 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt
> +            VisibilityModifier.INTERNAL -> print("internal ")
it looks like we can define corresponding literals in this enum and just render it here

2023-03-21 20:06 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt
> +            VisibilityModifier.INTERNAL -> print("internal ")
Unfortunately it seems to be not very good idea because modifiers rendering is language specific. For example `public` in Kotlin will not be rendered at all.

2023-03-22 08:29 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/context/CgContext.kt
> +    var valueByModelId: MutableMap<ModelId, CgValue>
Also, this field should be cleared in the `clearClassScope` method, I guess

2023-03-22 12:10 UTC, Damtev requested changes

2023-03-22 12:59 UTC, Damtev approved these changes

2023-03-22 14:07 UTC, merged

2023-03-23 08:26 UTC, alisevych commented
@sofurihafe @EgorkaKulikov 
Please do not forget to add ctg- and comp labels in future PRs