try to build ultimate plugin each time on pr event #1836
UnitTestBot/UTBotJava pull request #1837
Opened 2023-02-21 12:51 UTC by bissquit

## Description

We need to check if IU plugin is built ok

Fixes #1836

## How to test

### Automated tests

Not applicable

### Manual tests

Check workflow from branch. Temporary change behavior of artifact publishing to be sure it works

## Self-check list

- [ ] check tests from branch
- [ ] test artifacts publishing from branch
- [ ] disable artifact publishing from a branch before merge this pr

2023-02-22 13:39 UTC, victoriafomina requested changes

2023-02-22 13:39 UTC, victoriafomina commented on .github/workflows/publish-plugin-and-cli-from-branch.yml
> +          default: false
It's better to use _true_ as the default value here as we often use this workflow (from branch) to build artifacts in order to test them attach to releases

2023-02-27 06:45 UTC, bissquit commented on .github/workflows/publish-plugin-and-cli-from-branch.yml
> +          default: false
fxd

2023-02-27 12:45 UTC, victoriafomina approved these changes
LGTM

2023-02-28 08:42 UTC, merged