Socket connection in python fuzzing
UnitTestBot/UTBotJava pull request #1844
Opened 2023-02-22 15:57 UTC by tamarinvs19

## Description

Added socket connection between python and kotlin.

Fixes # (issue)

## How to test

### Manual tests

Generate tests for python

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [ ] I've set the proper **labels** for my PR (at least, for category and component).
- [ ] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-02-27 06:50 UTC, Markoutte reviewed
At the moment an exception is thrown, or no tests generated for this example:

```python
def test3(x: str) -> bool:
    if x[0] == 'b':
        if x[1] == 'a':
            if x[2] == 'd':
                if x[3] == '!':
                    raise RuntimeError("Very bad")
    return True
```

2023-02-27 11:04 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
> +//                val outputFile = "/home/vyacheslav/utbot_profile"
Fixed

2023-03-01 07:06 UTC, Markoutte approved these changes

2023-03-02 06:27 UTC, Markoutte requested changes

2023-03-02 06:27 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/fuzzing/PythonApi.kt
> +    val executionFeedback: FuzzingExecutionFeedback?
This feedback is used as a part of equals/hashCode, therefore 2 same paths with different result will be recognized as different feedbacks. Is it intented?

2023-03-02 06:27 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/newtyping/utils/Utils.kt
> +fun <T> weightedRandom(elems: List<T>, weights: List<Double>): T {
You can find similar util method in RandomExtension.kt (in module utbot-fuzzing) with name Random.chooseOne. Also, please not, that random in your case doesn't use seed, therefore, every run will be different, that usually is undesirable.

2023-03-03 04:22 UTC, Markoutte requested changes

2023-03-03 04:22 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/newtyping/utils/Utils.kt
> +    val index = Random.chooseOne(weights.map { it / sum }.toDoubleArray())
The random is still so random. Also, you can pass to the chooseOne just `weights.toDoubleArray`. The method does `sum` itself, so, there's no need to do before.

2023-03-03 04:22 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
> +    private fun addExecutionToCache(key: Pair<PythonMethodDescription, List<PythonTreeWrapper>>, result: PythonExecutionResult) {
I'd recommend extracting the cache into a separate class to facilitate further work with it.

2023-03-03 11:02 UTC, Markoutte approved these changes

2023-03-03 11:39 UTC, merged