Listen that mock occured in forceMock method
UnitTestBot/UTBotJava pull request #1889
Opened 2023-03-03 10:18 UTC by EgorkaKulikov

## Description

Fixes # ([1560](https://github.com/UnitTestBot/UTBotJava/issues/1560))

We need to stop symbolic execution if we called `forceMock` function and `Do not mock` strategy is used.
One of possible scenarios is when there are no implementations of an interface in project. 

## How to test

### Automated tests

Standard `utbot-samples` pipeline as regression checks. Mostly in `mocks` package.

### Manual tests

Scenario from issue.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [x] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-03-06 15:15 UTC, Damtev requested changes
There are some suspicious parts

2023-03-06 15:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                        val mockedObject = mockedObjectInfo.value!!
It's better to make `value` in `MockedObjectInfo` abstract and override with `non-null type in `ExpectedMock` to avoid such non-null assertion calls

2023-03-06 15:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            .mapNotNull { (method, implementationClass, possibleTypes) ->
I do not see any nulls in the body

2023-03-06 15:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                    is UnexpectedMock -> unreachableBranch("If it ever happens, it should be investigated")
That behavior is very unclear. Please, add some comments to clarify.

Also, please change the message

2023-03-07 06:48 UTC, EgorkaKulikov commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/mock/CommonMocksExampleTest.kt
> +            coverage = DoNotCalculate,
Actually, all tests in this file are marked with `DoNotCalculate`, I just added similarly.
I tried to avoid this setting, both newly created and modified tests fail with a message

```
Coverage matcher 'full coverage' fails for (branches: 0/0, instructions: 3/4, lines: 0/0) (at least: 75) ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:46)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:187)
```

2023-03-07 07:16 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> +     * it does not check anything and always returns the constructed mock.
Why?

2023-03-07 07:23 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            val mockedObject = mockedObjectInfo.value ?: error("Mocked value cannot be null after force mock")
No... objectValue is never null in `forceMock` method

2023-03-07 08:03 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            val mockedObject = mockedObjectInfo.value ?: error("Mocked value cannot be null after force mock")
Anyway, I've rewritten this place

2023-03-07 08:03 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                    is UnexpectedMock -> unreachableBranch("If it ever happens, it should be investigated")
I will discuss with Alexey

2023-03-07 13:57 UTC, Damtev commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/mock/CommonMocksExampleTest.kt
> +            coverage = DoNotCalculate,
Well, in such cases we can use `AtLeast(75)`

2023-03-07 15:52 UTC, CaelmBleidd requested changes

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> + * A wrapper for [ObjectValue] to store additional onfo.
Typo? `info`

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> + * or when an object type is in a set that requires force mocking.
Please, add a link using `[]` to this set

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> + * Represents a mock that occurs when it is not recommended
I think, `not recommended` is not exactly the condition. Probably, `when it is not allowed` would be better, since it is strictly prohibited to generate mocks in such cases

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> + * mock startegy is DO_NOT_MOCK and class is not in mockAlways set.
Use `[]` to add a link to the set and to the `DO_NOT_MOCK`, please

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> +    fun construct(value: ObjectValue?, mockInfo: UtMockInfo): MockedObjectInfo {
Shouldn't it be a private function? What is a case of usage it from outside?

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> +        if (value == null) {
I guess, if you name it as `mockedValue`, it will be easier to understand

2023-03-07 15:52 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                is NoMock -> error("Value must be mocked after the fore mock")
Typo, `force`

2023-03-07 15:53 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Mocks.kt
> +     * it does not check anything and always returns the constructed mock.
Added a proposition about possible documentation. Information about checks is still correct because added checks are not about the need to mock, but about whether they are expected or not

2023-03-07 16:07 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                    is UnexpectedMock -> unreachableBranch("If it ever happens, it should be investigated")
If it is unclear, you can provide a comment. Something like: 


Currently, it is unclear how this could happen. Perhaps, the answer is somewhere in the following situation: you have an interface with an abstract method `foo`, and it has an abstract inheritor with the implementation of the method, but this inheritor doesn't have any concrete inheritors. It looks like in this case we would mock this instance (because it doesn't have any possible concrete type), but it is impossible since either this class cannot present in possible types of the object on which we call `foo` (since they contain only concrete types), or this class would be already mocked (since it doesn't contain any concrete implementors).


Something like this. But tbh I think it can be just replaced with `-> TODO("If it ever happens, it should be investigated")`

2023-03-10 07:21 UTC, CaelmBleidd approved these changes
LGTM

2023-03-13 08:10 UTC, Damtev approved these changes

2023-03-13 08:13 UTC, merged