Update time management of python test generation
UnitTestBot/UTBotJava pull request #1893
Opened 2023-03-03 20:43 UTC by tamarinvs19

## Description

New test generation strategy is:
* If function is fully annotated and type inference algorithm cannot infer type we use all time from UI-settings to fuzzing and test generation; 
* If type inference and infer type we try to fuzz tests for one annotation with the following restrictions:
    - max 150 successfully executable tests (with or without exeception)
    - max 10 invalid tests (when we generate incorrect arguments and have `TypeError` or `AttributeError`; or we cannot generate any valid representative of the inferred type)
    - and 5 additional tests (as a precaution)
    - until time limit

In future we can modify strategies and add it to UI. For example, wait max coverage.

Fixes #1831

## How to test

### Manual tests

#### Fully annotated function
For example,
```python
def div(a: int, b: int) :
    return a / b
```
__Expected__: two tests (valid and with `ZeroDivisionError`), test generation process lasted all time from UI-settings

Or,
```python
def str_test(x: str):
    if x[0] == 'b':
        if x[1] == 'a':
            if x[2] == 'd':
                return 'Very bad!'
```
__Expected__: all time generation, one test with `x = 'ba'` or longer (with timeout 60s) and all covered branches with timeout 180s

#### Without or partially annotated function
For example,
```python
def str_test(x):
    if x[0] == 'b':
        if x[1] == 'a':
            if x[2] == 'd':
                return 'Very bad!'
```
__Expected__: all time generation, one test with `x = 'b'`, no one with `'ba'` and longer (__regardless of timeout in UI__)

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-03-06 11:52 UTC, tochilinak commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>              if (existsAnnotation.arguments.all { it.pythonTypeName() != "typing.Any" }) {
Seems like this is wrong. Example:
```python
def f(x: list): pass
```

In this case we need type inference for intermal type.

We can get information about whether function signature has Any's inside type inference algorithm. In that case initial state has no Any nodes, and the main loop makes only one iteration (initial state -> no new states -> finish).

2023-03-06 11:54 UTC, tochilinak requested changes
Problem with setting `limitManager.mode = TimeoutMode`.

2023-03-06 12:46 UTC, tamarinvs19 commented
> Problem with setting `limitManager.mode = TimeoutMode`.

Fixed

2023-03-06 13:03 UTC, tochilinak commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>                  annotationHandler(existsAnnotation)
Initially this code was needed to run fuzzing with initial types (even when those are not full). Will we run fuzzing with `list[Any]` for the following function?
```python
def f(x: list): ...
```

2023-03-06 13:37 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>                  annotationHandler(existsAnnotation)
Maybe. But only if all arguments have not-`typing.Any` annotations. And if all annotations are full we run fuzzing twice

2023-03-06 13:44 UTC, tochilinak commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>                  annotationHandler(existsAnnotation)
Are you sure? Type inference does not run annotationHandler on initial signature.

2023-03-06 13:54 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>                  annotationHandler(existsAnnotation)
Now I run fuzzing with initial annotations only after type inference) But I can change program and run fuzzing twice with initial annotations, but I think it isn't a good solution

2023-03-06 15:28 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
>                  annotationHandler(existsAnnotation)
I added handling of an initial annotation after first expansion in BaselineAlgorithm. 
- if annotation is full we cannot expand it and stop type inference and then start fuzzing;
- if annotation is not full we try to expand and first of all try to fuzz initial annotation (for example, if it is `list[typing.Any]` we can generate empty list), after that we continue type inference

2023-03-06 15:41 UTC, tochilinak approved these changes

2023-03-07 05:24 UTC, Markoutte requested changes

2023-03-07 05:24 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
> +                return@flow
Should be logged somehow

2023-03-07 05:24 UTC, Markoutte commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
>                                  .zip(methodUnderTest.arguments)
On line 215 (sorry, that I comment another line, because I was not able to find how to comment 215) there's no check that:

```
is ValidExecution -> {
  val trieNode: Trie.Node<Instruction> = description.tracer.add(coveredInstructions)
```

Returns the node the was already found. You can check `trieNode.count > 1` to ignore duplicates and minimise the count of tests for user. At the moment similar tests are generated with different arguments, but same trace.

2023-03-08 05:31 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
> +                return@flow
Logging was already there but one level higher. I moved it here

2023-03-08 05:35 UTC, tamarinvs19 commented on utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
>                                  .zip(methodUnderTest.arguments)
Fixed

2023-03-09 06:05 UTC, Markoutte approved these changes

2023-03-09 06:59 UTC, merged