Rider plugin fixes
UnitTestBot/UTBotJava pull request #1894
Opened 2023-03-05 18:13 UTC by mxprshn

- Add test generation timeout option 
- Add balloon notifications
- Improve .NET versions check
- Pass multiple methods to V# API simultaneously
- Support types with overloaded methods

2023-03-07 08:46 UTC, MchKosticyn approved these changes

2023-03-13 17:30 UTC, Domonion requested changes
we need to discuss

2023-03-13 17:30 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/ProjectPublisher.cs
> +[ShellComponent]
why shell component?

2023-03-13 17:30 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/ProjectPublisher.cs
> +    public void PublishSync(IProject project, IProjectConfiguration config, VirtualFileSystemPath outputDir)
better make it `[ProjectComponent]` and receive project from constructor

2023-03-13 17:30 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/Notifications.cs
> +    public void Refresh() => _lifetime = _sequentialLifetimes.Next();
what is this for?

2023-03-13 17:30 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/DotNetVersionUtils.cs
> +internal class DotNetVersionUtils
Why internal class is SolutionComponent?

2023-03-13 17:30 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/DotNetVersionUtils.cs
> +    private readonly ConcurrentDictionary<string, TestProjectTargetFramework> _testProjectsFrameworksCache = new();
to discuss - I believe we should not manually maintain cache as we do not track any refactorings and after some time of work this cache might grow indefinitely.

2023-03-14 11:45 UTC, mxprshn commented on utbot-rider/src/dotnet/UtBot/UtBot/UnitTestBuilder.cs
> +        progressIndicator.Header.SetValue($"Building {project.Name}...");
Change method to indicate that 
1. you are doing publish
2. you are publishing for gathering dependencies
3. you are publishing to custom dir

2023-03-14 13:49 UTC, mxprshn commented on utbot-rider/src/dotnet/UtBot/UtBot/UnitTestBuilder.cs
> +        progressIndicator.Header.SetValue($"Building {project.Name}...");
Tried this, rider can't show long strings properly in progress bars

2023-03-15 11:35 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/UnitTestBuilder.cs
> +        progressIndicator.Header.SetValue($"Building {project.Name}...");
make message shorter

2023-03-15 11:35 UTC, Domonion commented on utbot-rider/src/dotnet/UtBot/UtBot/Utils/ProjectPublisher.cs
> +[ShellComponent]
remove all shell components please

2023-03-15 11:37 UTC, mxprshn commented on utbot-rider/src/dotnet/UtBot/UtBot/UnitTestBuilder.cs
> +        progressIndicator.Header.SetValue($"Building {project.Name}...");
Already done. This screenshot is outdated

2023-03-15 12:22 UTC, merged