Сoncrete values for enums
UnitTestBot/UTBotJava pull request #19
Opened 2022-05-24 14:50 UTC by Damtev

Closes https://github.com/UnitTestBot/UTBotJava/issues/18, https://github.com/UnitTestBot/UTBotJava/issues/32

To increase the performance of symbolic analysis for source code that uses enums, we can extract these enums concretely from runtime instead of enum's initializers analysis which can require a lot of time for enums with a lot of constants (because enum's static initializer fills fields for every enum constant, creates `$VALUES` array, invokes `java.lang.Enum` initializer for every constant, etc). 

But very important thing is that we cannot process concretely every enum but only  **isolated** - enums that do not affect the system state (like other classes' statics) in their initializers and do not use external statics to initialize its own statics. To prevent concrete processing of enum that **is not isolated**, we need to traverse its static initializer and check that it does not initialize external statics and does not use external statics to initialize its own statics.

2022-05-25 15:13 UTC, CaelmBleidd requested changes
Add a design doc for concrete processing of enum's clinit sections

2022-05-25 15:13 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/statics/concrete/EnumConcreteUtils.kt
> +    return activeBody.units.any {
Above you checked that you could retrieve a body, but didn't do it. You might do not have this body here yet

2022-05-25 15:13 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/statics/concrete/EnumConcreteUtils.kt
> +                val declaringClass = leftOp.fieldRef.declaringClass()
Same about declaringClass

2022-05-26 08:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt
> +    existingEnumSymbolicValue: Any?,
This method is quite properly documented in its body, so I just fixed the wrong parameter's name

2022-05-26 08:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            val declaringClass = fieldRef.fieldRef.declaringClass()
Fixed

2022-05-26 08:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +                LocalVariable(local.name) to curFieldSymbolicValueForLocalVariable
Fixed

2022-05-26 08:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/statics/concrete/EnumConcreteUtils.kt
> +    return activeBody.units.any {
Changed to jimpleBody

2022-05-26 08:06 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/statics/concrete/EnumConcreteUtils.kt
> +                val declaringClass = leftOp.fieldRef.declaringClass()
Fixed

2022-05-26 08:30 UTC, CaelmBleidd approved these changes

2022-05-29 18:32 UTC, merged