Remove old fuzzer dependencies from JavaScript module
UnitTestBot/UTBotJava pull request #1900
Opened 2023-03-06 12:29 UTC by rudolf101

## Description

Now `utbot-js` module depends on `utbot-fuzzing` and do not contain any imports from `org.utbot.fuzzer`

Fixes #1792 

## How to test

### Manual tests

Various scenarios have been tested. You can find the examples in the folder `/utbot-js/samples' and try to run UTBot.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-03-07 04:39 UTC, Markoutte requested changes

2023-03-07 04:39 UTC, Markoutte commented on utbot-js/src/main/kotlin/fuzzer/JsFuzzerApi.kt
> +data class JsFuzzedValue(
Look like JsFuzzedValue is not really needed by the code, because the filed `summary` is never read and used. Only the `model` is required by the further code as I can see.

2023-03-07 04:39 UTC, Markoutte commented on utbot-js/src/main/kotlin/fuzzer/JsFuzzerApi.kt
> +fun UtModel.fuzzed(block: JsFuzzedValue.() -> Unit = {}): JsFuzzedValue = JsFuzzedValue(this).apply(block)
Taking into account the previous comment you can remove this because UtModel can be used directly by the js codegen.

2023-03-07 04:39 UTC, Markoutte commented on utbot-js/src/main/kotlin/fuzzer/providers/ObjectValueProvider.kt
> +                val id = JsIdProvider.get()
`createId` is clearer than `get`. When calling method with name `get` usually everyone would expect that it returns same value for every call.

2023-03-07 05:14 UTC, Markoutte commented on utbot-js/src/main/kotlin/fuzzer/JsFuzzerApi.kt
>          val castOther = other as? JsFeedback
This equals/hashCode is not good for fuzzing, because it groups result only by status, but doesn't use JsStatement. Please, look at java and pythod feedbacks. They look like this:

```
data class PythonFeedback(
    override val control: Control = Control.CONTINUE,
    val result: Trie.Node<Instruction> = Trie.emptyNode(),
) : Feedback<Type, PythonFuzzedValue>
```

2023-03-07 14:47 UTC, rudolf101 commented on utbot-js/src/main/kotlin/fuzzer/JsFuzzerApi.kt
> +data class JsFuzzedValue(
Removed JsFuzzedValue

2023-03-07 14:48 UTC, rudolf101 commented on utbot-js/src/main/kotlin/fuzzer/JsFuzzerApi.kt
>          val castOther = other as? JsFeedback
Fixed

2023-03-09 04:21 UTC, Markoutte approved these changes

2023-03-09 04:21 UTC, merged