Wrapper for basic Stream
UnitTestBot/UTBotJava pull request #194
Opened 2022-06-09 15:18 UTC by Damtev

# Description

Added wrapper `UtStream` based on `RangeModifiableUnlimitedArray` for `java.util.streams.Stream` with all its methods implemented (as easy for the symbolic analysis as possible). Added `UtClassMock` for static methods of `java.util.streams.Stream` (`of`, `empty`, `generate`, `iterate`, and `concat`) - with using `UtStream` wrapper for finite streams and concrete execution for infinite streams (from `generate`, `iterate`, and `concat`).

Closes #145.

## Type of Change

New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

See `org.utbot.examples.stream.BaseStreamExampleTest`

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

2022-06-14 13:57 UTC, CaelmBleidd requested changes
Overall, LGTM, but there are several questions

2022-06-14 13:57 UTC, CaelmBleidd commented on utbot-sample/src/main/java/org/utbot/examples/stream/BaseStreamExample.java
> +        return list
This test doesn't check anything since a stream with one null element will go through it, but it will be removed from a first filter operation

2022-06-14 13:57 UTC, CaelmBleidd commented on utbot-framework/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +            val x = statics[statics.keys.single()]!!.value as Int
`statics.values.single().value as Int`

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/pc/Z3TranslatorVisitor.kt
> +            val numDimensionsConstraint = z3Context.mkAnd(
Removed

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +     * <li> elementData.size in 0..MAXIMUM_LIST_SIZE. </li>
Fixed

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +        return this;
Fixed

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +    public Iterator<E> iterator() {
Fixed

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +    @Disabled("TODO too long, improve performance")
Used

2022-06-21 11:25 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +            coverage = DoNotCalculate
Fixed

2022-06-21 11:26 UTC, Damtev commented on utbot-sample/src/main/java/org/utbot/examples/stream/BaseStreamExample.java
> +        return list
Removed this test

2022-06-21 11:26 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +            val x = statics[statics.keys.single()]!!.value as Int
Fixed

2022-06-21 13:50 UTC, CaelmBleidd requested changes

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +                    if (!matchingLengthExpr.isConcrete) return null
Can you remove redundant nulls at the ends of the blocks and replace returns from the blocks with `return@with`?

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +            .filterNot { (baseType, numDimensions) -> numDimensions == 0 && baseType is RefType && baseType.sootClass.isInappropriate }
I think we should have here arrays of interfaces and abstract classes, but not classes with UtMock annotations

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/pc/Z3TranslatorVisitor.kt
> +            z3Context.mkAnd(*constraints.toTypedArray())
This line doesn't do anything

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/pc/Z3TranslatorVisitor.kt
> +        val typeConstraint = z3Context.mkOr(
I think it is better to make `mkOr(mkAnd(dimensions, type), canBeNull)`, otherwise we might get unsat with nulls with different num dimensions

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/UtilMethods.kt
> +            CodegenLanguage.JAVA -> listOf(java.util.stream.Stream::class.id, java.util.stream.Stream::class.id, Set::class.id)
`java.util.stream.Stream::class.id` occurs twice

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +import java.util.*;
Asterisk

2022-06-21 13:50 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +        assume(elementData.end <= HARD_MAX_ARRAY_SIZE);
Please, use `assumeOrExecuteConcretely`

2022-06-21 15:04 UTC, CaelmBleidd approved these changes

2022-06-21 19:06 UTC, merged