Update UnitTestBot Python, JavaScript, Go docs
UnitTestBot/UTBotJava pull request #1989
Opened 2023-03-20 14:11 UTC by olganaumenko

## Description

Linguistic bugs fixed, document structure optimized.
Added note: "be sure to enable _Experimental languages support_ option for **_each_** project".

## How to test

The PR introduces no code changes.
Manual scenario: the text itself has been previewed in the IntelliJ IDEA viewer.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-03-20 14:20 UTC, rudolf101 commented on docs/JavaScriptSupport.md
> +# UnitTestBot JavaScript
How about moving this file to utbot-js and renaming it to README, as is done with the Go and Python modules?

2023-03-21 08:25 UTC, tochilinak commented on utbot-python/README.md
> +1. Python 3.8 or 3.9 (UnitTestBot Python has been tested to provide support for these versions; some Python 3.10 syntax is not supported)
Now we support Python 3.8+.

2023-03-21 08:26 UTC, alisevych commented on docs/JavaScriptSupport.md
> +# UnitTestBot JavaScript
Probably moving Go- and Py- docs into /docs?

2023-03-21 08:27 UTC, tochilinak commented on utbot-python/README.md
> +1. Download the corresponding [archive](https://github.com/UnitTestBot/UTBotJava/actions/runs/2956160534).
This instruction is outdated. Now UTBot Python is included in UTBot Java plugin.

2023-03-21 08:33 UTC, rudolf101 commented on docs/JavaScriptSupport.md
> +# UnitTestBot JavaScript
Both scenarios LGTM

2023-03-21 09:15 UTC, egiptipavel approved these changes

2023-03-21 09:15 UTC, egiptipavel commented on utbot-go/README.md
>  * GCC as well as `github.com/stretchr/testify/assert` and `golang.org/x/tools@v0.4.0` Go modules installed
`golang.org/x/tools@v0.4.0` is not required

2023-03-23 10:22 UTC, rudolf101 approved these changes

2023-03-23 17:55 UTC, tochilinak commented on docs/PythonSupport.md
> +3. IntelliJ IDEA 2022.1
Now this line is not needed

2023-03-24 13:46 UTC, alisevych requested changes
LGTM, just minor corrections are possible.

2023-03-24 13:46 UTC, alisevych commented on docs/PythonSupport.md
> +4. To generate tests, place the caret at the required function and press **Alt+Shift+U** (**Alt+U, Alt+T** in Ubuntu).
"in Ubuntu" -> better "in Linux", because there can be different distributives.

2023-03-24 13:57 UTC, rudolf101 commented on docs/JavaScriptSupport.md
> +* _nyc_ 15.1.0 or later: `> npm install -g nyc`
This is true, some npm packages are installed locally in each JS project, so an internet connection will be required at the first launch.

This only applies to npm packages.

2023-03-24 14:19 UTC, tamarinvs19 commented on docs/PythonSupport.md
> +4. To generate tests, place the caret at the required function and press **Alt+Shift+U** (**Alt+U, Alt+T** in Ubuntu).
"in Linux" is too general restriction. The real problem is that keyboard shortcut `Alt+Shift` can be assigned to switch language and it blocks combination `Alt+Shift+U` but not all Linux users use `Alt+Shift` (e.g. me).

2023-03-24 14:33 UTC, tochilinak commented on docs/PythonSupport.md
> +4. To generate tests, place the caret at the required function and press **Alt+Shift+U** (**Alt+U, Alt+T** in Ubuntu).
I think it it better to just write "or Alt+U, Alt+T". It works on Windows as well.

2023-03-27 15:15 UTC, alisevych approved these changes

2023-03-27 15:20 UTC, merged