Avoid false NPE tests for Spring classes
UnitTestBot/UTBotJava pull request #2052
Opened 2023-03-27 14:55 UTC by EgorkaKulikov

## Description

Fixes # ([2034](https://github.com/UnitTestBot/UTBotJava/issues/2034))

This PR enlarges the speculative not null concept to Spring applications

## How to test

### Manual tests

Check that there are no tests with the message "this test fails ..." that are actually passing in Spring applications.

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-03-27 15:19 UTC, Damtev requested changes

2023-03-27 15:19 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (springInjectedClassesStorage.isEmpty()) {
Also, there is a possible performance problem - for example, there are a lot of `beanQualifiedNames` **but** all of them are filtered out, so this condition is always true, and we will never use the `springInjectedClassesStorage` field. I'm not sure whether it can be fixed or not, need to think a bit.

2023-03-27 15:19 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    private var springInjectedClassesStorage = mutableSetOf<ClassId>()
Why is it a `var`? Also, this field requires some docs

2023-03-27 15:19 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +
Why?

2023-03-27 16:03 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (springInjectedClassesStorage.isEmpty()) {
Actually no, I think. In case of inverted condition we are to use two return statements instead of one.

2023-03-27 16:07 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +@Suppress("KDocUnresolvedReference")
I have just copied it from Dima and this suppressing is really required. Or we are to bad in Kotlin to create these docs without warnings...

2023-03-27 16:09 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (springInjectedClassesStorage.isEmpty()) {
I see the problem, but don't see a good solution. Going to think about it tomorrow a little more.

2023-03-28 07:12 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (springInjectedClassesStorage.isEmpty()) {
Actually, it seems a little bit impossible for me not to have at least one not filtered type here in real application context. However, I have applied a potential fix.

2023-03-28 10:31 UTC, Damtev requested changes

2023-03-28 10:31 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +                springInjectedClassesStorage += objectClassId
It seems a bit dangerous and very hard to debug. Consider using an additional flag to check whether `springInjectedClassesStorage` was initialized or not

2023-03-28 10:31 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    private val springInjectedClassesStorage = mutableSetOf<ClassId>()
Please, add some comments that we have an unresolved problem with classloaders when using `lazy`

2023-03-28 13:19 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (springInjectedClassesStorage.isEmpty()) {
Replaced with flags

2023-03-28 13:24 UTC, Damtev approved these changes

2023-03-28 13:24 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +            if (!areInjectedClassesInitialized && springInjectedClassesStorage.isEmpty()) {
I don't really think that we need the second condition anymore

2023-03-28 13:57 UTC, merged