Add SpringAnalyzerProcess with RD
UnitTestBot/UTBotJava pull request #2085
Opened 2023-03-31 18:35 UTC by IlyaMuravjov

## Description

- Add `SpringAnalyzerProcess` using RD and corresponding run configurations for debugging
- Extract common code from `SpringAnalyzerProcess` and `EngineProcess` to `AbstractProcess`
- Add `utbot-spring-analyzer` shadow jar to `utbot-intellij` resources
- Create new `utbot-spring-analyzer-model` project that both `utbot-spring-analyzer` and `utbot-intellij` depend on, since we don't want `utbot-intellij` to have `utbot-spring-analyzer` in dependencies (other than having its shadow jar in resources) due to depending on a Spring application directly being problematic (`utbot-spring-analyzer` is in actuallity a Spring application)
- Add multiple path classpath support to `utbot-spring-analyzer`

Currently, call to `utbot-spring-analyzer` is disabled with `useSpringAnalyzer` flag in `GenerateTestsModel` since `utbot-spring-analyzer` API is expected to get changed soon, in particular, instead of receiving `.properties` and `.xml` file paths it should receive project path and infer these paths on its own. As of now, empty lists are passed.

Markdown docs are to be updated once the implementation is agreed upon.

## How to test

Should not be tested standalone, just as a part of Spring support 1st phase.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-04-03 20:06 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/SpringAnalyzerProcess.kt
> +package org.utbot.framework.process
We may want to move it somewhere else, but I wasn't able to find a better place for it, since we can't put it in a `spring-analyzer` module because of the reason specified in a PR description. One alternative is to create additional `spring-analyzer-starter` module.

2023-04-04 16:01 UTC, Domonion commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/SpringAnalyzerProcess.kt
> +            FileUtils.copyURLToFile(
1. you will always copy this file when you run this function. Copy it once and recheck if it is outdated
2. I am afraid that if you module is spring app and also references apache io - this jar will be way too big and plugin will weight too much. You need to discuss it with Denis Fokin

2023-04-05 13:33 UTC, IlyaMuravjov commented on utbot-core/src/main/kotlin/org/utbot/common/StandardStreamUtil.kt
> +fun silentlyCloseStandardStreams() {
Done

2023-04-05 13:34 UTC, IlyaMuravjov commented on settings.gradle.kts
> +include("utbot-spring-analyzer-model")
In that case, how do I use the model outside of the `utbot-spring-analyzer` to communicate with it? I can't add `implementation(project(":utbot-spring-analyzer))` to `dependencies` block, because `utbot-spring-analyzer` is a Spring application.

2023-04-05 13:35 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/process/CommonProcessArgs.kt
> +fun obtainCommonProcessCommandLineArgs(
We don't have `AbstractProcess` anymore, since most of it was dedicated to dealing with configuring log4j2, which is no longer needed since `SpringAnalyzerProcess` uses rd logger now. Moved inside `object`.

2023-04-05 13:38 UTC, IlyaMuravjov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/InstrumentedProcessRunner.kt
> +        obtainCommonProcessCommandLineArgs(
This change **is** in `InstrumentedProcessRunner` and `obtainCommonProcessCommandLineArgs` does what removed code above used to do, except it's now one common function that is not reimplemented separately for three processes.

2023-04-05 13:40 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt
> +    var useSpringAnalyzer = false
It may not be me who resolves that issue and leaving pull request open may lead to merge conflicts accumulating. Finally, I do know that this code is working, since I've run it with this flag set to `true` and hardcoded resource (`.properties` and `.xml` files) paths.

2023-04-05 13:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/process/EngineProcess.kt
> +                    ) + obtainProcessSpecificCommandLineArgs(port)
The global one is used not just here, but in two other processes as well. Replaced private functions for obtaining process specific command line args with ones that obtain full command by moving `obtainCommonProcessCommandLineArgs` inside of these functions.

2023-04-05 13:43 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/process/EngineProcess.kt
> +        assertReadAccessNotAllowed()
I do **not** need it, that's why I am checking that I do **not** have it the same way every other public method in this class does. If `assertReadAccessNotAllowed()` does something other than checking that we are not holding read lock, then I got confused by naming and usages and this line needs to be removed.

2023-04-05 14:06 UTC, IlyaMuravjov commented on utbot-rd/build.gradle
> +    def springAnalyzerModelProjectDir = project.rootProject.childProjects["utbot-spring-analyzer-model"].projectDir
There's no such folder. I've described in earlier comments and in PR description why `spring-analyzer-model` is needed. As an alternative I can put Spring analyzer model in `UTBotJava/utbot-rd/src/main/kotlin/org/utbot/rd/generated/`.

2023-04-05 14:08 UTC, IlyaMuravjov commented on utbot-rd/src/main/kotlin/org/utbot/rd/loggers/UtRdLogUtil.kt
> +fun setupRdLogger(rdProcess: ProcessWithRdServer, loggerModel: LoggerModel, rdLogger: UtRdKLogger) {
Done, though I missed why extracting common logic to function is a bad decision. Do you mean that when more types of processes get introduced, they may need a different logging setup?

2023-04-05 14:08 UTC, IlyaMuravjov commented on utbot-rd/src/main/kotlin/org/utbot/rd/loggers/RDApacheCommonsLogFactory.kt
> +class RDApacheCommonsLogFactory : LogFactoryImpl() {
Moved to `spring-analyzer`.

2023-04-05 14:13 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/SpringAnalyzerProcess.kt
> +            FileUtils.copyURLToFile(
1. Done.
2. It's around 28 MB now and it's going to get smaller since we are planning to put user's Spring on the classpath instead of having it in our jar.

2023-04-07 15:26 UTC, Domonion requested changes

2023-04-07 15:26 UTC, Domonion commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/process/AbstractRDProcessCompanion.kt
> +    JdkInfoService.provide().path.resolve("bin${File.separatorChar}${osSpecificJavaExecutable()}")
make it getter function in `ProcessCompation`

2023-04-07 15:26 UTC, Domonion commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/process/EngineProcess.kt
> +            this.javaClass.classLoader.getResourceAsStream("log4j2.xml")?.use { logConfig ->
make it private function in this file

2023-04-07 15:26 UTC, Domonion commented on utbot-rd/src/main/kotlin/org/utbot/rd/StandardStreamUtil.kt
> +    fun silentlyCloseStandardStreams() {
move it to ClientProtocolBuilder class

2023-04-07 15:26 UTC, Domonion commented on utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
> +private val jarFile = Files.createDirectories(utBotTempDirectory.toFile().resolve("spring-analyzer").toPath())
name it `springAnalyzerJarFile`

2023-04-07 15:26 UTC, Domonion commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/InstrumentedProcess.kt
> +        } ?: error("""
refactor please to separate functions instead of runs

2023-04-07 16:01 UTC, Domonion approved these changes

2023-04-10 07:34 UTC, merged