Improved communication contracts in utbot-spring-analyzer
UnitTestBot/UTBotJava pull request #2164
Opened 2023-04-19 10:01 UTC by sofurihafe

## Description

This PR improves communication in utbot-spring-analyzer by getting rid of unused arguments and changing types.

Fixes #2160

## How to test

### Automated tests

### Manual tests

Not relevant.

2023-04-19 14:09 UTC, EgorkaKulikov commented
Failing CI shows that manual tests are nevertheless relevant...

2023-04-21 07:52 UTC, IlyaMuravjov requested changes

2023-04-21 07:52 UTC, IlyaMuravjov commented on utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
>                      )
We still want to continue using `classpathItems` here, so `spring-analyzer` process is started with user's classpath. Meaning that we want to pass user's classpath all the way up to here via `UtTestsDialogProcessor` -> `EngineProcess` -`EngineProcessModel` -> `EngineProcessMain`, but we don't want it to go any further via `SpringAnalyzerProcess` -> `SpringAnalyzerProcessModel` -> `SpringAnalyzerProcessMain`.

Since this pull request is only changing contracts, it should not change the behavior, so you can't change command line arguments that are used to start the process.

2023-04-21 15:35 UTC, EgorkaKulikov commented
Replaced with https://github.com/UnitTestBot/UTBotJava/pull/2174

2023-04-21 15:35 UTC, closed without merging