Automatically install Spring test dependencies into user project if required
UnitTestBot/UTBotJava pull request #2197
Opened 2023-05-09 18:28 UTC by EgorkaKulikov

## Description

Supported an auto-installation of Spring or Spring Boot testing dependencies into user projects

Also:
- Added a setting to choose unit or integration testing
- "Framework will be installed" message is shown
- This setting is stored in State
- `LibraryMatcher` class refactored

## How to test

### Manual tests

- Pure Spring project, no test dependency => it is installed with the same version as in project
- Pure Spring project, test dependency is present => no more dependencies installed
- Same two scenarios for Spring Boot projects

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-05-09 21:42 UTC, IlyaMuravjov requested changes

2023-05-09 21:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/ExternalLibraryDescriptors.kt
> +    ExternalLibraryDescriptor("org.springframework", "spring-test", "2.4.0", null, versionInProject ?: "6.0.8")
spring-test 2.4.0 doesn't really make sense here given the minimal version [mvnrepository is aware of is 2.5](https://mvnrepository.com/artifact/org.springframework/spring-test). I think `null` would be more self descriptive until we decide which minimal version we require.

2023-05-09 21:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +                                "while integration tests autowire beans."
I would work a bit more on the wording here, my initial suggestion is: "Unit tests do not  initialize `ApplicationContext` and not autowire beans, while integration tests do."

2023-05-09 21:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            }
```suggestion
            configureSpringTestDependency(when {
                SpringBoot.isInstalled -> SpringBoot
                SpringBeans.isInstalled -> SpringBeans
                else -> else -> error("Unsupported DI framework type $framework")
            })
```

2023-05-09 21:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            addDependency(model.testModule, libraryDescriptor)
`addDependency` returns `Promise<Void>`, here it's ignored, but we want the dependency to finish getting added at some point before `findPaths` gets called in `UtTestsDialogProcessor`.

2023-05-10 08:22 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +                                "while integration tests autowire beans."
Seems `... and DO not autowire ...`, fixed

2023-05-10 08:22 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            }
This fragment does not compile, but I created smth similar, thanks

2023-05-10 08:24 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/ExternalLibraryDescriptors.kt
> +    ExternalLibraryDescriptor("org.springframework", "spring-test", "2.4.0", null, versionInProject ?: "6.0.8")
I set version 2.5 as minimal. There are many bugs in Intellij dependency installation api, so we should better avoid testing what happens if we pass null as minimal version here ihmo.

2023-05-10 08:25 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            addDependency(model.testModule, libraryDescriptor)
Tried to fix using `blockingGet`, implemented it similar to the examples found in ide internals.

2023-05-11 15:38 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            }
If I am not mistaken this runs on the UI thread, so I advise moving blocking call elsewhere. For example, we may add `preCompilePromises: List<Promise<*>>` to `GenerateTestsModel`, save the promise in that list, and in `UtTestsDialogProcessor` replace `compile(...)`  with `preCompilePromises.all().thenAsync { compile(...) }`.

2023-05-11 23:30 UTC, EgorkaKulikov commented
Still does not work correctly

2023-05-12 07:42 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                val compilationPromise = compile(project, filesToCompile, springConfigClass)
Using fluent promise API can help avoid additional layer of nesting here
```suggestion
        val promise = model.preCompilePromises.all().thenAsync {
            compile(project, filesToCompile, springConfigClass)
        }
```

2023-05-12 12:03 UTC, IlyaMuravjov approved these changes

2023-05-15 06:58 UTC, merged