Introduce Spring integration tests
UnitTestBot/UTBotJava pull request #2205
Opened 2023-05-15 09:35 UTC by IlyaMuravjov

## Description

Introduce Spring integration tests that start `SpringApplication` and autowire tested class instance.

## How to test

### Manual tests

Generate tests for `spring-boot-testing-main` after putting the following in the `application.yml`.

```yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
```

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-05-22 08:15 UTC, sergeypospelov approved these changes
`utbot-instrumentation` lgtm

2023-05-23 05:07 UTC, Markoutte requested changes

2023-05-23 05:07 UTC, Markoutte commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/InstrumentedProcess.kt
> +private const val UTBOT_INSTRUMENTATION = "utbot-instrumentation-shadow"
Why is this suffix needed?

2023-05-23 05:07 UTC, Markoutte commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
>                                          val rdGenerateResult = process.generate(
Looks like it is time to write here smth like this:

```kotlin
val rdGenerateResult = process.generate(
    conflictTriggers = model.conflictTriggers,
    methods = methods,
    mockStrategyApi = model.mockStrategy,
    chosenClassesToMockAlways = model.chosenClassesToMockAlways,
    timeout = model.timeout,
    generationTimeout = model.timeout,
    isSymbolicEngineEnabled = false,
    isFuzzingEnabled = true,
    fuzzingValue = project.service<Settings>().fuzzingValue,
    searchDirectory = searchDirectory.pathString
)
```

2023-05-23 08:06 UTC, IlyaMuravjov commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzer/FuzzedType.kt
> +    open val usesCustomValueProvider get() = false
Maybe something like `hasCustomCreationMechanism` could be a better name. The alternative is to make `ObjectValueProvider` aware of `AutowiredFuzzed`, but it seems more wrong to me.

2023-05-23 08:07 UTC, IlyaMuravjov commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzing/JavaLanguage.kt
> +    thisInstanceFuzzedTypeWrapper: (FuzzedType) -> FuzzedType = { it },
We can accept an instance of `FuzzedTypeFactory`:
```kotlin
interface FuzzedTypeFactory {
    fun createFuzzedType(type: Type, isThisInstance: Boolean)
}
```
It will have two implementations:

- `PureJvmFuzzedTypeFactory` traverses types recursively and incapsulates everything `cache`-related
- `SpringFuzzedTypeFactory` is a decorator that makes this instance type to be autowired

2023-05-23 08:10 UTC, IlyaMuravjov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/InstrumentedProcess.kt
> +private const val UTBOT_INSTRUMENTATION = "utbot-instrumentation-shadow"
So it's clear that it's a jar with all the dependencies, unlike regular jars that are built with Gradle jar task. Some alternative suffixes are `-all`, `-fat`, `-uber`.

P.S. Same suffixes occur also in `utbot-spring-analyzer-shadow.jar` and `utbot-spring-commons-shadow.jar`.

2023-05-23 08:55 UTC, Markoutte commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzer/FuzzedType.kt
> +    open val usesCustomValueProvider get() = false
The better way I see is to use marker interface to implement, like:

```kotlin
interface CustomValueProvider {
    fun getProvider(): ValueProvider
}
```

`FuzzerType` itself shouldn't implement that interface, but `AutowiredFuzzerType` should.

2023-05-23 08:58 UTC, Markoutte commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzing/JavaLanguage.kt
> +    thisInstanceFuzzedTypeWrapper: (FuzzedType) -> FuzzedType = { it },
I think it is good idea to use factory with decorators in this case 👍

2023-05-23 09:43 UTC, IlyaMuravjov commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzer/FuzzedType.kt
> +    open val usesCustomValueProvider get() = false
Great idea, but I think this interface should be called `CustomJavaValueProviderHolder` with `val` property instead of the getter. In case of `AutowiredFuzzedType`, `javaValueProvider` can be injected into it via constructor by `SpringFuzzedTypeFactory` so we avoid cyclic dependency between `AutowiredFuzzedType` and `AutowiredValueProvider`.

Finally, we can add `DelegatingToCustomJavaValueProvider` to `defaultValueProviders`.

```kotlin
interface CustomJavaValueProviderHolder {
    val javaValueProvider: JavaValueProvider
}

object DelegatingToCustomJavaValueProvider {
    fun accept(type: FuzzedType): Boolean = type is CustomJavaValueProviderHolder

    fun generate(description: FuzzedDescription, type: FuzzedType): Sequence<Seed<FuzzedType, FuzzedValue>> =
        (type as CustomJavaValueProviderHolder).javaValueProvider.generate(description, type)
}
```

There's nothing Java specific about the code above, but if we use generic `ValueProviderHolder<T, R, D : Description<T>>` and `DelegatingToCustomValueProvider<T, R, D : Description<T>>` then unsafe cast to `ValueProviderHolder<T, R, D>` is needed instead of cast to `CustomJavaValueProviderHolder`.

2023-05-29 06:56 UTC, Markoutte reviewed
As we discussed with @EgorkaKulikov we can rebase it into the main, because it doesn't break general fuzzing, but we still need to refactor the Spring part in fuzzing module with @IlyaMuravjov to improve some concepts.

2023-05-29 06:56 UTC, Markoutte approved these changes

2023-06-01 11:02 UTC, EgorkaKulikov approved these changes

2023-06-01 11:23 UTC, merged