Go. Big update
UnitTestBot/UTBotJava pull request #2206
Opened 2023-05-15 10:43 UTC by egiptipavel

## Description

Added support for new types:
* pointers
* channels, interfaces (as function parameters)

Changed test generation template

Added support for methods

Parallel fuzzing

Traces -> coverage

Fixes #2117 

## How to test

### Manual tests

Test on `utbot-go/go-samples/simple/samples.go` and `utbot-go/go-samples/simple/supported_types.go` files.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-05-23 08:06 UTC, Markoutte approved these changes

2023-05-23 08:06 UTC, Markoutte commented on utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt
> +            row("Number of fuzzing processes:") {
Should a user know about this number?

2023-05-23 11:32 UTC, egiptipavel commented on utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt
> +            row("Number of fuzzing processes:") {
I think this is important if he wants to run fuzzing instead of generating tests.

2023-05-25 04:12 UTC, Markoutte requested changes

2023-05-25 04:12 UTC, Markoutte commented on utbot-go/src/main/kotlin/org/utbot/go/util/ProcessExecutionUtil.kt
> +        this["Path"] = goExecutableAbsolutePath.resolve(File.pathSeparator).toString() + (this["Path"] ?: "")
Resolve should resolve a child element of the current path.

2023-06-09 12:49 UTC, Markoutte approved these changes

2023-06-09 18:06 UTC, merged