Divide Spring unit and integration testing in codegen
UnitTestBot/UTBotJava pull request #2230
Opened 2023-05-22 14:08 UTC by EgorkaKulikov

## Description

- Introduce tests type: unit and integration
- Differ codegen process for Spring unit and integration tests

## How to test

### Automated tests

Verify that there are no regressions in unit testing, integration are not yet ready.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [x] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-05-22 14:29 UTC, Damtev requested changes

2023-05-22 14:29 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgAbstractSpringTestClassConstructor.kt
> +    ): Set<CgFieldDeclaration> {
As I see, the class `CgFieldDeclaration` does not have an overridden method `equals`. Perhaps, we need to add it.

2023-05-23 09:31 UTC, Damtev requested changes

2023-05-23 09:31 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    INTEGRATION_Spring_TESTS(
It's a bit unconventional naming. To be honest, I don;t think the `Spring` part is required as it is mentioned in the name of the enum class itself.

2023-05-23 09:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
> +    }
`with(params)` looks useful here

2023-05-23 09:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/generator/CodeGenerator.kt
> +open class CodeGenerator(
Perhaps, rename it to the `PureJvmCodeGenerator`, according to the corresponding `ProjectType`?

2023-05-23 09:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
> +            forceStaticMocking = kryoHelper.readObject(params.forceStaticMocking),
Same

2023-05-23 09:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
> +            paramNames = kryoHelper.readObject(params.paramNames),
It's used twice, better extract to the variable

2023-05-23 10:42 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/generator/CodeGenerator.kt
> +open class CodeGenerator(
Let's do not confuse normal people about Spring :)

2023-05-23 11:47 UTC, Damtev approved these changes

2023-05-23 11:53 UTC, merged