Improve fuzzing for domain specific API
UnitTestBot/UTBotJava pull request #2256
Opened 2023-06-05 06:31 UTC by Markoutte

## Description

Several enhancements and bug fixes are done:

1. Fix `ClassCastException` when collecting constants from Soot.
2. Enable fuzzing for static methods with no parameters.
3. Add an ability to generate very specific values in some specific cases.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-06-05 22:41 UTC, IlyaMuravjov requested changes

2023-06-05 22:41 UTC, IlyaMuravjov commented on utbot-fuzzing/src/main/kotlin/org/utbot/fuzzing/Api.kt
> +        }
It seems unintended that we use `state.cache` here when the `description` is already a fork and is not the original description that was used to populate `state.cache`, but we just happened to not fork `description` one more time during this execution of the `produce` function, so `fork === description`

2023-06-05 22:41 UTC, IlyaMuravjov commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzing/JavaLanguage.kt
> +        if (checkParamIsThis() == true) {
Only forking when `checkParamIsThis(scope) == true` leads to only being able to transition to `scope` such that `checkParamIsThis(scope) == true`, but not backwards. Since `description` is propagated from `thisInstanceParam` to parameters of constructor used to instantiate a value for `thisInstanceParam` and parameters of methods used to mutate it, this causes all these parameters to also be treated as if they were `thisInstance` themselves, that in turn leads to not covering an exception branch of `checkInnerIsNotNull` method in the following class:

```java
public class Outer {
    public static class Inner { }

    private final Inner inner;

    public Outer(Inner inner) {
        this.inner = inner;
    }

    public void checkInnerIsNotNull() {
        if (inner == null)
            throw new RuntimeException("Inner is null");
    }
}
```

But if we fork description every time, how is adding some dynamic flags/properties to `FuzzedType` is any worse? Flag examples: `NullValueProvider.IgnoredTypeFlag`, `ObjectValueProvider.IgnoredTypeFlag`.

Similar (even more complex) extension of Java type system with flags is used by the [Checker Framework](https://checkerframework.org/manual/#writing-annotations) just fine, so adding flags should not break Java fuzzing type system.

2023-06-06 12:20 UTC, Markoutte commented on utbot-java-fuzzing/src/main/kotlin/org/utbot/fuzzing/type/factories/FuzzedTypeFactory.kt
> -}
As it was discussed I'll try to introduce another way for extending types in java fuzzer

2023-06-06 13:54 UTC, IlyaMuravjov requested changes
`org.utbot.fuzzing.ValueProvider$withFallback$1` doesn't override `enrich()` method and hence `SpringBeanValueProvider.enrich()` is never called

2023-06-08 10:58 UTC, Markoutte commented
> `org.utbot.fuzzing.ValueProvider$withFallback$1` doesn't override `enrich()` method and hence `SpringBeanValueProvider.enrich()` is never called

@IlyaMuravjov, could you please, review and mark it resolved if the problem doesn't reproduce anymore and Spring's implementation works as it does before.

2023-06-08 11:12 UTC, Markoutte commented
> The final design of scope sensitive fuzzing looks quite cumbersome. How about we just make fuzzer work with `ScopeSensetiveValueProvider`s instead of simple `ValueProvider`s, while also keeping simple `ValueProvider`s for backward compatibility?

Let's create a new issue to further discussion of this particular problem. Currently, I think that:
1. A user shouldn't know about scopes until the scope is really needed (by design, scope is not needed)
2. ValueProvider have to be stateless. In this example:

```
    override fun generate(description: D, type: T): ((scope: FuzzingScope) -> List<Seed<T, R>>) {
        val cache = mutableMapOf<K, List<Seed<T, R>>>()
        return { scope -> 
            val key = chooseKey(description, type, scope)
            cache.getOrPut(key) { generate(description, type, key).toList() }
        }
    }
```
cache is the state, that can be held indefinitely.

2023-06-08 13:32 UTC, IlyaMuravjov commented
> > The final design of scope sensitive fuzzing looks quite cumbersome. How about we just make fuzzer work with `ScopeSensetiveValueProvider`s instead of simple `ValueProvider`s, while also keeping simple `ValueProvider`s for backward compatibility?
> 
> Let's create a new issue to further discussion of this particular problem. Currently, I think that:
> 
> 1. A user shouldn't know about scopes until the scope is really needed (by design, scope is not needed)
> 2. ValueProvider has to be stateless. In this example:
> 
> ```
>     override fun generate(description: D, type: T): ((scope: FuzzingScope) -> List<Seed<T, R>>) {
>         val cache = mutableMapOf<K, List<Seed<T, R>>>()
>         return { scope -> 
>             val key = chooseKey(description, type, scope)
>             cache.getOrPut(key) { generate(description, type, key).toList() }
>         }
>     }
> ```
> 
> cache is the state, that can be held indefinitely.

1. A user that doesn't need scopes can implement `ValueProvider` instead of `ScopeSensetiveValueProvider`
2. In that example, it's important to clarify that the `ValueProvider` doesn't directly hold a reference to the `cache`. Instead, the `cache` is captured by the function that is returned by the `generate` method. This means that the `cache` will only be retained as long as the returned function is stored by the caller of the `ValueProvider`.

2023-06-08 13:33 UTC, IlyaMuravjov approved these changes
Now Spring related fuzzing works as it did before

2023-06-09 10:05 UTC, Vassiliy-Kudryashov approved these changes

2023-06-09 10:08 UTC, merged