Support direct field accesses in call models
UnitTestBot/UTBotJava pull request #2261
Opened 2023-06-06 08:44 UTC by EgorkaKulikov

## Description

Enlarges a way to construct assemble models.

Previously only executables could be used to modify intilial state. Actually, direct field acessors may be useful too (e.g. for Spring projects).

## How to test

Difficult to test.
Needs to take in mind all cycle of assemble models processing.
May be we should rely on pipeline...

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [x] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-06-06 13:27 UTC, Damtev approved these changes
LGTM

2023-06-06 15:26 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +                        is UtStatementCallModel -> stmt.params.forEach { collectRecursively(it, allModels) }
We probably want to call `collectRecursively` on `params.instance` as well

2023-06-06 16:59 UTC, IlyaMuravjov requested changes

2023-06-06 16:59 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgVariableConstructor.kt
> +            is DirectFieldAccessId -> executable.fieldId.declaringClass
```suggestion
            is DirectFieldAccessId -> executable.fieldId.type
```

2023-06-06 16:59 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/minimization/Minimization.kt
> +        is UtStatementCallModel -> 1 + params.sumOf { it.calculateSize(used) }
I think, here we should also add `instance?.calculateSize(used) ?: 0` in all cases. It won't get accounted multiple times because `calculateSize` returns `0` for models that has already been `used`.

2023-06-06 16:59 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +) : UtStatementCallModel(instance, fieldAccess, emptyList())
`UtReflectiveSetFieldModel` seems a better name, not to be confused with already existing `UtDirectSetFieldModel` that is used, for example, like this:
```kotlin
is UtDirectSetFieldModel -> {
    val instance = declareOrGet(statementModel.instance)
    // fields here are supposed to be accessible, so we assign them directly without any checks
    instance[statementModel.fieldId] `=` declareOrGet(statementModel.fieldModel)
}
```

2023-06-07 09:34 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
> +                        is UtStatementCallModel -> stmt.params.forEach { collectRecursively(it, allModels) }
Do you mean `stmt.instance`? 
But this has already been done in line 121.

2023-06-07 09:41 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +) : UtStatementCallModel(instance, fieldAccess, emptyList())
Your names seems strange. This is getter, not setter model.
To avoid confusion with `UtDirectSetFieldModel, I named it `UtDirectGetFieldModel`

Actually, it is not very reflective as uses `DirectFieldAccessId`, even though it allows the rendering in reflective way.

2023-06-07 09:51 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/minimization/Minimization.kt
> +        is UtStatementCallModel -> 1 + params.sumOf { it.calculateSize(used) }
We should better keep this place "as is" in current PR. If we really want to change smth in minimization, let's do it in Andrey's PR, for example.

2023-06-07 10:22 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +) : UtStatementCallModel(instance, fieldAccess, emptyList())
Why is it using `DirectFieldAccessId` instead of just `FieldId` if it allows rendering in a reflective way?

2023-06-07 10:25 UTC, IlyaMuravjov approved these changes
Checkout new comments before merging

2023-06-07 13:46 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/minimization/Minimization.kt
> +        is UtStatementCallModel -> 1 + params.sumOf { it.calculateSize(used) }
Asked Andrey do not forget about it.

2023-06-07 13:53 UTC, merged