Add specific annotations for Spring integration testing
UnitTestBot/UTBotJava pull request #2281
Opened 2023-06-13 10:19 UTC by EgorkaKulikov

## Description

Adds new annotations for Spring integration testing:
- `@SpringBootTest`
- `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)`

## How to test

Should be tested as a part of full integration testing checks.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-06-13 12:32 UTC, IlyaMuravjov reviewed
It's also desirable to add `@Transactional` and `@AutoConfigureTestDatabase` if they are present on the **test module** class path.

2023-06-22 12:45 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringIntegrationTestClassConstructor.kt
> +            body = constructTestClassBody(testClassModel)
Not now

2023-06-26 15:04 UTC, alisevych commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringIntegrationTestClassConstructor.kt
> +            body = constructTestClassBody(testClassModel)
@IlyaMuravjov Can you please create a task for this enhancement from this comment? That can be done in future.

2023-06-26 18:17 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringIntegrationTestClassConstructor.kt
> +        }
Am I missing something, why isn't it implemented like this?
```suggestion
        currentTestClassContext.collectedTestClassAnnotations += collectSpringSpecificAnnotations()
        return super.constructTestClass()
```

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +    val springBootTestClassId = ClassId("org.springframework.boot.test.context.SpringBootTest")
Is it intended to stay unused in this PR?

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsTestFrameworkManager.kt
> +    override fun collectParameterizedTestAnnotations(dataProviderMethodName: String?) { }
Do parametrized tests really require no additional annotations in JS or are they not supported? In case of the second option, it may be better to implement it here in a way similar to `Junit4Manager` where `error("Parametrized tests are not supported for JUnit4")` is used.

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> + * NOTE: use `CgContext.addAnnotation`
Do you mean `StatementConstructor.addAnnotation`?

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForSpringRunner() { }
I think, for now we can just disable entire test class with appropriate message suggesting user to use JUnit 4 or JUnit 5.

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgMethodConstructor.kt
>              annotations += testFrameworkManager.createDataProviderAnnotations(dataProviderMethodName)
Does that not work as expected here?
```suggestion
            testFrameworkManager.createDataProviderAnnotations(dataProviderMethodName)
            annotations += collectedMethodAnnotations 
```

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgMethodConstructor.kt
>              annotations += testFrameworkManager.createDataProviderAnnotations(dataProviderMethodName)
Also, I think `createDataProviderAnnotations` should be renamed to `addDataProviderAnnotations` since it has a side effect of modifying `collectedMethodAnnotations`.

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringIntegrationTestClassConstructor.kt
> +        if (annotationTypeIsAccessible(bootstrapWithClassId)) {
`@BootstrapWith` annotation is an extension point for `spring-test` (not something `spring-boot-test` specific), so it's a part of `spring-test` itself and should always be accessible here (even without `spring-boot-test` being present).

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringIntegrationTestClassConstructor.kt
> +        if (annotationTypeIsAccessible(bootstrapWithClassId)) {
One way to actually check for presence of `spring-boot-test` is to use `annotationTypeIsAccessible(springBootTestContextBootstrapper)`.

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +    val springBootTestContextBootstrapper = ClassId("org.springframework.boot.test.context.SpringBootTestContextBootstrapper")
```suggestion
    val springBootTestContextBootstrapperClassId = ClassId("org.springframework.boot.test.context.SpringBootTestContextBootstrapper")
```

2023-06-27 20:00 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +        }
`setListeners()` is called after `initDefaultValues()` in `createCenterPanel()`. That makes me suspect that if we start to memorize `springTestsType` between runs that will cause us to not call `updateTestFrameworkList(item)` for memorized value of `springTestsType` from previous run.

2023-06-27 22:39 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/context/CgContext.kt
> +            CodegenLanguage.KOTLIN -> CgGetKotlinClass(id)
I think even when `codegenLanguage` is Kotlin most of the times we still need to generate `CgGetJavaClass`, as far as I can see the only place where we actually need `CgGetKotlinClass` is in annotations.

2023-06-28 06:31 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForSpringRunner() { }
I disabled integration tests with TestNg on UI

2023-06-28 10:58 UTC, sofurihafe commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgStatementConstructor.kt
> +            AnnotationTarget.Field -> error("Such annotations are not supported in JavasCRIPT")
```suggestion
            AnnotationTarget.Field -> error("Such annotations are not supported in JavaScript")
```

2023-06-28 11:00 UTC, sofurihafe commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsTestFrameworkManager.kt
> +        error("Nested classes annotation does not exists in Mocha")
```suggestion
        error("Nested class annotation does not exist in Mocha")
```

2023-06-28 11:00 UTC, sofurihafe commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsTestFrameworkManager.kt
> +        error("Spring runner annotation does not exists in Mocha")
```suggestion
        error("Spring runner annotation does not exist in Mocha")
```

2023-06-28 11:37 UTC, Damtev requested changes
There are a lot of possibly dangerous changes connected with `CgJavaGetClass`. I suggest removing these changes from this PR and moving them to another PR

2023-06-28 11:37 UTC, Damtev commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgStatementConstructor.kt
> +        ): CgAnnotation {
A bit strange formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgStatementConstructor.kt
> +            AnnotationTarget.Field -> error("Such annotations are not supported in JavasCRIPT")
Please, add info about the annotation to the error's message.

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> +enum class AnnotationTarget {
May we use `kotlin.annotation.AnnotationTarget` instead of creating our own type?

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> + * instead of explicit constructor call.
I guess, it's more preferrable to replace all these warnings with TODOs for rearranging packages/classes

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/access/CgFieldStateManager.kt
> +                createGetClassExpression(owner)
This method should not be used here. `CgJavaGetClass` seems to be always required because the `getStaticFieldValue` method accepts `java.lang.Class` as a parameter, not `kotlin.KClass`.

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    abstract fun addAnnotationForSpringRunner()
It's a bit unexpected to see a Spring specific method in this common manager

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +                )
Strange formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +                createGetClassExpression(this)
Same about `Class` - ASAIR `assertThrows` requires Java class too

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForSpringRunner() { }
Does it mean that `TestNg` does not work with nested classes and Spring? If so, I would rather expect errors instead of empty behavior

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +            )
Strange formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForNestedClasses() { }
Same as for `TestNg`

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
>              )
Formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addDataProviderAnnotations(dataProviderMethodName: String) { }
Same as for `TestNg`

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +                    ),
Formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +                    ),
Formatting

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgMethodConstructor.kt
> +                        createGetClassExpression(expected.type),
Same about `Class`

2023-06-28 11:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgStatementConstructor.kt
> +            createGetClassExpression(classId)
Looks like this implementation does not satisfies documentation

2023-06-28 13:09 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> +enum class AnnotationTarget {
Bue... it may lead the user to a wrong concern that we support or going to support all items from it. Next, in current implementation we are able to do smth like `Class(classId)` to specify the scope of current or outer class, for example. After that, do not forget that we get salary for the changed lines...

2023-06-28 13:11 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> + * instead of explicit constructor call.
I'm not sure it will be ever done in current codegen. We know about packaging in general. I added this warnings just for other users to avoid additional mess in the code.

2023-06-28 13:19 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForNestedClasses() { }
There is just no specific annotation in JUnit4, but it is not an error here.

2023-06-28 13:30 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    abstract fun addAnnotationForSpringRunner()
But I will remove it now and refactor everything else soon.

2023-06-28 13:59 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/TestFrameworkManager.kt
> +    override fun addAnnotationForNestedClasses() { }
Why? If it is just not required in JUnit4, please add a comment about it

2023-06-28 13:59 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/CgElement.kt
> + * instead of explicit constructor call.
> I'm not sure it will be ever done in current codegen
Perhaps it will not, but IMHO todo is much more notable than such a simple comment.

2023-06-28 14:01 UTC, Damtev approved these changes
Mostly LGTM

2023-06-28 15:31 UTC, merged