Exclude third-party libs from coverage statistics
UnitTestBot/UTBotJava pull request #2282
Opened 2023-06-13 10:34 UTC by sofurihafe

## Description

Fixes #2218

## How to test

### Manual tests

Tested on `ilya_m/ilya_m/spring_integration_test_prototype` branch. There are two instead of >8 tests.

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    ): UtExecution
I don't think it's a good design decision, to make `UtExecution` aware of all these properties from its subclasses. If needed, subclasses can add overloads of `copy` method with more parameters. 
```suggestion
    abstract fun copy(
        stateBefore: EnvironmentModels = this.stateBefore,
        stateAfter: EnvironmentModels = this.stateAfter,
        result: UtExecutionResult = this.result,
        coverage: Coverage? = this.coverage,
        summary: List<DocStatement>? = this.summary,
        testMethodName: String? = this.testMethodName,
        displayName: String? = this.displayName,
    ): UtExecution
```

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        val entityAnnotation = utContext.classLoader.tryLoadClass("javax.persistence.Entity")
Make it more readable and also easier to edit
```suggestion
        val ignoreCoverageAnnotations = listOfNotNull(utContext.classLoader.tryLoadClass("javax.persistence.Entity")
```

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        val classLoader = URLClassLoader(urls)
Better name would be `buildDirsClassLoader`

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                        execution.stateBefore.thisInstance?.classId?.jClass?.canonicalName == instrClassName) {
`canonicalName` is dot separated, while `instrClassName` is slash separated here. Also, in theory `thisInstance` can be an instance of a subclass of the class under test.

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                return this.mapNotNull { instruction ->
There's not mapping, just filtering
```suggestion
                return this.filter { instruction ->
```

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                                ?: false
Here you can use class loaded earlier to avoid `?.`s and `?: false`
```
// Check whether we can find the class in user classpath
val instrClass = classLoader.load(instrClassName) ?: return@mapNotNull null
```

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +            val filteredMissedInstructions = coverage.missedInstructions.filter()
`missedInstructions` are from method under test, we don't need to filter them

2023-06-13 13:38 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                    coveredInstructions = filteredCoveredInstructions,
Consider logging a warning and using original `coveredInstructions` if `filteredCoveredInstructions` is somehow empty

2023-06-13 14:06 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                        execution.stateBefore.thisInstance?.classId?.jClass?.canonicalName == instrClassName) {
> `canonicalName` is dot separated, while `instrClassName` is slash separated here.

Yes, I think you missed this:
https://github.com/UnitTestBot/UTBotJava/pull/2282/files/8c3415529499cbe7c12a74ec27cdbbd2db6f354e#diff-b410086455f775b569900a45f751c5cc55ec6d7a0eb1b9c4e73fa64272df9090R148

2023-06-13 14:20 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    ): UtExecution
If you are referring to this segment of code, then it won't require using `when` since you are only changing `coverage` which base `UtExecution` is aware of 
```kotlin
execution.copy(
    coverage = Coverage(
        coveredInstructions = filteredCoveredInstructions,
        instructionsCount = coverage.instructionsCount,
        missedInstructions = filteredMissedInstructions
    )
)
```

2023-06-13 14:27 UTC, IlyaMuravjov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    ): UtExecution
To be more clear here's what I suggest:
```kotlin
abstract class UtExecution(
    val stateBefore: EnvironmentModels,
    val stateAfter: EnvironmentModels,
    val result: UtExecutionResult,
    val coverage: Coverage? = null,
    var summary: List<DocStatement>? = null,
    var testMethodName: String? = null,
    var displayName: String? = null
) : UtResult() {
    abstract fun copy(
        stateBefore: EnvironmentModels = this.stateBefore,
        stateAfter: EnvironmentModels = this.stateAfter,
        result: UtExecutionResult = this.result,
        coverage: Coverage? = this.coverage,
        summary: List<DocStatement>? = this.summary,
        testMethodName: String? = this.testMethodName,
        displayName: String? = this.displayName,
    ): UtExecution
}

class UtSymbolicExecution(
    stateBefore: EnvironmentModels,
    stateAfter: EnvironmentModels,
    result: UtExecutionResult,
    val instrumentation: List<UtInstrumentation>,
    val path: MutableList<Step>,
    val fullPath: List<Step>,
    coverage: Coverage? = null,
    summary: List<DocStatement>? = null,
    testMethodName: String? = null,
    displayName: String? = null,
    /** Convenient view of the full symbolic path */ val symbolicSteps: List<SymbolicStep> = listOf(),
) : UtExecution(stateBefore, stateAfter, result, coverage, summary, testMethodName, displayName) {
    override fun copy(
        stateBefore: EnvironmentModels,
        stateAfter: EnvironmentModels,
        result: UtExecutionResult,
        coverage: Coverage?,
        summary: List<DocStatement>?,
        testMethodName: String?,
        displayName: String?
    ): UtExecution = UtSymbolicExecution(
        stateBefore = stateBefore,
        stateAfter = stateAfter,
        result = result,
        instrumentation = instrumentation,
        path = path,
        fullPath = fullPath,
        coverage = coverage,
        summary = summary,
        testMethodName = testMethodName,
        displayName = displayName
    )

    fun copy(
        stateBefore: EnvironmentModels = this.stateBefore,
        stateAfter: EnvironmentModels = this.stateAfter,
        result: UtExecutionResult = this.result,
        coverage: Coverage? = this.coverage,
        summary: List<DocStatement>? = this.summary,
        testMethodName: String? = this.testMethodName,
        displayName: String? = this.displayName,
        instrumentation: List<UtInstrumentation> = this.instrumentation,
        path: MutableList<Step> = this.path,
        fullPath: List<Step> = this.fullPath
    ): UtExecution = UtSymbolicExecution(
        stateBefore = stateBefore,
        stateAfter = stateAfter,
        result = result,
        instrumentation = instrumentation,
        path = path,
        fullPath = fullPath,
        coverage = coverage,
        summary = summary,
        testMethodName = testMethodName,
        displayName = displayName
    )
}

// more subclasses
```

2023-06-14 11:44 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +            else -> minimizeTestCase(executions) { it.result::class.java }
```suggestion
            else -> minimizeTestCase(when (applicationContext) {
                is SpringApplicationContext -> executions.filterCoveredInstructions()
                else -> executions
            }) { it.result::class.java }
```

2023-06-14 11:44 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        val loadedClasses = mutableMapOf<String, Class<*>?>()
```suggestion
        val isClassOnUserClasspathCache = mutableMapOf<String, Boolean>()        
        fun isClassOnUserClasspath(fullyQualifiedName: String): Boolean =
            isClassOnUserClasspathCache.getOrPut(fullyQualifiedName) {
                buildDirsClassLoader.tryLoadClass(fullyQualifiedName) != null
            }
```

2023-06-14 11:44 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        // Also, we filter out instructions that operate in classes marked as @Entity and in standard java libs
Marked with `ignoreCoverageAnnotations`

2023-06-14 11:44 UTC, IlyaMuravjov commented on utbot-js/src/main/kotlin/framework/api/js/JsUtFuzzedExecution.kt
> +        TODO("Not yet implemented")
Is that intended to stay as `TODO` here?

2023-06-14 11:44 UTC, IlyaMuravjov commented on utbot-python/src/main/kotlin/org/utbot/python/framework/api/python/PythonApi.kt
> +        TODO("Not yet implemented")
Is that intended to stay as `TODO` here?

2023-06-14 16:54 UTC, IlyaMuravjov approved these changes

2023-06-15 12:35 UTC, IlyaMuravjov requested changes

2023-06-15 12:41 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                buildDirsClassLoader.tryLoadClass(fullyQualifiedName) != null
To fix that I suggest introducing `thirdPartyClassLoader` that knows about whole user `classpath`, but `buildDirs` and instead of checking that "class can be loaded by `buildDirsClassLoader`" check that "class can't be loaded by `thirdPartyClassLoader`".

2023-06-15 13:58 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                buildDirsClassLoader.tryLoadClass(fullyQualifiedName) != null
Fixed

2023-06-15 14:04 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        if (buildDirs.isEmpty() || classpath.isNullOrEmpty()) return this
When can `classpath` be empty?

2023-06-15 14:04 UTC, IlyaMuravjov approved these changes

2023-06-17 13:53 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                        val instrClassName = instruction.className.replace('/', '.')
What exactly is `instrClassName` here? It seems to be sometimes used as canonical name and other times as binary name?

2023-06-18 11:57 UTC, IlyaMuravjov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +                        val instrClassName = instruction.className.replace('/', '.')
Binary and canonical name are different when it comes to member and anonymous classes. So make sure you've tested your code with class under test being at least a member class.

2023-06-19 16:22 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                                        val rdGenerateResult = withMinimizationStrategy(minimizationStrategy) {
Is that intended that `UtSettings.testMinimizationStrategyType` is completely ignored here?

2023-06-20 09:19 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                                        val rdGenerateResult = withMinimizationStrategy(minimizationStrategy) {
Is new version better?

2023-06-20 11:52 UTC, IlyaMuravjov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                                        val rdGenerateResult = withMinimizationStrategy(minimizationStrategy) {
Now `UtSettings.testMinimizationStrategyType` is only ignored for Spring projects. But I think if it is set to say `DO_NOT_MINIMIZE_STRATEGY` it's expected that tests won't get minimized even if we deal with a Spring project. One way to achieve that is to add `TestSelectionStrategyType.DEFAULT` that is a default value and is replaced with either `USER_INSTRUCTIONS_ONLY_COVERAGE_STRATEGY` or `COVERAGE_STRATEGY` in a `TestCaseGenerator#minimizeExecutions` depending on the type of the project.

2023-06-23 09:09 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        return this.stateBefore.thisInstance?.classId?.name == name ||
When we call minimization, we have methodUnderTest. It is better to get classId from it.
This code seems to be correct now, but after future improvements of engine or fuzzer some subclass may be stored in thisInstance.

2023-06-23 10:12 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestCaseGenerator.kt
> +        return this.stateBefore.thisInstance?.classId?.name == name ||
Ok, fixed that.

2023-06-23 10:18 UTC, EgorkaKulikov approved these changes

2023-06-23 10:39 UTC, merged