Support running Spring integration tests in instrumentation process
UnitTestBot/UTBotJava pull request #2335
Opened 2023-06-29 09:31 UTC by sofurihafe

## Description

Fixes # (issue)

Add more info _if needed_:
* context/purpose for implementing changes
* detailed description of the changes made

## How to test

### Automated tests

Please specify the _automated tests_ for your code changes: you should either mention the existing tests or add the new ones.

For example:

> The proposed changes are verified with tests:
> `utbot-fuzzing/src/test/kotlin/org/utbot/fuzzing/FuzzerSmokeTest.kt`

### Manual tests

If it is impossible to provide the automated tests, please reason why. Usually, it is relevant only for UI- or documentation-related PRs.
If this is your case, share the detailed _manual scenarios_ that help to verify your changes.

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [ ] I've set the proper **labels** for my PR (at least, for category and component).
- [ ] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-07-04 07:49 UTC, EgorkaKulikov requested changes

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/SpringUtExecutionInstrumentation.kt
> +            // TODO move forcing `getBean()` somewhere else (we need to once forcefully get beans under test
It seems that we may just call `getBean` after `resetBean` before calling instrumentation and leave a comment that we need to force loading there. It is not a good idea to get beans inside a method `getBeanNames` for me, looks like a side effect.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/SpringUtExecutionInstrumentation.kt
> +        // transforming Spring takes too long
Let's make this comments more clear.
For me, first one is smth like "We do not transform Spring classes as it takes to long and mostly useless because ..."
Second one does not explain how transforming these classes may give fuzzer more feedback, arbitrary developer will not understand it.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/context/SimpleInstrumentationContext.kt
> +    override fun constructContextDependentValue(model: UtModel): UtConcreteValue<*>? = null
This implementation is very unclear to me. When should we avoid creating values for any model? Add the documentation for the whole class, please.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> +        invoke(clazz, methodSignature, arguments, parameters, phasesWrapper = { it() })
May be `phasesRunner`?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> +                    // some preparation actions for concrete execution
May be we should add some details about actions in brackets?
`Some preparation actions (..., ..., ...) for concrete execution`
For the method `applyPostProcessing` a comment will also be useful.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> -                } catch (t: Throwable) {
Why don't we catch the exeption here any more? As far as I remember, there is some alternative, but I forgot the details.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/UtExecutionInstrumentation.kt
> +                    val constructedData = applyPreprocessing(parameters)
What for do you need this variable?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/constructors/MockValueConstructor.kt
> +            }
By the way, there is a similar method in `ValueConstructor` and currently (and before) it is inconsistent with this one. Is it ok? We do not use specific processing of Spring context model there.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/context/InstrumentationContext.kt
> +    fun constructContextDependentValue(model: UtModel): UtConcreteValue<*>?
Add documentation, please.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/phases/ValueConstructionPhase.kt
> +    override fun wrapError(e: Throwable): ExecutionPhaseException = ExecutionPhaseStop(
Is it the better alternative to may catch block?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzer/SpringApplicationAnalyzer.kt
> +                .catch { instantiator.instantiate().context }
Don't like this code now. it is very unclear what we catch here? Some problem in field getter?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons-api/src/main/kotlin/org/utbot/spring/api/context/ContextWrapper.kt
> +    /**
Add smth like `NOTE!` please to fire that it is not only declarative documentations, but also important extensions how to use.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/build.gradle.kts
> +    compileOnly("org.springframework:spring-test:5.2.6.RELEASE")                    // TODO: fix the version
TODOs are still actual...

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/src/main/kotlin/org/utbot/spring/context/BaseDummyTestClass.kt
> +open class BaseDummyTestClass {
`BaseSpringIntegrationTestsDummyClass`?
I also suggest to introduce a separate package for dummy classes.

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/src/main/kotlin/org/utbot/spring/context/SpringBootDummyTestClass.kt
> +class SpringBootDummyTestClass : BaseDummyTestClass()
May be we should create not only SpringBoot implementation of base class, but PureSpring also and make it just extend base class as is to make it more clear?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/src/main/kotlin/org/utbot/spring/context/SpringContextWrapper.kt
> +    private lateinit var dummyTestInstance: BaseDummyTestClass
`dummyTestClassInstance`?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/src/main/kotlin/org/utbot/spring/context/SpringContextWrapper.kt
> +        private fun parseProfileExpression(profileExpression: String?): Array<String> =
I don't understand how profile expressions are now used in unit tests for bean definitions analysis? Is it really a good place to locate this method?

2023-07-04 07:49 UTC, EgorkaKulikov commented on utbot-spring-commons/src/main/kotlin/org/utbot/spring/instantiator/PureSpringApplicationInstantiator.kt
>  class PureSpringApplicationInstantiator : SpringApplicationInstantiator {
Could you rename all instantiators and related methods to api providers, as we discussed yesterday, please?

2023-07-04 14:58 UTC, EgorkaKulikov commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/SpringUtExecutionInstrumentation.kt
> +            // TODO move forcing `getBean()` somewhere else (we need to once forcefully get beans under test
Let's call it `getRelevantBeans` then.

2023-07-05 10:17 UTC, IlyaMuravjov approved these changes
All comments will be addressed in a separate pull request, this pull request need to be merged now to avoid conflicts with @sofurihafe who is about to start making new improvements to updated parts of the project.

2023-07-06 07:02 UTC, EgorkaKulikov commented
LGTM, requested some optional naming improvements personally.

2023-07-06 07:02 UTC, EgorkaKulikov approved these changes

2023-07-06 08:02 UTC, merged