Extract `utbot-spring-framework` module from `utbot-framework`
UnitTestBot/UTBotJava pull request #2570
Opened 2023-08-30 14:32 UTC by IlyaMuravjov

## Description

**All** spring-specific logic is extracted from `utbot-framework` module to `utbot-spring-framework` module.

## How to test

Regression tests, this PR should not change UtBot semantics at all.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-09-06 08:43 UTC, Damtev requested changes
There are some unobvious moments

2023-09-06 08:43 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
> +    }
Why do we have only one post-processing task? Perhaps it could be a list of such tasks performed consequently.

2023-09-06 08:43 UTC, Damtev commented on utbot-spring-framework/build.gradle.kts
> +val sootVersion: String by rootProject
Do we really need Soot for this module?

2023-09-06 08:43 UTC, Damtev commented on utbot-spring-framework/src/main/kotlin/org/utbot/framework/codegen/domain/SpringModule.kt
> +abstract class SpringModule(
Why not make it an enum?

2023-09-06 08:43 UTC, Damtev commented on utbot-spring-framework/src/main/kotlin/org/utbot/framework/process/SpringAnalyzerTask.kt
> +class SpringAnalyzerTask(
Is it true that it does not matter will this task be performed before the symbolic analysis or after? So, can we always consider it as a post-processing task?

2023-09-06 08:43 UTC, Damtev commented on utbot-spring-framework/src/main/kotlin/org/utbot/framework/codegen/tree/fieldmanager/ClassFieldManagerFacade.kt
> +
It's not very obvious why this object and this extension method (which seem to be common for any possible extension to the `CgContext` - Spring, or any other in the future) are located in this Spring-specific module

2023-09-06 08:43 UTC, Damtev commented on utbot-rd/src/main/rdgen/org/utbot/rd/models/EngineProcessModel.kt
> +        field("engineProcessTask", array(PredefinedType.byte))
Based on its usage, this task seems to always be **post-processing**. Am I right? If so, please rename it correspondingly

2023-09-06 14:09 UTC, IlyaMuravjov commented on utbot-spring-framework/src/main/kotlin/org/utbot/framework/process/SpringAnalyzerTask.kt
> +class SpringAnalyzerTask(
It's always performed before symbolic analysis and its results are later used to guide type replacement during symbolic execution.

2023-09-07 09:02 UTC, Damtev approved these changes
LGTM

2023-09-07 10:57 UTC, Vassiliy-Kudryashov approved these changes

2023-09-07 20:29 UTC, merged