Support for both Cookie libraries for different versions of Spring
UnitTestBot/UTBotJava pull request #2606
Opened 2023-09-18 17:10 UTC by tepa46

## Description

Fixes #2542

Added support for `jakarta.servlet.http.Cookie` which is used in newer versions of Spring.

## How to test

### Manual tests
Tested on the `spring-petclinic` project. (Spring Boot 3.1.3 with `jakarta.servlet.http.Cookie`)
Tested on the `spring-boot-testing` project. (Spring Boot 2.7.3 with `javax.servlet.http.Cookie`)

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

2023-09-19 08:18 UTC, EgorkaKulikov requested changes

2023-09-19 08:18 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +        cookieClassId: ClassId,
I do not  catch an idea here. What for do we pass an argument and do not use it?

2023-09-19 08:18 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +        val cookieClassId = cookieClassIds.singleOrNull()
Why not firstOrNull? Is it guarantied that a user may not use them in common (even without any real motivation for it)?

2023-09-19 08:18 UTC, EgorkaKulikov commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +        if(cookieClassId is ClassId) {
This is an equivalent of cookieClassIs is null? Why not `?.let { ... } ?: warn { ...}` then? Anyway, the semantic of your check is not clear.

2023-09-19 22:00 UTC, tepa46 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/SpringModelUtils.kt
> +        val cookieClassId = cookieClassIds.singleOrNull()
Depending on which version of Spring is used in the user project, Spring uses different cookie libraries. If the user uses them in common, it is unclear which of the libraries use to build models.

2023-09-20 06:39 UTC, EgorkaKulikov approved these changes

2023-09-20 06:39 UTC, merged