Improve python tracing process
UnitTestBot/UTBotJava pull request #2662
Opened 2023-10-20 09:17 UTC by tamarinvs19

## Description

### Coverage
Supported new coverage measurement mode for python with uses instructions.
Current methods:
* use lines coverage (previous)
* use instructions coverage (by default now)

Added new option to change coverage output format:
* lines (default)
* instructions

Added new option to switch off sending coverage continuously during execution. If you use this option execution process will be faster but in case unexpected failure of execution we will lose coverage info. By default this option is __disable__.

All of this options you can set in python-cli:
* `--coverage-measure-mode` (`LINES`/`INSTRUCTIONS`)
* `--do-not-send-coverage-continuously`
* `--coverage-output-format` (`LINES`/`INSTRUCTIONS`)

### Other
* Added progress bar for script `run_tests.py`
* Updated target values in `test_configuration.json`
* Used python instructions in python fuzzing

## How to test

### Automated tests

Run `utbot-python/samples/run_tests_all.sh` and check coverage results.

### Manual tests

Run python-cli with arguments `--

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

2023-10-24 09:12 UTC, tochilinak requested changes
Problems with conversion from `PyInstruction` to `UtInstruction` (and probably they shouldn't be different classes, this logic is too complex).

2023-10-25 22:37 UTC, tochilinak commented
`utbot-executor==1.8.0` not published on pypi

2023-10-26 06:33 UTC, tamarinvs19 commented
> `utbot-executor==1.8.0` not published on pypi

Fixed

2023-10-26 09:55 UTC, tochilinak approved these changes

2023-10-26 12:10 UTC, EgorkaKulikov approved these changes

2023-10-26 12:11 UTC, merged