Fuzzing consume much memory for a method with 10 and more parameters
UnitTestBot/UTBotJava pull request #335
Opened 2022-06-28 14:02 UTC by Markoutte

# Description

Provides another way to randomized fuzzer generated values. This approach helps to create a sequence of shuffled unique integers  without huge memory consumption for corner cases. Previously, it was creating an array for storing as much integers as fuzzer had possible values combinations thus it leads to OOME.

Fixes #293

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Run PseudoShuffledIntProgressionTest to validate that an implementation is correct.

## Manual Scenario 

Create a test with 10 parameters:

```java
    public int test(int x, boolean y, String s, Integer z, float f, double g,
                    int x2, boolean y3, String s4, Integer z5, float f6, double g2) {
        return -1;
    }
```

Run test generation with fuzzer and capture memory snapshot. Find `org.utbot.fuzzer.PseudoShuffledIntProgression` object and check that retained size isn't big (in my case for 6 553 600 values it takes only 20 596 bytes).

2022-06-28 14:56 UTC, CaelmBleidd requested changes
Some places are a bit confusing at first sight, but everything seems fine

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> + * 1. Separate a sequence into 2 parts: matrix-part and tail
How do we separate them? From the example we can see, that we transform the sequence into `n * n` matrix with a `size - n * n` tail. Is it always true?

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +    constructor(size: Int, random: Random = Random) : this (size, random, { sqrt(it.toDouble()).toInt() })
extra space

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +        left = IntArray(size = if (topSize == 0) 0 else size / topSize) { it }.apply { shuffle(random) }
How `topSize` can be equal to zero here? We checked that it must be positive

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +        left = IntArray(size = if (topSize == 0) 0 else size / topSize) { it }.apply { shuffle(random) }
Can you add a description for the fields, please? Or, probably, it is better to change names. I believe, `top` is the number of the columns and `left` is the number of the rows?

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +        override fun hasNext() = current < size
Is it right? We stated that it `Generates pseudo random values from 0 to size exclusive.`

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> + * Columns are shuffled:
Can you add an extended explanation, please? Not only with the matrix but with `top` and `left` arrays as well

2022-06-28 14:56 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +            top[i] * l + left[j]
Can you add an example, just like you added for the whole algorithm, please?  For me, it is not obvious work with `tail.size * e`

2022-06-29 06:57 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +        left = IntArray(size = if (topSize == 0) 0 else size / topSize) { it }.apply { shuffle(random) }
> How topSize can be equal to zero here? We checked that it must be positive

Top size can be 0 in case when size is 0. Both arrays should be 0 in this case

2022-06-29 08:28 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> +        override fun hasNext() = current < size
Looks like yes, because for size 10 we want to generate sequence like [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. Added a test on this

2022-06-29 08:48 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt
> + * 1. Separate a sequence into 2 parts: matrix-part and tail
Rewrite this algorithm to clarify this place

2022-06-29 10:46 UTC, CaelmBleidd approved these changes
LGTM

2022-06-29 11:00 UTC, merged