Disabled NPE checks for non-public library fields by default
UnitTestBot/UTBotJava pull request #353
Opened 2022-06-29 23:03 UTC by Damtev

TODO

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

2022-06-30 15:01 UTC, CaelmBleidd approved these changes
LGTM

2022-06-30 15:20 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        if (maximizeCoverageUsingReflection || !field.declaringClass.isLibraryClass) {
Looks like it is wrong because these methods search in different stores.

2022-06-30 15:21 UTC, dtim approved these changes
Seems good.

2022-06-30 15:21 UTC, dtim commented on docs/SpeculativeFieldNonNullability.md
> +allow `null` values). Automatically generated tests assign `null` values to fields in questions using reflection,
It's my mistake from the previous commit, but I think it would be better to remove "in questions" here.

2022-07-04 16:09 UTC, CaelmBleidd approved these changes

2022-07-04 16:09 UTC, CaelmBleidd commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/TrustedLibraries.kt
> +        "com.alibaba.fastjson",
Does that mean we won't check NPE for users from `fastjson`, for example?

2022-07-05 08:54 UTC, dtim requested changes
The code looks good, but I think that the default set of trusted libraries should be reduced.

2022-07-05 08:54 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/TrustedLibraries.kt
> +        "com.google.common",
As libraries can't be removed from the default set by the user, the default set should contain the minimal necessary set, probably only JDK.

2022-07-05 09:04 UTC, dtim approved these changes
LGTM

2022-07-07 11:19 UTC, merged