Minimize exceptions in signature
UnitTestBot/UTBotJava pull request #418
Opened 2022-07-05 13:09 UTC by sofurihafe

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

2022-07-05 13:41 UTC, Damtev requested changes
Overall, LGTM

2022-07-05 13:41 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/context/CgContext.kt
> +    fun addExceptionIfNeeded(exception: ClassId) {
Passing `BuiltinClassId`  to this method possibly leads to `ClassNotFoundException` because of a missing class in the classpath.  Perhaps we should check it and early return in such a case.

Also, I suggest checking if passed `ClassId` is actually a checked exception - we do not need to collect an unchecked exception.

2022-07-05 15:30 UTC, Damtev requested changes

2022-07-05 15:30 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/context/CgContext.kt
> +            .removeIf { existingException -> existingException isSubtypeOf exception }
Looks like you inverted the logic here - we are going to remove a super exception in case the passed exception is an inheritor of it, but here you are removing all inheritors of the passed exception.

2022-07-06 16:58 UTC, EgorkaKulikov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/context/CgContext.kt
> +            .removeIf { existingException -> existingException isSubtypeOf exception }
It is the filtering of "small" exceptions if we add "huge" ones, seems to be correct to me.

2022-07-06 16:59 UTC, EgorkaKulikov approved these changes

2022-07-07 15:57 UTC, Damtev requested changes
The big problem found, need to discuss

2022-07-08 06:52 UTC, Damtev approved these changes
Discussed, everything is OK

2022-07-08 07:50 UTC, merged