Disabled tests for autogenerated functions
UnitTestBot/UTBotJava pull request #505
Opened 2022-07-12 15:29 UTC by volivan239

# Description

Disabled tests for autogenerated functions
Fixes # (issue)

## Type of Change

-  bug fix (non-breaking small changes)

# How Has This Been Tested?

## Automated Testing

None

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

2022-07-13 12:01 UTC, dtim commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt
> +                                        if (!srcClass.isEnum)
It seems that the approach with `SyntheticElement` can be used here as well.

2022-07-13 12:09 UTC, dtim commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> +            it.displayName.substringBefore('(') in listOf("values", "valueOf") && it.clazz.java.isEnum
There are many sequential calls to `filter`/`filterNot`. To avoid creation of too many intermediate lists, it would be better to use `asSequence()` call on the original collection (`methodsToGenerate`), and then convert the resulting  sequence to a list.

2022-07-13 12:15 UTC, dtim commented on utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt
> +                    it.displayName.substringBefore('(') in listOf("values", "valueOf")
I think that string constants should be defined once, e.g., in an object in `utbot-framework-api`, and referenced everywhere they are needed: cli, contest estimator, maybe the plugin (see next comments for details about the plugin).

Maybe the condition that is used inside `filterNot` may be implemented as a separate function as well?

2022-07-15 08:17 UTC, volivan239 commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +            items = if (!srcClasses.single().isEnum)
Rewrote like you suggested, the code looks prettier now

2022-07-15 08:17 UTC, volivan239 commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt
> +                                        if (!srcClass.isEnum)
done

2022-07-15 08:21 UTC, volivan239 commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> +            it.displayName.substringBefore('(') in listOf("values", "valueOf") && it.clazz.java.isEnum
done, but I have no idea what is the best way to deal with many sequential filters

2022-07-15 08:24 UTC, volivan239 commented on utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt
> +                    it.displayName.substringBefore('(') in listOf("values", "valueOf")
Put list of excluded methods into `org.utbot.framework.SyntheticMethods` and moved condition in filter to a function in `org.utbot.framework.util` (`SyntheticMethodsChecker.kt`)

2022-07-18 09:23 UTC, dtim requested changes
Algorithmically and conceptually the PR is good, but there are some issues with the code organization. I would like also suggest some stylistic changes.

2022-07-18 09:23 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntethicMethodsChecker.kt
> +fun isSynthetic(method: UtMethod<*>): Boolean =
We already have an extension function for `ClassId` with the same name that checks the corresponding JVM attribute of the method: `org.utbot.framework.plugin.api.ClassId#isSynthetic`.

Your function applies to enums only, so I think it would be better to rename it.

I would also suggest to avoid creating Kotlin files with a single function. It seems that this function can be moved to `SyntheticMethods.kt`, it would be easier to navigate the code that way.

2022-07-18 09:23 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt
> +object SyntheticMethods {
This objects stores method names, not `UtMethod` or Java/Kotlin callables, so I would suggest to rename it to something like "KnownSyntheticMethodNames".

2022-07-18 09:23 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt
> +    val enumSyntheticMethods = listOf("values", "valueOf")
I think it would be nice to have a KDoc for `enumSyntheticMethods` value and for the container object.

2022-07-18 09:23 UTC, dtim commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> +        }.filterWhen(!UtSettings.generateForSyntheticMethods) { !isSynthetic(it) }
I would suggest to write `filterNot` condition in a single line, or at least move `.filterWhen` call to the next line after the closing brace.

2022-07-18 09:25 UTC, dtim commented on utbot-core/src/main/kotlin/org/utbot/common/FilterWhen.kt
> + * If [condition] is true, returns list containing only elements, matching [predicate].
I think an article is missing before "list", and a comma before "matching" is not necessary: "If [condition] is true, returns a list containing only elements matching [predicate]".

2022-07-18 12:03 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var generateForSyntheticMethods by getBooleanProperty(false)
Renamed to `skipTestGenerationForSyntheticMethods` with opposite value

2022-07-18 12:04 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt
> +object SyntheticMethods {
Renamed to `KnownSyntheticMethodNames`

2022-07-18 12:05 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt
> +    val enumSyntheticMethods = listOf("values", "valueOf")
Done

2022-07-18 12:05 UTC, volivan239 commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> +        }.filterWhen(!UtSettings.generateForSyntheticMethods) { !isSynthetic(it) }
Done

2022-07-18 13:11 UTC, dtim approved these changes
LGTM. If possible, it would be nice to have some unit tests in CLI.

2022-07-18 16:01 UTC, merged