Text for JetBrains marketplace closes #53
UnitTestBot/UTBotJava pull request #54
Opened 2022-05-27 14:33 UTC by denis-fokin

# Description

We discussed the text with the team.

## Type of Change

Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
I checked the plugin representation in the IDE.

## Automated Testing

No automated tests.

## Manual Scenario 

Open IDE, install the plugin and check the plugin description.

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings
- [x] All tests pass locally with my changes

2022-05-27 16:01 UTC, korifey requested changes

2022-05-27 16:01 UTC, korifey commented on utbot-intellij/src/main/resources/META-INF/plugin.xml
> +                <br />
Found issue? Please submit it here: https://github.com/UnitTestBot/UTBotJava/issues

2022-05-27 21:41 UTC, denis-fokin commented on utbot-intellij/src/main/resources/META-INF/plugin.xml
> +                <br />
I have used a link

2022-05-28 12:29 UTC, korifey approved these changes
Lgtm

2022-05-28 16:35 UTC, alexeyfridman approved these changes

2022-05-28 16:47 UTC, merged