Skip test generation for abstract methods #550
UnitTestBot/UTBotJava pull request #556
Opened 2022-07-19 15:24 UTC by volivan239

# Description

* Added filters for abstract methods, so now they don't reach test generator
* Added catch for exception which is thrown when plugin tries to generate tests for an abstract class that has no implementations (in this case error message is shown in UI)

Fixes #550

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

No tests were added.

## Manual Scenario 

* Launch plugin on example from #550 -- works as expected.
* Launch plugin on a package with abstract class with default functions and no derived classes -- test generation for this class is skipped and an error message is shown.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-07-21 08:44 UTC, Damtev requested changes

2022-07-21 08:44 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +                .filterNot { it.member.modifierList?.hasModifierProperty(PsiModifier.ABSTRACT)?: false }
Please, move such a function somewhere in utils.

2022-07-21 08:44 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                                    } catch (e: java.lang.IllegalStateException) {
Are we really going to catch only `IllegalStateException`? Maybe, we should catch every exception here? Need to discuss

2022-07-28 12:33 UTC, volivan239 commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
> +                .filterNot { it.member.modifierList?.hasModifierProperty(PsiModifier.ABSTRACT)?: false }
Moved to `org.utbot.intellij.plugin.util.MemberInfoUtilsKt#isAbstract`

2022-07-28 12:33 UTC, volivan239 commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
> +                                    } catch (e: java.lang.IllegalStateException) {
As discussed, replaced with `runCatching`

2022-07-28 12:49 UTC, Damtev approved these changes

2022-07-28 14:14 UTC, merged