Parametrized test generation in Uber tests
UnitTestBot/UTBotJava pull request #573
Opened 2022-07-21 15:17 UTC by sofurihafe

# Description

This PR adds support for parametrized test generation in Uber tests. It doesn't generate them if `Symbolic Engine` encounters force mocking.

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

Run `CodegenExampleTest`. Verify that parametrized test generation doesn't fail when force mocking took place.

2022-07-21 16:13 UTC, nikitavlaev requested changes

2022-07-21 16:13 UTC, nikitavlaev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt
> +        fun delete(testCaseGenerator: TestCaseGenerator, listener: MockListener) {
`delete` does not look like responsibility of the ForceMockListener.
At least it does not delete anything.
Move this method from companion object to class and name it something like `detach`.

2022-07-21 16:13 UTC, nikitavlaev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceStaticMockListener.kt
> +        fun delete(testCaseGenerator: TestCaseGenerator, listener: MockListener) {
Same here

2022-07-21 16:13 UTC, nikitavlaev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt
> +        fun delete(testCaseGenerator: TestCaseGenerator, listener: MockListener) {
Maybe make `Listener` implement `Closeable` and use it with `use`?

2022-07-21 16:13 UTC, nikitavlaev commented on utbot-framework/src/test/kotlin/org/utbot/framework/codegen/TestCodeGeneratorPipeline.kt
> +        return codeGenerator.generateAsString(
Comment why `listOf()`

2022-07-21 16:13 UTC, nikitavlaev commented on utbot-framework/src/test/kotlin/org/utbot/examples/UtValueTestCaseChecker.kt
> +    private lateinit var currentTestFrameworkConfiguration: TestFrameworkConfiguration
This causes pipeline to fail. You access it before initialization somehow

2022-07-21 16:15 UTC, nikitavlaev commented on utbot-framework/src/test/kotlin/org/utbot/framework/codegen/TestCodeGeneratorPipeline.kt
> +        val isParametrizedAndForceMocked = testFrameworkConfiguration.isParametrizedAndMocked
Not sure if that variable is required

2022-07-21 20:48 UTC, sofurihafe commented on utbot-framework/src/test/kotlin/org/utbot/framework/codegen/TestCodeGeneratorPipeline.kt
> +        return codeGenerator.generateAsString(
Done

2022-07-21 20:52 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt
> +        fun delete(testCaseGenerator: TestCaseGenerator, listener: MockListener) {
Moved `detach` method to `MockListener` abstract class because it's the same for both listeners

2022-07-21 20:52 UTC, sofurihafe commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceStaticMockListener.kt
> +        fun delete(testCaseGenerator: TestCaseGenerator, listener: MockListener) {
Done

2022-07-21 20:52 UTC, sofurihafe commented on utbot-framework/src/test/kotlin/org/utbot/examples/UtValueTestCaseChecker.kt
> +    private lateinit var currentTestFrameworkConfiguration: TestFrameworkConfiguration
Fixed

2022-07-21 20:55 UTC, sofurihafe commented on utbot-framework/src/test/kotlin/org/utbot/framework/codegen/TestCodeGeneratorPipeline.kt
> +        val isParametrizedAndForceMocked = testFrameworkConfiguration.isParametrizedAndMocked
Seems like it, removed

2022-07-25 18:30 UTC, nikitavlaev approved these changes

2022-07-25 21:13 UTC, merged