Introduce custom JavaDoc tags #565
UnitTestBot/UTBotJava pull request #585
Opened 2022-07-25 15:03 UTC by onewhl

# Description

Introduce custom JavaDoc tags to make generated code comments structured.

`@utbot.classUnderTest` - Inline link to the enclosing class.
`@utbot.methodUnderTest` - Inline link to the method we test.
`@utbot.expectedResult` - Value we expect to get.
`@utbot.actualResult` - Value we got.
`@utbot.executes` - Executed condition.
`@utbot.invokes` - Invoked method.
`@utbot.returnsFrom` - Statement we return from.
`@utbot.throwsException` - Thrown exception.

**TODO**: check if it works after plugin removal
**TODO**: add unit tests
**TODO**: add a flag generateCustomTags to UtSettings 
**TODO**: make UtBot generate tests using custom tags

Fixes #565

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

TODO: write unit tests

## Manual Scenario 

1. Open any Java project in IntelliJ IDEA.
2. Add JavaDoc comment above any method and start typing `@utbot` -> you will notice that completion works and our custom tags are shown.
3. You can also render comment clicking toggle on the right side of the comment.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

2022-07-27 12:52 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useFuzzing: Boolean by getBooleanProperty(false)
don't forget to remove in the final PR (just reminder)

2022-07-27 12:52 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgAbstractRenderer.kt
> -        println("<pre>")
Just found a discussion, what's tag combination is the best for usage with code https://stackoverflow.com/questions/541920/multiple-line-code-example-in-javadoc-comment

Looks like combination ```<pre>{@code``` wins

2022-07-27 12:52 UTC, amandelpie commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            builder.append(tmp.toString().trim { it <= ' ' })
let's use Kotlin DSL for String builders like here https://github.com/UnitTestBot/UTBotJava/blob/4f1c7f51229011b8b6eef953375e702166f86a88/utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt#L257

2022-07-27 12:52 UTC, amandelpie commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +            invokes = null,
Is this object is not filled fully yet? and is under development?

2022-07-27 15:35 UTC, onewhl commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +            invokes = null,
yes, i'm working on extracting values from jimple to fill these tags with values.
but not all of them could be filled, it depends of the execution path the test covers.
we will show only tags we have values for

2022-07-27 15:35 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            builder.append(tmp.toString().trim { it <= ' ' })
thanks, I will rework it!

2022-08-04 13:25 UTC, onewhl commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgAbstractRenderer.kt
> -        println("<pre>")
Reverted this change and added a check if a custom javadoc tags are used

2022-08-08 10:22 UTC, onewhl commented
I would like to discuss several things.

- Is it OK to change global settings from UtSettings in tests (see SummaryTestCaseGeneratorTest)? The order of tests is non-determined, it seems it possible could lead to errors.
- Is it possible to show error message in CI logs in case test fail?

2022-08-08 15:35 UTC, Damtev requested changes

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        var offset = if (tagElements.isNotEmpty()) {
Consider using early-return for empty elements

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                if (tagElement.textOffset > offset) this.append(' ')
Same about braces

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                if (i < tagElements.size - 1) {
Consider using `lastIndex` instead of `size - 1`

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        }.trim { it <= ' ' }
Same about this strange predicate

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        }
```kotlin
val linkLabel = label ?: context.manager.let {
    JavaDocUtil.getLabelText(it.project, it, refText, context)
}
```

2022-08-08 15:35 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            logger.info(e) { "Failed to find a reference while generating JavaDoc comment. Details: ${e.message}" }
Is it really an expected situation, that could be properly processed later?

2022-08-08 15:35 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +            traceTag.result.exceptionOrNull()?.let { it::class.qualifiedName }
It looks like this expression always equals to `null` value

2022-08-08 15:35 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +                        //TODO: do we need to handle others?
It looks like a question for @amandelpie. Anyway, please make an issue for this, if it could not be resolved now

2022-08-08 17:21 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useCustomJavaDocTags by getBooleanProperty(false)
I am a bit confused with this `false` default value. As I understand, this request is mostly about a new user feature, but for now the only way for user to enable it is editing `UtSettings` that is definitely not obvious. Perhaps this setting should be `true` by default for the plugin and/or be editable from the plugin settings directly

2022-08-09 08:26 UTC, onewhl commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +        if (other is DocCustomTagStatement) this.hashCode() == other.hashCode() else false
I defined `equals` and `hashcode` in the same way it's defined for other `DocTagStatement's` inheritors (`DocPreTagStatement`, `DocClassLinkStmt`, `DocCodeStmt`, and so on). Do you think we need fix it for all `DocTagStatement's` inheritors as well? If yes, it sounds like a separate task on refactoring.

2022-08-09 08:28 UTC, onewhl commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/tree/CgElement.kt
> +        } else false
Please, see question in the comment above.

2022-08-09 08:35 UTC, onewhl commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgAbstractRenderer.kt
> +        for (stmt in element.content) stmt.accept(this)
OK. Could we define these formatting preferences in `.editorconfig`? I was guided on how surrounding code in this class is formatted.

2022-08-09 08:36 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtCustomJavaDocTagProvider.kt
> +        }
Agree, thanks!

2022-08-09 08:46 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt
> +    }
Looks nice, thanks!

2022-08-09 09:41 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        val builder: StringBuilder = StringBuilder(javadoc)
We get `javadoc` from the platform, it could be null (see `JavaDocInfoGenerator#generateRenderedDocInfo()`). I will add null check to line 34.

2022-08-09 09:43 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtCustomJavaDocTagProvider.kt
> +        CustomJavaDocTagProvider().getPluginCustomTags().map { t -> UtCustomTagInfo(t) }
Ok.

2022-08-09 10:58 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        comment: PsiDocComment?,
Thanks!

2022-08-09 11:03 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +    }
Cool, thanks

2022-08-09 11:08 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        }
Nice, thanks

2022-08-09 11:11 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            logger.info(e) { "Failed to find a reference while generating JavaDoc comment. Details: ${e.message}" }
It could be useful to have this information in logs, why not?

2022-08-09 11:13 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +        if (other is DocCustomTagStatement) this.hashCode() == other.hashCode() else false
Well, yes, I think we need to refactor others in the future, but please, change it for the new classes in this PR.

2022-08-09 11:15 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgAbstractRenderer.kt
> +        for (stmt in element.content) stmt.accept(this)
Actually, we do not have any specific formatting preferences except [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html) and [Java code conventions](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf), so we just try to write code according to them

2022-08-09 11:17 UTC, onewhl commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +        return listOf<DocStatement>(DocCustomTagStatement(docStatementList))
Ok, I'll remove it

2022-08-09 11:17 UTC, onewhl commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +        val comment: CustomJavaDocComment = buildCustomJavaDocComment(method)
Ok

2022-08-09 11:24 UTC, Damtev commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            logger.info(e) { "Failed to find a reference while generating JavaDoc comment. Details: ${e.message}" }
Yes, of course, but I mean, is it a pipeline-breaking error or just a common situation with a problem with using some built-in features, that could be correctly processed with some kind of workaround?

2022-08-09 11:33 UTC, Damtev commented
> I would like to discuss several things.
> 
> * Is it OK to change global settings from UtSettings in tests (see SummaryTestCaseGeneratorTest)? The order of tests is non-determined, it seems it possible could lead to errors. I used JUnit extension to avoid it.
> * Is it possible to show error message in CI logs in case test fail?

1. Mostly it is **not** OK, just because of your mentioned, reasons, so we use a lot of util functions that change them only for specific tests. You can see some examples  in the `org.utbot.examples.UtValueTestCaseChecker` file, like `withoutMinimization` and others. But I suppose your way is acceptable too.
2. I am not sure about common logs, but we publish some artifacts after a pipeline ending, that you can find in [the pipeline summary tab](https://github.com/UnitTestBot/UTBotJava/actions/runs/2816286407). One of them is `utbot_framework_logs`, which is a simple gradle tests report. In this report, you can find logs and, most importantly, test output for each test.

2022-08-15 06:34 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                    element is PsiDocToken && element.tokenType !== JavaDocTokenType.DOC_COMMENT_LEADING_ASTERISKS
It seems it should, methods in this class were taken from the IJ platform.

2022-08-22 09:08 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useCustomJavaDocTags by getBooleanProperty(false)
I suggest to move this settings to UtSummarySettings and enable as true

2022-08-22 09:08 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useCustomJavaDocTags by getBooleanProperty(false)
Also I suggest to create a ticket to add this settings (for display name and for custom java tags to the plugin settings)

2022-08-22 11:11 UTC, amandelpie requested changes
Please make some minor changes

2022-08-23 14:08 UTC, onewhl commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/tree/CgElement.kt
>  class CgDocCodeStmt(val stmt: String) : CgDocStatement() {
We need a separate statement type to make it possible to handle comment with tags differently from regular ones (CgDocPreTagStatement). We don't want to wrap comments with custom tags in <pre> tags.

See `visit(element: CgDocPreTagStatement) `  and `visit(element: CgCustomTagStatement)`  in `CgCustomRenderer`.

2022-08-23 15:28 UTC, onewhl commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useCustomJavaDocTags by getBooleanProperty(false)
Added a ticket: https://github.com/UnitTestBot/UTBotJava/issues/774.
I'm not sure about moving it to UtSummarySettings, I think we should store all properties in one place.

2022-08-23 15:33 UTC, onewhl commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var useCustomJavaDocTags by getBooleanProperty(false)
We should keep it false for a while because there are no tags for fuzzer, and `useFuzzing` is true by default.
As we discussed with @amandelpie , first we merge this PR, then we add tags for fuzzer and add a settings about choosing the style of comments (custom tags/regular comments).

2022-08-23 19:40 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            for (i in 2 until children.size - 1) { // process all children except tag opening/closing elements
deleted this file after updating to idea 2022.1

2022-08-23 19:40 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                if (child is PsiDocToken && child.tokenType === JavaDocTokenType.DOC_COMMENT_LEADING_ASTERISKS) continue
deleted this file after updating to idea 2022.1

2022-08-23 19:40 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                        elementText.substring(0, pos + 1) // skip whitespace before leading asterisk
deleted this file after updating to idea 2022.1

2022-08-23 19:40 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        var offset = if (tagElements.isNotEmpty()) {
deleted this file after updating to idea 2022.1

2022-08-23 19:40 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +        val builder: StringBuilder = StringBuilder(javadoc)
deleted this file after updating to idea 2022.1

2022-08-23 19:41 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +                    element is PsiDocToken && element.tokenType !== JavaDocTokenType.DOC_COMMENT_LEADING_ASTERISKS
deleted this file after updating to idea 2022.1

2022-08-23 19:41 UTC, onewhl commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtJavaDocInfoGenerator.kt
> +            logger.info(e) { "Failed to find a reference while generating JavaDoc comment. Details: ${e.message}" }
deleted this file after updating to idea 2022.1

2022-08-24 12:14 UTC, amandelpie approved these changes

2022-08-24 12:16 UTC, merged

2022-08-24 13:00 UTC, onewhl commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
> +            traceTag.result.exceptionOrNull()?.let { it::class.qualifiedName }
thanks! you're right, I didn't notice it, I will fix it in separate PR