Add support for classes with hidden fields
UnitTestBot/UTBotJava pull request #592
Opened 2022-07-26 14:17 UTC by volivan239

# Description

Now if class has hidden fields, they can be recognized by engine and correct code for instantiation of such classes will be generated.

Fixes #563

## Type of Change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Switched `org.utbot.examples.objects.HiddenFieldExampleTest#testCheckSuccField` to enabled, added `org.utbot.examples.objects.HiddenFieldAccessModifiersTest`

## Manual Scenario 

Tested plugin on examples from #563 -- generates tests the way as expected.

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-07-28 13:57 UTC, CaelmBleidd requested changes

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
> +fun Class<*>.findDirectAccessedField(fieldName: String): Field? = generateSequence(this) { it.superclass }
Please, add documentation here. Especially about what 'directAccessed' means

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    override fun toString() = declaringClass.fieldOrNull(this).toString()
Why not `findField` anymore?

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        return null
Please, do not omit brackets for multiline constructions. Minor: redundant `this`

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        null
I believe, it is exception-dependent logic. Why you can't do it without throwing an exception? It is not a cheap operation after all. Moreover, please, add an empty line before the return

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
> +fun Class<*>.findDirectAccessedField(fieldName: String): Field? = generateSequence(this) { it.superclass }
Why it is not `orNull` anymore?

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        val realFieldDeclaringClass = typeRegistry.findRealType(field.declaringClass.type) as RefType
It is a declaringType

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        if (realFieldDeclaringClass.sootClass !in ancestors(realType.sootClass.id))
Please, do not omit brackets

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        if (realFieldDeclaringClass.sootClass !in ancestors(realType.sootClass.id))
Why do we always have such a field in ancestors?

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        val realFieldDeclaringClass = typeRegistry.findRealType(field.declaringClass.type) as RefType
Why did it work earlier? Please, add corresponding comment here with explanation and example

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +        val valuesFieldChunkId = hierarchy.chunkIdForField(utStringClass.type, utStringClass.valueField)
Are you sure? Why? 

Moreover, if it is true, do we write in this field in all other places in the wrapper? Not only in the resolver

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            else -> field.fieldId.field.let { it.withAccessibility { it.get(null) } }
Obviously, a problem with naming: `field.fieldId.field`

Moreover, now we have unused `declaringClass` variable

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt
> +                model.classId.fieldOrNull(field) ?: error("Can't find field: $field for $javaClass")
Returning back to the `fieldOrNull` implementation, here it looks like: 
`if we don't have a field, throw an exception. I'll catch it, return null and throw an exception once again`

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +            if (field != null && field.type.id == variableForField.type && fieldId.canBeSetIn(testClassPackageName)) {
@Damtev or @EgorkaKulikov, please, look over these changes with code generation

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DslUtil.kt
> +        CgFieldAccess(this, fieldId)
brackets

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/test/kotlin/org/utbot/examples/UtModelTestCaseChecker.kt
> +    protected fun UtModel.findField(fieldName: String, declarationClass: ClassId = this.classId): UtModel =
is `declaration` the right word?

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-sample/src/main/java/org/utbot/examples/objects/HiddenFieldSuccClass.java
> +    }
Isn't it a forgotten method implementation?

2022-07-28 13:57 UTC, CaelmBleidd commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt
> +            coverage = DoNotCalculate
Why?

2022-07-29 12:17 UTC, volivan239 commented on utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
> +fun Class<*>.findDirectAccessedField(fieldName: String): Field? = generateSequence(this) { it.superclass }
Added documentation for this method

2022-07-29 12:20 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    override fun toString() = declaringClass.fieldOrNull(this).toString()
Previously it was a method that was finding `Field` by its name. Now, when the `FieldId` is passed as argument, it is not really finding -- it's more like checking that this field belongs to this class and returning `Field`.

Renamed to `fieldByIdOrNull` for greater clarity

2022-07-29 12:20 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        return null
fixed

2022-07-29 12:21 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        null
fixed, although it's a little bit copy-pasted now

2022-07-29 12:22 UTC, volivan239 commented on utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
> +fun Class<*>.findDirectAccessedField(fieldName: String): Field? = generateSequence(this) { it.superclass }
Renamed to `findDirectAccessedFieldOrNull`

2022-07-29 12:24 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        val realFieldDeclaringClass = typeRegistry.findRealType(field.declaringClass.type) as RefType
Renamed to `realFieldDeclraingType`. Is "declaring type" a correct term?

2022-07-29 12:24 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        if (realFieldDeclaringClass.sootClass !in ancestors(realType.sootClass.id))
fixed here

2022-07-29 12:26 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        if (realFieldDeclaringClass.sootClass !in ancestors(realType.sootClass.id))
Are there other ways how field can belong to the class? At least, similar check was for `ancestorType` before these changes

2022-07-29 12:27 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            else -> field.fieldId.field.let { it.withAccessibility { it.get(null) } }
Just rewrote using `declaringClass`, seems better now

2022-07-29 12:29 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt
> +                model.classId.fieldOrNull(field) ?: error("Can't find field: $field for $javaClass")
Added same method without `orNull`, fixed

2022-07-29 12:29 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DslUtil.kt
> +        CgFieldAccess(this, fieldId)
fixed here

2022-07-29 12:29 UTC, volivan239 commented on utbot-framework/src/test/kotlin/org/utbot/examples/UtModelTestCaseChecker.kt
> +    protected fun UtModel.findField(fieldName: String, declarationClass: ClassId = this.classId): UtModel =
replaced with `declaring`

2022-07-29 14:08 UTC, volivan239 commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt
> +            coverage = DoNotCalculate
added coverage here and to `org.utbot.examples.objects.HiddenFieldExampleTest#testCheckSuccField`

2022-07-29 14:10 UTC, volivan239 commented on utbot-sample/src/main/java/org/utbot/examples/objects/HiddenFieldSuccClass.java
> +    }
This override really seems useless, removed it

2022-07-29 14:33 UTC, Damtev requested changes

2022-07-29 14:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +            if (field != null && field.type.id == variableForField.type && fieldId.canBeSetIn(testClassPackageName)) {
There are no functional changes, but I am a bit confused with this `TODO` removing. Are you sure it is resolved?

2022-07-29 14:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DslUtil.kt
> +    }
This functionality was just a shortcut for a `CgFieldAccess` constructor. I don't think we should use more complex logic with additional checks here.

Also, this logic does not always work - there is no check that `fieldId.declaringClass` is accessible, so there is possible situation with cast to a private class.

2022-07-29 14:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgKotlinRenderer.kt
> +        if (element.caller is CgTypeCast) print(")")
Why?

2022-07-29 14:53 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgKotlinRenderer.kt
> +        if (element.caller is CgTypeCast) print(")")
If lhs is typecast, we need brackets for correct priority. Without this, the generated code will be like `Succ as Super.f` and not `(Succ as Super).f`.

This is a little bit of a hack, but I didn't find more general solution.

2022-07-29 15:12 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgKotlinRenderer.kt
> +        if (element.caller is CgTypeCast) print(")")
This is definitely a hack, which is also not total - it does not cover similar cases for a method invocation and an array access. We need to find another solution.

2022-07-29 15:15 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/util/DslUtil.kt
> +    }
What is the best place to move this logic to? Before calling this there are checks that `fieldId` is accessible, aren't they enough?

Also, I believe that this logic should solve the removed TODO: it checks if we should use obj or declaring class as a caller. But maybe I misunderstood the TODO

2022-08-01 12:11 UTC, volivan239 commented
After discussion with @Damtev and @ArsenHD it was decided to merge into main only changes concerning engine (#627) so far. It was also decided to leave codegen untouched until @ArsenHD finishes his changes in codegen so we would have more rational ways of dealing with field hiding there.

2022-09-07 13:44 UTC, volivan239 commented
Corresponding issue was finally solved in #763, closing this one therefore.

2022-09-07 13:44 UTC, closed without merging