Summaries for tests generated by fuzzer are generated in the summary module #597
UnitTestBot/UTBotJava pull request #599
Opened 2022-07-27 15:27 UTC by amandelpie

# Description

1. Moved NameSuggesting API to summaries module
2. Shifted the stage of setting names/display names for fuzzing later, to the Summarization stage

Fixes #597 

## Type of Change

- Refactoring (typos and non-functional changes) 

# How Has This Been Tested?

## Automated Testing

TODO: add unit-tests for fuzzing tests and its names too

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-07-27 15:35 UTC, amandelpie commented
@Markoutte there is an open question how to pass information required to the Name generation outside the Fuzzer module.

I used UtExecution for that (adding two fields with types from Fuzzing module), but faced with some issues
1) class UtExecution is defined in Api.kt in utbot-framework-api and this module **doesn't import** fuzzer module (I don't know could I import it here?)
2) I could not **inherit** UtExecution (make FuzzingUtExecution and place it in utbot-framework or somewhere else) because it's a data class (the inheritance of data classes if forbidden in Kotlin). Could we convert it to usual class?

So I decided to keep something with types Any and fill these fields with specific types later in Java 4 style. I don't see huge objection not to follow this way

2022-07-28 06:18 UTC, Markoutte commented
I think we can do this trick like that: move the knowledge about data origin into the API or even another high-level module and unbind it from the fuzzer. I wouldn't move the knowledge about fuzzing (or any another possible way we generate names) to the summaries. But we can make a contract with a flex hierarchy of classes somewhere upper in module hierarchy (for example, one for those which have jimple body or which provide some internal knowledge about data origin).

I think, maybe, it is good idea to have something like "summary-api" or a package in framework-api for summaries. It gives us a way to choose how to fill this data for that summary. No summaries at all if we don't fill any.

Moreover it helps to merge the last 4 fields of UtExecution (createdBy, summary, testMethodName, displayName) into one object to pass further.  

What do you think?

2022-07-28 07:20 UTC, amandelpie commented
@Markoutte I'd like your proposal, and ready to try to implement this approach.

But I have an alternative suggestion: I have some tickets related to javadoc generation and clusterization for fuzzing and want to progress with them in parallel.

Could we merge this as it's implemented and start with depending tickets and in parallel start the discussion with team about changes in API?

2022-08-05 12:31 UTC, amandelpie commented
@Markoutte @denis-fokin please have a look, I've implemented the proposed hierarchy of classes and handle separately each case where Symbolic Execution and Fuzzed Execution have different flows.

Also, I checked this manually, fuzzing and symbolic works well together

2022-08-05 13:31 UTC, Damtev requested changes

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +            .filterIsInstance<UtSymbolicExecution>()
Why do we choose only among `UtSymbolicExecution`? Does it mean there will be no parametrized tests in case only the fuzzer is used for generating tests?

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +        genericExecution: UtSymbolicExecution,
Same about this concrete type

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +                for ((execIndex, execution) in testSet.executions.filterIsInstance<UtSymbolicExecution>().withIndex()) {
Same about filtering

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +            .filterIsInstance<UtSymbolicExecution>()
@EgorkaKulikov take a look here, please

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +            }
Same about `sealed`

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
Why do not we analyze `stateBefore` and `stateAfter` here? `UtFuzzedExecution` has them as `UtSymbolicExecution`

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
Same about analysis for `UtFuzzedExecution`

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
Same about `sealed`

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/EngineUtils.kt
> +fun UtSymbolicExecution.hasThisInstance(): Boolean = when {
Why it is not applicable for `UtFuzzedExecution`?

2022-08-05 13:31 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/sarif/SarifReport.kt
> +        return if (utExecution is UtSymbolicExecution) {
Could you use when with pattern-matching here (for possible future compile-time checks), please?

2022-08-05 13:31 UTC, Damtev commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> + * - required instrumentation details (such as randoms, time, static methods).
`UtFuzzedExecution` does not have an instrumentation

2022-08-05 13:31 UTC, Damtev commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> + * - the engine type that created this execution.
I guess we do not have this type anymore

2022-08-05 13:31 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> + * - the engine type that created this execution.
I guess we do not have this type anymore

2022-08-05 13:31 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +class UtSymbolicExecution(
Why not make this class a `data class`?

2022-08-05 13:31 UTC, Damtev commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> +class UtFuzzedExecution(
Same about `data class`

2022-08-05 13:31 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +                    null
Maybe `runCatching` is more suitable here

2022-08-05 13:31 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +                    nameSuggester.flatMap { it.suggest(utExecution.fuzzedMethodDescription as FuzzedMethodDescription, utExecution.fuzzingValues as List<FuzzedValue>, utExecution.result) }.firstOrNul
Is it true that this statement is throwable only in case `fuzzedMethodDescription` or `fuzzingValues` are null? If so, checking it instead of `try` construction looks more appropriate.

2022-08-05 13:31 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +        diversity = percentageDiverseExecutions(testSet.executions.filterIsInstance<UtSymbolicExecution>())
I guess, we can make this `filter` once and store it in a variable

2022-08-05 13:31 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +    val sootInvokes = testSet.executions.filterIsInstance<UtSymbolicExecution>().flatMap { it.path.invokeJimpleMethods() }.toSet()
As the such filter is used so often, perhaps it is better to make it as an extension function?

2022-08-08 05:57 UTC, Markoutte approved these changes
Fuzzing part and UtExecution looks good to me

2022-08-08 08:17 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +class UtSymbolicExecution(
it gives zero benefits, data modifier is good for isolated classes without inheritance

2022-08-08 08:18 UTC, amandelpie commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> +class UtFuzzedExecution(
it gives zero benefits, data modifier is good for isolated classes without inheritance

2022-08-08 08:21 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +open class UtExecution(
Agree it looks like a good candidate for sealed class hierarchy, but it's a specific situation: the UTExecution and UTSymbolicExecution is located in one module, but UTFuzzedExecution is in another module (included like a plugin)

It violates the usual technique for usage of sealed classes

From here: https://kotlinlang.org/docs/sealed-classes.html
Sealed classes and interfaces represent restricted class hierarchies that provide more control over inheritance. All direct subclasses of a sealed class are known at compile time. No other subclasses may appear outside a module within which the sealed class is defined.

2022-08-08 08:23 UTC, amandelpie commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +open class UtExecution(
IDEA said "Inheritance of sealed classes or interfaces from different module is prohibited"

2022-08-08 08:29 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +            .filterIsInstance<UtSymbolicExecution>()
I don't know guys, please help me to answer this question (I made some decisions based on debugging generated FuzzedExecutions for some cases and some decisions could be weird or wrong) @EgorkaKulikov

2022-08-08 08:33 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +        genericExecution: UtSymbolicExecution,
@EgorkaKulikov As I understand, execution generated by fuzzer don't visit this places

2022-08-08 08:34 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +                for ((execIndex, execution) in testSet.executions.filterIsInstance<UtSymbolicExecution>().withIndex()) {
@EgorkaKulikov As I understand, execution generated by fuzzer don't visit this places

2022-08-08 08:35 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
they are empty and has no information used here, internally in the analysis

2022-08-08 08:35 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
@Damtev @EgorkaKulikov

2022-08-08 08:35 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
they are empty and has no information used here, internally in the analysis

2022-08-08 08:39 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/util/EngineUtils.kt
> +fun UtSymbolicExecution.hasThisInstance(): Boolean = when {
@Markoutte correct me if I'm wrong, but FuzzedExecution is not communicated with this function

2022-08-08 08:40 UTC, amandelpie commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> + * - the engine type that created this execution.
Sorry, what type?

2022-08-08 08:50 UTC, amandelpie commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +                    null
I never used the runCatching earlier, but as I understand from docs, it's more suitable for the situation when we want to improve the try/finally section and handle something in the finally section

In the following PRs I'm going to rewrite logic in this place, probably the runCatching will be more suitable here in future

2022-08-08 08:52 UTC, amandelpie commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +        diversity = percentageDiverseExecutions(testSet.executions.filterIsInstance<UtSymbolicExecution>())
Agree

2022-08-08 08:53 UTC, amandelpie commented on utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
> +    val sootInvokes = testSet.executions.filterIsInstance<UtSymbolicExecution>().flatMap { it.path.invokeJimpleMethods() }.toSet()
It's a standard function from the library, and it's better give us the visual control, what's happened here.
Extension functions have their own advantages and disadvantages, but I'm trying to avoid them to hide the standard functions

2022-08-08 09:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/fields/ExecutionStateAnalyzer.kt
> +                return this
It is not obvious why are they always empty. Could you leave some comments about it, please?

2022-08-08 09:06 UTC, Damtev commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/UtFuzzedExecution.kt
> + * - the engine type that created this execution.
The engine type

2022-08-08 11:53 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +            .filterIsInstance<UtSymbolicExecution>()
I analyzed and extended this behaviour for the all UtExecutions, thanks @damtev

2022-08-08 11:54 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
> +        genericExecution: UtSymbolicExecution,
@Damtev Agree with you, experimented and extended to all UtExecutions

2022-08-08 11:56 UTC, amandelpie commented
@Damtev thanks for review, I solved the majority of the questions @EgorkaKulikov please have a look

2022-08-08 13:37 UTC, Damtev approved these changes

2022-08-08 13:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt
> +        if (execution is UtSymbolicExecution) {
Minor: `return if`

2022-08-08 13:58 UTC, EgorkaKulikov approved these changes

2022-08-08 14:29 UTC, merged