Make UtEnumConstModel and UtClassRefModel reference models #414
UnitTestBot/UTBotJava pull request #611
Opened 2022-07-29 13:47 UTC by dtim

# Description

Historically `UtEnumConstModel` and `UtClassRefModel` have been processed not as other reference models, but in a special way, more like to primitive types. This approach leads to several problems, especially to class cast errors when processing generic collections with enums or class references as elements.

This commit makes `UtEnumConstModel` and `UtClassRefModel` subtypes of `UtReferenceModel`.

  * Concrete executor is modified to respect the identity of static fields to avoid rewriting enum values and `Class<?>` instances.

  * Special processing for enums is implemented. When a new enum value is created, or an `Object` is being cast to the enum type, static values for the enum class are initialized, and the set of hard constraint is added to require that the new instance has the same address and ordinal as any one of enum constants to implement reference equality for enums.

  * Corresponding changes in fuzzer model providers have been implemented.

Note: anonymous nested classes associated with enum values are not fully supported yet.

Fixes #414 (meta-issue), #230, #300

## Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

All existing unit tests should pass.

New unit tests for enums have been added: `org.utbot.examples.enums.ComplexEnumExamplesTest`

Note: the test `org.utbot.examples.enums.ComplexEnumExamplesTest#testFindState` is currently disabled because of limited anonymous classes support.

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-01 12:53 UTC, Damtev requested changes
Logic LGTM, some issues about codestyle

2022-08-01 12:53 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    is UtNullModel -> 0
Could you link this constant with `org.utbot.engine.ResolverKt#NULL_ADDR` somehow, please?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt
> +                    val addr = model?.idOrNull() ?: throw IllegalStateException("Unsupported model: $model")
Perhaps it is better to introduce a new extension for `UtModel` that performs such action.

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
Why not `List` return type?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
Same about `List`

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        val allUpdates =  enumUpdates + createConcreteLocalValueUpdate(stmt, curFieldSymbolicValueForLocalVariable)
Redundant  ` `

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +    @Suppress("UnnecessaryVariable")
I guess this suppression is no longer applicable.

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        queuedSymbolicStateUpdates += mkOr(enumValueConstraints).asHardConstraint()
Why do we need one more `mkOr`?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt
> +                                    construct(computedValue, fieldId.type)
Could you please use curly braces here?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +            { a, b, c, r -> ((a == b && b != c) || (a != b && a == c)) && r == 2 },
`setOf(a, b, c).size == 2`?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +            { a, b, r -> ((a != null && b == null) || (a == null && b != null)) && r == 1 },
`(a == null) != (b == null)`?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +    @Disabled("TODO: Nested anonymous classes in enums do not work well yet")
Do we have an issue with it?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +            { cs, r -> cs.filter { it != null }.isNotEmpty() && r != null && Color.values().all { clr -> cs.count { it == clr } == (r[clr] ?: 0) } }
It is very difficult to read, could you break it into a few lines, please?

2022-08-01 12:53 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    }
Why do weed these overrides? It is a data class already

2022-08-01 12:53 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    }
Same about overrides

2022-08-01 12:53 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    override fun toString(): String = "$value@$id"
Are you sure about this `@` sign?

2022-08-01 12:53 UTC, Damtev commented on utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java
> +public class ComplexEnumExamples {
Same about curly braces for conditional expressions

2022-08-01 15:40 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
Sure, thank you.

2022-08-01 15:41 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt
> +    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
Fixed this as well.

2022-08-01 15:41 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        val allUpdates =  enumUpdates + createConcreteLocalValueUpdate(stmt, curFieldSymbolicValueForLocalVariable)
Fixed.

2022-08-01 15:46 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +    @Suppress("UnnecessaryVariable")
It is required as otherwise IDEA would suggest to get rid of `allUpdates`. It is easy to use a direct `return` here and in the next function (`makeConcreteUpdatesForNonEnumStaticField`), but I decided to keep the previous approach (it seems a bit more readable for me, although the difference is not so big). I can replace `allUpdates` with `return enumUpdates + ...` here if you think it would be better.

2022-08-01 15:47 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        queuedSymbolicStateUpdates += mkOr(enumValueConstraints).asHardConstraint()
We don't, thank you. I forgot to remove it when I last changed the code.

2022-08-01 15:47 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt
> +                                    construct(computedValue, fieldId.type)
Done.

2022-08-01 15:47 UTC, dtim commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +            { a, b, c, r -> ((a == b && b != c) || (a != b && a == c)) && r == 2 },
Yes, it seems better, thank you.

2022-08-01 15:49 UTC, dtim commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +    @Disabled("TODO: Nested anonymous classes in enums do not work well yet")
Yes, #617. I added a link to the issue to the comment.

2022-08-01 15:52 UTC, dtim commented on utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt
> +            { cs, r -> cs.filter { it != null }.isNotEmpty() && r != null && Color.values().all { clr -> cs.count { it == clr } == (r[clr] ?: 0) } }
I noticed an incorrect usage of `@NotNull` annotation on arrays in the Java code (my understanding of the `@NotNull` semantics was incomplete), so I rewrote the test a bit to make it correct again. Hope it's more clear now.

2022-08-01 15:53 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    }
Yes, it was an artifact left from an early version. Thank you, I removed it.

2022-08-01 15:53 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt
> +                    val addr = model?.idOrNull() ?: throw IllegalStateException("Unsupported model: $model")
I just meant an extension function like this:

```kotlin
fun UtModel.id(): Int = idOrNull() ?: throw IllegalStateException("Unsupported model: $this")
```

2022-08-01 15:55 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +    override fun toString(): String = "$value@$id"
I replaced ":" with "@" in both locations, as it seems more readable. I'd like to keep these `id` values for debugging, at least until related issues are fixed.

2022-08-01 15:55 UTC, dtim commented on utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java
> +public class ComplexEnumExamples {
Done.

2022-08-01 15:57 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +    @Suppress("UnnecessaryVariable")
Yeah, I see, it's my misunderstanding - I read not carefully and mixed up `UnnecessaryVariable` with `UNUSED_PARAMETER`. Keep it as it is, please.

2022-08-01 17:09 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt
> +                    val addr = model?.idOrNull() ?: throw IllegalStateException("Unsupported model: $model")
A solution that does not break smart casts: an extension function with a contract (thanks to @ArsenHD).

2022-08-02 11:12 UTC, Damtev approved these changes

2022-08-03 09:11 UTC, sergeypospelov approved these changes
The concrete part looks good to me.

2022-08-03 09:11 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/engine/symbolic/SymbolicStateUpdate.kt
> +import org.utbot.framework.plugin.api.classId
Looks like these imports are redundant.

2022-08-03 11:54 UTC, dtim commented
Updated `UtModelVisitor` and `FieldStateVisitor` to reflect model hierarchy change.

2022-08-04 07:01 UTC, Markoutte approved these changes

2022-08-04 09:31 UTC, Markoutte approved these changes

2022-08-04 12:08 UTC, merged