Fixed engine dealing with field hiding
UnitTestBot/UTBotJava pull request #627
Opened 2022-08-01 11:00 UTC by volivan239

# Description

Now if class has hidden fields, they can be recognized by engine and correct models are built.

Fixes engine part of #563

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Switched `org.utbot.examples.objects.HiddenFieldExampleTest#testCheckSuccField` to enabled, added `org.utbot.examples.objects.HiddenFieldAccessModifiersTest`

## Manual Scenario 

No manual scenario for testing this.

# Checklist (remove irrelevant options):

_This is the author self-check list_
- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-01 12:14 UTC, volivan239 commented
This PR is derived from #592. See this [comment](https://github.com/UnitTestBot/UTBotJava/pull/592#issuecomment-1201120069) for more details.

2022-08-01 12:27 UTC, volivan239 commented
Problems discovered in previous PR that were fixed but the fixes were not reviewed:

* Changes in `IdUtil.kt` (naming and logic)
* Naming problem in `Traverser.kt:642`

2022-08-02 11:08 UTC, Damtev requested changes

2022-08-02 11:08 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt
> +        // TODO: currently, codegen can't handle tests with field hiding
Create an issue and mention it here, please

2022-08-02 11:08 UTC, Damtev commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt
> +        // TODO: currently, codegen can't handle tests with field hiding
Same about issue

2022-08-02 14:52 UTC, dtim requested changes
Generally OK, but a fix in `UtAbstractStringBuilderWrapper.value()` needs correction.

As you fix only the engine part, I think it could be useful to create two separate issues, one for the engine, and another for the codegen ("children" of #563 and linked to it). That way you could reference (and close) the relevant issue and keep another issue open, and then close both the remaining issue and the parent issue with a second PR.

2022-08-02 14:52 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt
> +        val valuesFieldChunkId = hierarchy.chunkIdForField(utStringClass.type, utStringClass.valueField)
Replacement of `overriddenClass.valueField` with `utStringClass.valueField` seems incorrect, as we are dealing with `UtStringBuilder`/`UtStringBuffer` and not `UtString`. At the same time, the first argument `utStringClass.type` seems suspicious.

2022-08-02 14:52 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                val id = field.fieldId
This code seems not very clear, too many `id`s. Maybe rename `id` to a more descriptive name?

2022-08-02 14:52 UTC, dtim commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +    get() = safeField ?: error("Field $name is not found in class ${declaringClass.jClass.name}")
If we have a `ClassId.jClass`, maybe it would be consistent to rename `FieldId.field` to `FieldId.jField`?

2022-08-02 15:30 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +    get() = safeField ?: error("Field $name is not found in class ${declaringClass.jClass.name}")
done

2022-08-02 15:31 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt
> +        val realFieldDeclaringType = typeRegistry.findRealType(field.declaringClass.type) as RefType
The linked comment was actually resolved, so fixed now

2022-08-02 15:31 UTC, volivan239 commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt
> +        // TODO: currently, codegen can't handle tests with field hiding
done

2022-08-02 15:31 UTC, volivan239 commented on utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt
> +        // TODO: currently, codegen can't handle tests with field hiding
done

2022-08-02 15:32 UTC, volivan239 commented on utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
> + * when you write `${this.name}.$fieldName`.
This is a valuable comment, but I found out that this function is not even needed in this PR, so this is to be fixed in #592

2022-08-02 15:33 UTC, volivan239 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +    get() = safeField ?: error("Field $name is not found in class ${declaringClass.jClass.name}")
fixed

2022-08-02 16:31 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                jField.let { it.withAccessibility { it.get(null) } }
fixed

2022-08-02 16:33 UTC, volivan239 commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                val id = field.fieldId
replaced with `fieldId`

2022-08-03 06:12 UTC, dtim approved these changes
LGTM

2022-08-03 11:51 UTC, Damtev approved these changes

2022-08-03 15:02 UTC, merged