Prohibit to set static final fields from library classes #697
UnitTestBot/UTBotJava pull request #699
Opened 2022-08-10 09:42 UTC by sergeypospelov

# Description

- It's prohibited now to set static final fields from predefined library classes. This is done by filtering fields which are added to `meaningfulStaticFields` in `Traverser`.
- Also refactored `initializedStaticFields` field in `Memory`.

Fixes #697

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

**To reproduce** section from #697 works correctly.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] No new warnings
- [x] All tests pass locally with my changes

2022-08-10 12:05 UTC, Damtev requested changes

2022-08-10 12:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            !sunPackagesToProcessConcretely.any { field.declaringClass.packageName.startsWith(it) }
Maybe we can use `org.utbot.framework.TrustedLibraries#getTrustedLibraries` here?

2022-08-11 08:54 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +            !sunPackagesToProcessConcretely.any { field.declaringClass.packageName.startsWith(it) }
Didn't know about that, thank you.

2022-08-12 11:50 UTC, CaelmBleidd approved these changes
LGTM

2022-08-12 11:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                !ignoreStaticsFromTrustedLibraries || !field.declaringClass.isFromTrustedLibrary()
I think it is better to rewrite with conjunction to avoid several negations

2022-08-12 11:50 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        // fields from predefined library classes are excluded, because there are not meaningful
It is better to explain somewhere what you mean `meaningful`

2022-08-12 12:39 UTC, dtim approved these changes
I agree with comments by @CaelmBleidd (especially w.r.t. condition readability in `isStaticFieldMeaningful`), but LGTM overall.

2022-08-15 11:19 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +                !ignoreStaticsFromTrustedLibraries || !field.declaringClass.isFromTrustedLibrary()
I agree, thank you.

2022-08-15 11:19 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        // fields from predefined library classes are excluded, because there are not meaningful
OK, thank you.

2022-08-15 13:49 UTC, merged