Night Statistics Monitoring
UnitTestBot/UTBotJava pull request #701
Opened 2022-08-10 10:06 UTC by SBOne-Kenobi

# Description

## Problem
We want to develop and improve our product and, of course, there are some changes and its combinations which, according to some statistics, can make UTBot worse.

## Solution
The main idea is collecting statistics after made changes. But it takes too long to collect statistics on a huge project to do it after each push into master. Thus, we will do it every night when no one makes changes. Also we need to visualize collected statistics to easily analyze them. 

Look at docs/NightStatisticsMonitoring.md for more information.

### Coverage
I decided to collect coverage information using our ConcreteExecutor and I've provided total instructions count from tested class.

Fixes #700 

## Type of Change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Manual Scenario 

Created cloned repository and run github action. Also run each script with different parameters.

# Checklist:

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered

2022-08-12 10:25 UTC, sergeypospelov requested changes
PR looks really nice, can't wait to try it out. There are just some minor things. Also here some thoughts about possible enhancements:
- What about adding `usedConcreteExecutors` field in the future? 😊
- Maybe in the future we could write an interface to extend statistics with a custom statistic produced from `UtExecution`?
- What about adding a special file from which the `StatisticsMonitoringKt::main` takes arguments? It could be useful for defining custom monitorings without modifying .yml file.

2022-08-12 10:25 UTC, sergeypospelov commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
> +    var concolicCoverage: Coverage? = null
Do we really need to have `Coverage` here as lists? Maybe it's OK to have only sets here?

2022-08-12 10:46 UTC, sergeypospelov commented on utbot-junit-contest/src/main/kotlin/org/utbot/monitoring/StatisticsMonitoring.kt
> +    val timeLimit = 20
Why did we hardcode it?

2022-08-12 11:51 UTC, SBOne-Kenobi commented on utbot-junit-contest/src/main/kotlin/org/utbot/monitoring/StatisticsMonitoring.kt
> +    projectFilter = listOf("guava")
No, I decided to collect statistics from only one project witch is used by me to test features. You, of course, can change it.

2022-08-12 11:58 UTC, SBOne-Kenobi commented on docs/NightStatisticsMonitoring.md
> +Input arguments: `<history file> <new stats file> <output coverage graph> <output quantitative graph>`.
My mistake, I use our repository as database for statistics history. Format: json array of objects with statistics.

2022-08-12 12:00 UTC, SBOne-Kenobi commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
> +    var concolicCoverage: Coverage? = null
You are right, I decided to reuse `Coverage` class to don't create one more "Coverage".

2022-08-12 15:50 UTC, victoriafomina commented on monitoring/draw_stats_graphs.py
> +        raise FileNotFoundError("File with new stats not exists!")
does not exist :)

2022-08-15 08:13 UTC, denis-fokin commented on monitoring/draw_stats_graphs.py
> +DPI = 108
Could you add some clarification on these parameters? If them are parameters for some known library, please add a reference to the documentation.

2022-08-15 08:44 UTC, denis-fokin commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> -    // Doesn't work
If the code does not work, why we include it into the change?

2022-08-15 08:50 UTC, SBOne-Kenobi commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
> -    // Doesn't work
I just deleted an irrelevant and useless comment.

2022-08-15 08:55 UTC, denis-fokin commented on utbot-junit-contest/build.gradle
> +    archiveName 'monitoring.jar'
What about moving the value in gradle.properties?

2022-08-15 10:18 UTC, SBOne-Kenobi commented on utbot-junit-contest/build.gradle
> +    archiveName 'monitoring.jar'
I think that name of jar file doesn't match to global information in gradle.properties.

2022-08-15 10:45 UTC, denis-fokin commented
There are some suggestions on the approach to gather and store the statistics.

### Where to store
It is better to store the statistical data in a separate branch or even repository. This way we can update the data without any harm to the `main` branch.

### Metadata
Currently, there is not enough metadata for further data processing. Assuming, we store data in a separate repository or branch we may need the next data:

- commit hash
- build number
- environment

### Images
Maybe our way of the results representation is not the best, so we should not stick to the particular images. Images are still useful for brief insight into the specific data, but they should not be stored as bitmap images. It is better to choose some vector format.

The way of representation of overall data with a single picture is a separate challenge. By the way, an independent repository will help us with refining the images.

### Data processing
Eventually, it is great to have only data in the repository. There are several solutions on the data postprocessing:

- script in the repository
- service that is able to process the data and build visual representation of it

### Granularity
We need to choose a smallest piece of information that we want to represent in our statistics. It seems reasonable to use a test as such an atomic measure. A common scenario that a user can run into is a change of generated tests number. This will lead to the change of the results. In such situations it is good to see the reason right from the statistical data.

### Third party solutions
We can take a look at other's solutions:

2022-08-18 12:33 UTC, sergeypospelov commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
> +} ?: CoverageStatistic(covered = 0, total = 0)
Still can't determine if it includes anonymous, nested, inner classes or not.

2022-08-18 12:38 UTC, SBOne-Kenobi commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
> +} ?: CoverageStatistic(covered = 0, total = 0)
Coverage from concrete executor doesn't calculate total instructions count from nested or inner classes. But we want to collect coverage in CoverageStatistic including them (that's a specific of ContestEstimator).

2022-08-18 12:49 UTC, sergeypospelov commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
> +} ?: CoverageStatistic(covered = 0, total = 0)
I mean, why didn't you add comments on that?

2022-08-22 09:39 UTC, victoriafomina commented on .github/workflows/night-statistics-monitoring.yml
> +        with:
It's better to run everything in the container as it'd give us the environment reproducible locally:
```
    runs-on: ubuntu-20.04
    container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
    steps:
```

In this case KOTLIN_HOME env must be removed as it's already set up in the container

2022-08-29 12:46 UTC, denis-fokin commented on monitoring/build_aggregated_data.py
> +def get_file_seq(input_data_dir):
Can we add type annotations?

2022-08-29 14:03 UTC, denis-fokin approved these changes

2022-08-30 06:09 UTC, merged