Mutate values to improve code coverage #213
UnitTestBot/UTBotJava pull request #713
Opened 2022-08-11 13:57 UTC by Markoutte

# Description

This commit adds a mutation mechanism to the fuzzing for improving code coverage by applying random mutations for numbers and strings.

Fixes #213

## Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Manual Scenario 

Turn on only fuzzing mode. These examples can find (usually do for default utbot settings):

1. Should find the string that starts with prefix "bad!"

```java
public static void test(String s) {
    if (s.charAt(0) == "b".charAt(0)) {
        if (s.charAt(1) == "a".charAt(0)) {
            if (s.charAt(2) == "d".charAt(0)) {
                if (s.charAt(3) == "!".charAt(0)) {
                    throw new IllegalArgumentException();
                }
            }
        }
    }
}
```

2. Should find a string that has "!" in the 5-th position, but can totally change the other part.

```java
public static void testStrRem(String str) {
    if (!"world???".equals(str) && str.charAt(5) == '!' && str.length() == 6) {
        throw new RuntimeException();
    }
}
```

3. Should find the value that will return 2 for the method:

```java
public int floatToInt(float x) {
    if (x < 0) {
        if ((int) x < 0) {
            return 1;
        }
        return 2; // smth small to int zero
    }
    return 3;
}
```

If results are failed try to increase test generation time.

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-12 15:17 UTC, CaelmBleidd requested changes

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +    ): FuzzedValue? {
Could be with an expression body

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +        val position = random.nextInt(string.length + 1)
Why can the position be greater than the last index? Is it to add the possibility of not removing a char? If so, could you add a comment about it, please?

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +            random.nextInt(1, 65536).toChar()
Shouldn't it be from zero until `Short.MAX_VALUE + 1`?

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +            value[random.nextInt(value.length)]
`value.random()`?

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +                append(charToMutate - random.nextInt(1, 128))
What `128` means here?

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +        if (value.isEmpty() || position >= value.length) return null
could be just `position >= value.length`

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
> +fun defaultMutators(): List<ModelMutator> = listOf(StringRandomMutator(50), NumberRandomMutator(50))
constants without names

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/ModelMutator.kt
> +        return parameters.mapIndexed { index, fuzzedValue ->
here and in other functions expression body might be used

2022-08-12 15:17 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/ModelMutator.kt
> +        return if (random.nextInt(1, 101) < probability) value else null
`random.nextInt(1, 101) < probability` used in many places. May you create a function for it?

2022-08-16 10:26 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        val frequencyRandom = FrequencyRandom(Random(221))
It shouldn't because its a random seed for a Random. No difference to fuzzing if value is changed.

2022-08-16 10:32 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        val factor = maxOf(0, UtSettings.fuzzingRandomMutationsFactor)
For me it hides the value when variable name is long:

```kotlin
var onlyPositiveValue = theRandomValuedRetrievedFromFile.coearceAtLeast(0)
```

and 

```kotlin
var onlyPositiveValue = maxOf(0, theRandomValuedRetrievedFromFile)
```

But I don't have any preferable way here.

2022-08-22 10:56 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +        val position = random.nextInt(string.length + 1)
In case the only insertion is done for any string of n length it is n + 1 positions to insert. For a simple example of size 1 a new character can be inserted before or after the string value.

2022-08-22 14:01 UTC, CaelmBleidd approved these changes
overall lgtm

2022-08-22 14:01 UTC, CaelmBleidd commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
> +            value[random.nextInt(value.length)]
value.random(random)?

2022-08-24 06:44 UTC, merged