Add unit tests for builders #543
UnitTestBot/UTBotJava pull request #734
Opened 2022-08-17 10:37 UTC by onewhl

# Description

Added unit tests for SimpleNameBuilder, SimpleCommentBuilder, SimpleClusterCommentBuilder.
Unfortunately, most of the methods are private and kotlin properties not always could be mocked, so the number of tests is small.

Fixes #543 

## Type of Change

Please delete options that are not relevant.

- New tests

# How Has This Been Tested?

## Automated Testing

Run tests in PR.

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

2022-08-17 12:43 UTC, amandelpie requested changes
It's a good question, should we test private methods or not, I suggest to use reflection or change the visibility of a few methods to the package-private or internal and test private methods without mockito but after moving from Soot to JCDB

If you wish, you could play with changing visibility at this PR for 1-2 method for the SimpleNameBuilder

Please add a few tests if possible and fix the issue with the mockito verision

2022-08-17 12:43 UTC, amandelpie commented on utbot-summary/build.gradle
> +    testImplementation 'org.mockito:mockito-core:4.7.0'
There are a few mockito versions in the framework, to have less, I suggest to make the same thing like in the testImplementation below  `testImplementation("org.junit.jupiter:junit-jupiter:$junit5_version")` using $mockito_version, please search in the project

2022-08-17 12:43 UTC, amandelpie commented on utbot-summary/src/test/kotlin/org/utbot/summary/comment/SimpleClusterCommentBuilderTest.kt
> +    fun `throws throwable if execution result is null`() {
This test fails on my side with 
```
expected: <<pre>
Test throws Throwable 
</pre>> but was: < >
```

2022-08-17 12:43 UTC, amandelpie commented on utbot-summary/src/test/kotlin/org/utbot/summary/comment/SimpleClusterCommentBuilderTest.kt
> +class SimpleClusterCommentBuilderTest {
Could we add a few tests to cover the following method:
- buildDocStmts

2022-08-17 12:43 UTC, amandelpie commented on utbot-summary/src/test/kotlin/org/utbot/summary/comment/SimpleCommentBuilderTest.kt
> +class SimpleCommentBuilderTest {
Could we add a few tests to cover the following method:

- buildDocStmts

2022-08-17 13:28 UTC, onewhl commented on utbot-summary/build.gradle
> +    testImplementation 'org.mockito:mockito-core:4.7.0'
I fixed it, thank you!

2022-08-17 13:29 UTC, onewhl commented on utbot-summary/src/test/kotlin/org/utbot/summary/comment/SimpleClusterCommentBuilderTest.kt
> +    fun `throws throwable if execution result is null`() {
i didn't expect these two builders have different behavior, but now we know. I fixed test

2022-08-18 08:29 UTC, amandelpie commented
@onewhl LGTM for me

2022-08-18 08:31 UTC, amandelpie approved these changes

2022-08-18 08:32 UTC, merged