Rd-gen
UnitTestBot/UTBotJava pull request #748
Opened 2022-08-19 15:25 UTC by Domonion

# Description

Moved child process communication to RD. Added ability to track process through JetBrains.Lifetimes. Refactored ConcreteExecutor to support JetBrains.Lifetimes and RD

1. switched from Protocol.Command to rd generated model
2. added utbot-rd project featuring LifetimedProcess, ProcessWithRdServer and minor rd-related utility classes
3. Switched from message-driven ConcreteExecutor to callback rd model, featuring UtInstrumentationProcess

## Type of Change

Please delete options that are not relevant.

- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)

## Automated Testing

org.utbot.examples.collections.ListsTest
org.utbot.examples.collections.MapsTest
org.utbot.external.api.UtBotJavaApi
org.utbot.examples.exceptions.JvmCrashExamplesTest
All tests should work

2022-08-22 17:02 UTC, korifey commented on utbot-analytics/build.gradle
> +    zip64 = true
why?

2022-08-23 10:11 UTC, Domonion commented on utbot-analytics/build.gradle
> +    zip64 = true
> Execution failed for task ':utbot-analytics:jar'.
> > archive contains more than 65535 entries.
Without this flag gradle cannot build it

2022-08-23 10:54 UTC, SBOne-Kenobi requested changes
Formatting questions

I hope that you will write one or several docs or at least a brief description in the PR about:
- How communication between child and main processes works
- How to support new commands, some requirements and tips for this
- A brief description about ChildProcess structure and workflow
- A brief description about rdgen builds

2022-08-23 10:54 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/ChildProcessRunner.kt
> +        val processBuilder = ProcessBuilder(cmds + " " + portArgument).redirectError(errorLogFile).directory(directory)
Empty argument (`" "`) is needed?

2022-08-23 10:54 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/ChildProcess.kt
> +            if (start > end) { // process is doing something
Could you use conditions and mutexes for waiting?

2022-08-23 10:54 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/ChildProcess.kt
> +                    delay(1000)
Magic number

2022-08-23 10:54 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/ChildProcess.kt
> +    protocolModel.warmup.set { _ ->
Can you carry out method with setting up commands for protocol model?

2022-08-23 10:54 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/ConcreteExecutor.kt
> +    suspend fun <T> withProcess(exclusively: Boolean = false, block: suspend UtInstrumentationProcess.() -> T): T {
Provide description

2022-08-29 09:12 UTC, SBOne-Kenobi commented on utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/process/ChildProcess.kt
> +private const val messageFromMainTimeoutMillis: Long = 120 * 1000
Magic constant `1000`, TimeUnit.Seconds.toMillis may help

2022-08-29 14:44 UTC, SBOne-Kenobi approved these changes

2022-08-30 09:47 UTC, merged