Enhance fuzzing for arrays #738
UnitTestBot/UTBotJava pull request #755
Opened 2022-08-22 11:09 UTC by volivan239

# Description

Now, `ArrayModelProvider` generates more interesting tests:

* small-sized arrays with "interesting" size and filled with default values ("interesting" means that this number is obtained from source code)
* arrays of small fixed size, each element is generated recursively by fuzzing synthetic method.

Fixes #738

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Manual Scenario 

Generate tests for methods from `ArrayExample` class (using only fuzzer):

```Java
class Point {
    int x, y;

    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    boolean equals(Point other) {
        return (other.x == this.x && other.y == this.y);
    }
}

public class ArrayExample {
    boolean checkAllSame(Integer[] a) {    // Fuzzer should find parameters giving true as well as parameters giving false
        Set<Integer> s = new HashSet<>(Arrays.asList(a));
        return (s.size() <= 1);
    }

    public boolean checkAllSamePoints(Point[] a) { // Also works for classes
        if (a.length == 4) {
            return false; // Test with array of size 4 should be generated by fuzzer
        }
        for (int i = 1; i < a.length; i++) {
            if (!a[i].equals(a[i - 1]))
                return false;
        }
        return true;
    }

    public boolean checkRowsWithAllSame2D(int[][] a, int y) {
        int cntSame = 0;
        for (int i = 0; i < a.length; i++) {
            boolean same = true;
            for (int j = 1; j < a[i].length; j++) {
                if (a[i][j] != a[i][j - 1]) {
                    same = false;
                    break;
                }
            }
            if (same)
                cntSame++;
        }
        return (cntSame == y);
    }
}
```

For each of them, meaningful tests are generated that cover both true/false outputs.

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-23 12:02 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ObjectModelProvider.kt
> +            1 -> Int.MAX_VALUE
The logic looks different: before when recursion is 1, 2, 3 and so on then limit is 1. Now it is harder to understand what's happening. The idea behind this was that the limit is articulated as: when we find constructors that accepts another objects then we construct them, but use no more than one available constructor. If recursion is 0, than we pass null to every object parameter in constructor. But usually, we look for constructors with primitive values.

2022-08-23 12:07 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +    var modelProviderForRecursiveCalls: ModelProvider =
Looks like we have lost an ability to change model providers for ObjectModelProvider, because before the changed model provider is passed into recursive call. Now, it uses only default providers.

2022-08-23 12:18 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ArrayModelProvider.kt
> +    private fun generateArrayLengths(description: FuzzedMethodDescription): Set<Int> {
Looks like this can be simplified. It is too much work to generate some values in interval from 0 up to 10

2022-08-23 12:21 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ObjectModelProvider.kt
> +    // TODO: can we make it private val (maybe depending on recursion)?
It is manual option and a part of public API

2022-08-23 12:22 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +    // TODO: currently it is var due to tests, maybe we can make it private val?
It was a part of public API to change a set of model providers. Currently, it looks broken

2022-08-23 12:22 UTC, Markoutte requested changes
Please, look at comments

2022-08-29 05:55 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +    val createModel: (List<FuzzedValue>) -> FuzzedValue
You can use notation like this:

```kotlin
 val createModel: (inputs: List<FuzzedValue>) -> FuzzedValue
```
to clarify name for parameter. Also, doc will be very useful here

2022-08-29 06:38 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +                        modelProviderForRecursiveCalls = this@RecursiveModelProvider.modelProviderForRecursiveCalls
Why don't we copy all these values in the `copy` method? It looks better as we want to get a copy of this provider. Here we can leave values that should be changed like totalLimit (but in copy it should be copied, I think)

2022-08-29 06:44 UTC, Markoutte commented on utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
> +    @Disabled
Test checks that Outer class is created using only one constructor from the inner and it is the simplest one. I think we should keep this behavior for ObjectModelProvider

2022-08-29 06:44 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +abstract class RecursiveModelProvider(
Please, add docs

2022-08-29 07:27 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
> +        nonRecursiveProviders(idGenerator).with(recursiveModelProviders(idGenerator, recursionDepth))
Note, that the other method called 'defaultModelProviders' without parameter with recursion has another set of model providers. Therefore. I'd recommend to change name for this method to avoid ambiguous calls.

2022-08-29 07:28 UTC, Markoutte requested changes
Please, see comments

2022-08-29 16:05 UTC, volivan239 commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +    val createModel: (List<FuzzedValue>) -> FuzzedValue
Added name for parameters. Also, added docs here and in other places where needed

2022-08-29 16:06 UTC, volivan239 commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
> +                        modelProviderForRecursiveCalls = this@RecursiveModelProvider.modelProviderForRecursiveCalls
Renamed to `createNewInstance` for more clarity

2022-08-29 16:06 UTC, volivan239 commented on utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
> +    @Disabled
Returned this behavior back

2022-08-29 16:11 UTC, volivan239 commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
> +        nonRecursiveProviders(idGenerator).with(recursiveModelProviders(idGenerator, recursionDepth))
This method should have replaced the method without `recursionDepth` parameter with no changes in behavior when this parameter is not specified. Seems like I accidently got duplication after rebase. Deleted method without parameter now. Could you please check that it didn't change the behavior?

2022-08-30 05:51 UTC, Markoutte commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
> +        nonRecursiveProviders(idGenerator).with(recursiveModelProviders(idGenerator, recursionDepth))
It changes because `PrimitivesModelProvider` isn't used anymore. By default I want to keep an ability to set different providers by default, because I usually want to use shallower value set for it. Right now this change is only about PrimitivesModelProvider, but in the future I'd want to add some providers that are used for generating flat parameters and aren't used for recursive.

2022-08-30 05:56 UTC, Markoutte requested changes
Looks good but let's discuss changes about `defaultModelProviders`

2022-08-30 11:38 UTC, Markoutte approved these changes

2022-08-30 12:01 UTC, merged