Support anonymous classes
UnitTestBot/UTBotJava pull request #760
Opened 2022-08-22 13:13 UTC by ArsenHD

# Description

This PR removes filters that prevented anonymous classes from being used. It also allows code generation to work with anonymous class instances. Not via reflection, but rather by storing these instances in variables of the anonymous class supertype. For example, instance of anonymous class implementing interface `Predicate` will be stored in a variable of type `Predicate`. If we have to access any fields of methods declared in anonymous class, it will be done through reflection, but all members of the supertype will be accessed directly.

This PR partly fixes issue #617. Now tests are generated, but there seems to be some problem with accessing enum constants that have corresponding anonymous classes, to be discussed.

## Type of Change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

TODO

## Manual Scenario 

Change was tested manually on example of code from issue #617. Tests are generated, but as said in the description, they are yet not fully correct. The exact problem is unclear. To be discussed.

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-24 13:48 UTC, Damtev requested changes
Could you please add some new tests (for example, with an anonymous class as a method result)?

2022-08-24 13:48 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        if (!isAnonymous) error("An anonymous class expected, but got $canonicalName")
`require` looks more suitable here

2022-08-24 13:48 UTC, Damtev commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +            }
Why not unite these two `when` branches into one with `if-else`?

2022-08-24 13:48 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +                else -> concreteTypes += it
I do not see what was changed except `heuristic` removal

2022-08-24 13:48 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/ConstructorUtils.kt
>      }
Could you not shadow an existing name?

2022-09-01 09:57 UTC, ArsenHD commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +        if (!isAnonymous) error("An anonymous class expected, but got $canonicalName")
[Done](https://github.com/UnitTestBot/UTBotJava/pull/760/commits/269303cbdcc4f3cab556c297f301d9cf7cc0c186)

2022-09-01 09:57 UTC, ArsenHD commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
> +            }
[Done](https://github.com/UnitTestBot/UTBotJava/pull/760/commits/0b0b0c3bce04c1742e2b1792884b2d76af9143ad)

2022-09-01 09:58 UTC, ArsenHD commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +                else -> concreteTypes += it
Now `sootClass.isAnonymous` condition is removed.

2022-09-01 09:59 UTC, ArsenHD commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/ConstructorUtils.kt
>      }
Done. Now this logic is moved to the `val ClassId.denotableType: ClassId` extension property in `IdUtil.kt` and the variable is renamed.

2022-09-01 10:31 UTC, ArsenHD commented
> Could you please add some new tests (for example, with an anonymous class as a method result)?

We already had tests on this. I [updated](https://github.com/UnitTestBot/UTBotJava/pull/760/commits/cecee725cbbf6fc53a70b77b1d3ea01e2d1d55e5) them according to my changes.

2022-09-15 13:13 UTC, merged