Support hidden fields in code generation
UnitTestBot/UTBotJava pull request #763
Opened 2022-08-22 14:45 UTC by ArsenHD

# Description

This PR fixes issue #646. Hidden fields have been supported in the engine by @volivan239 . This PR adds support for them on the code generation side.

Let's consider an example. We have `class A { int x; }` and `class B extends A { int x; }`. These fields `x` have the same name, but they are __different__ fields. Let's say we have a variable (of type `A` or `B`) and we want to access field `x` (from class `A` or `B`). There are 4 cases:
- Variable of type `A` accessing `x` of type `A`. Here field can be accessed directly.
- Variable of type `A` accessing `x` of type `B`. Here we need a cast to type `B` and then we are able to access the field.
- Variable of type `B` accessing `x` of type `A`. Here we also need a cast, but to type `A`.
- Variable of type `B` accessing `x` of type `B`. Here field can be accessed directly.

This logic is now implemented in `CgCallableAccessManagerImpl`. This class checks if we can call a method with the given arguments and if we can access a field using the given object. Previously, there were no checks for fields, only for methods. Now we check field for accessibility. There are 3 cases:
- Field can be accessed directly (`myObj.field`)
- Field can be accessed with type cast (`((MyClass) myObj).field`)
- Field can only be accessed via reflection (e.g. private fields)

## Type of Change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

These tests check the hidden fields functionality.

`org.utbot.examples.objects.HiddenFieldAccessModifiersTest`
`org.utbot.examples.objects.HiddenFieldExampleTest`

## Manual Scenario 

TODO

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-09-01 12:33 UTC, Damtev requested changes
A problem with RequiresTypeCast?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +        return CgStaticFieldAccess(fieldId)
Minor: Maybe use expression body here?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +        return when {
Minor: Maybe use expression body here?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            require(caller == null) { "Caller expression of a static method call must be null" }
Caller is not always null - we can invoke static methods with instance in Java

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            require(accessor == null) { "Accessor expression of a static field access must be null" }
Accessor is not always null - we can access static fields with instance in Java

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            // because they are well known library classes (e.g. Mockito) that are unlikely to have hidden fields.
Could you move this comment after 361 line, please?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +            if (fieldName.isNameOfFieldsInBothClasses(accessorType, fieldDeclaringClassType)) {
Looks like it does not work - for example, field "x" in private inheritor of some class "A" would be declared with `Object` type, and we will return `Suitable` here which is wrong

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +            Class::class.id[forName](classId.name)
`classClassId`

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +        val declaringClass = newVar(Class::class.id) { Class::class.id[forName](fieldId.declaringClass.name) }
`classClassId`

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +        return newVar(java.lang.reflect.Field::class.id, name) {
`fieldClassId`?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +        val declaringClass = newVar(Class::class.id) { Class::class.id[forName](executableId.classId.name) }
`classClassId`

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +                    Class::class.id[forName](parameterType.name)
`classClassId`

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +                newVar(java.lang.reflect.Method::class.id, name) {
`methodClassId`?

2022-09-01 12:33 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/util/CgStatementConstructor.kt
> +                newVar(java.lang.reflect.Constructor::class.id, name) {
`constructorClassId`?

2022-09-07 09:18 UTC, Damtev requested changes

2022-09-07 10:17 UTC, ArsenHD commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
> +    private infix fun FieldId.isFieldHiddenIn(subclass: Class<*>): Boolean {
[Done](https://github.com/UnitTestBot/UTBotJava/pull/763/commits/caba5d10a165006873c0c7734a1878038a9910d1)

2022-09-07 10:20 UTC, Damtev approved these changes

2022-09-07 10:44 UTC, merged