Updated gradle configuration
UnitTestBot/UTBotJava pull request #764
Opened 2022-08-23 09:18 UTC by Markoutte

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-24 12:19 UTC, amandelpie requested changes

2022-08-24 12:19 UTC, amandelpie commented on utbot-analytics/build.gradle
> -compileKotlin.dependsOn project(':utbot-instrumentation').tasks.jar
looks great

2022-08-24 12:19 UTC, amandelpie commented on utbot-summary/build.gradle
> -
Could you please remove repeated dependencies 

    api(project(':utbot-instrumentation'))
    implementation group: 'com.github.haifengl', name: 'smile-kotlin', version: '2.6.0'
    implementation group: 'com.github.haifengl', name: 'smile-core', version: '2.6.0'

2022-08-26 08:08 UTC, denis-fokin approved these changes

2022-08-26 08:20 UTC, denis-fokin approved these changes

2022-08-26 08:26 UTC, merged