#70 Fix wrong test resources directory in Android Studio
UnitTestBot/UTBotJava pull request #78
Opened 2022-05-30 16:19 UTC by IdeaSeeker

2022-05-31 08:20 UTC, EgorkaKulikov requested changes

2022-05-31 08:20 UTC, EgorkaKulikov commented on utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/utils/RootUtils.kt
> +fun SourceFolder.isInBuildGeneratedFolder(): Boolean {
I suggest to create extension method `JavaSourceRootProperties.isAndroidStudioGeneratedSources` instead of your method in lines 54-58 and check not only that the path contains "build/generated", but also that your current IDE is Android Studio. And could you mention in method documentation that standart property has false value in Android Studio, so we need to create such hack.

2022-06-02 16:20 UTC, denis-fokin commented
Please, provide a PR description.

2022-06-06 14:30 UTC, EgorkaKulikov requested changes

2022-06-07 09:19 UTC, nikitavlaev approved these changes

2022-06-07 09:22 UTC, merged