Minor refactoring in SimpleCommentBuildr and CustomJavaDocCommentBuilder
UnitTestBot/UTBotJava pull request #788
Opened 2022-08-24 15:14 UTC by onewhl

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-08-25 09:33 UTC, Damtev requested changes

2022-08-25 09:33 UTC, Damtev commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
>          }
I guess, it could be a little simplified:

```kotlin
if (thrownException != null) {
    val exceptionName = thrownException.javaClass.name
    val reason = findExceptionReason(currentMethod, thrownException)

    customJavaDocComment.throwsException = "{@link $exceptionName} $reason"
}
```

2022-08-26 12:04 UTC, onewhl commented on utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
>          }
I agree, thanks!

2022-08-26 13:30 UTC, Damtev approved these changes

2022-08-29 08:34 UTC, merged