Support lambda expressions
UnitTestBot/UTBotJava pull request #825
Opened 2022-08-30 17:31 UTC by ArsenHD

# Description

Substitute this text with a concise description of the proposed change. Emphasize, why particular solution was chosen.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)
- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

2022-09-02 16:49 UTC, Damtev requested changes

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/lambda/LambdaConstructionUtils.kt
> +    val lambdaMethodType = MethodType.methodType(lambdaMethod.returnType, lambdaMethod.parameterTypes)
Create a class for this code with restructuring, please

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt
> +        val created = createObject(addr, classType, useConcreteType = true, mockInfoGenerator)
By mistake?

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +                    }
Fix this method, please

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +        return TypeStorage(type, concretePossibleTypes)//.filterInappropriateClassesForCodeGeneration()
Uncomment?

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
> +        return TypeStorage(type, possibleTypes)//.filterInappropriateClassesForCodeGeneration()
Uncomment?

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +//                }
Remove?

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +//                }
Remove?

2022-09-02 16:49 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/UtilMethods.kt
> +): Result<String> = runCatching {
Remove `Result` here and throw an error here, please

Also, please create a task for isolation of rendering test method and link it here

2022-09-03 19:21 UTC, ArsenHD commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
> +// TODO: what about support for Kotlin lambdas (they are not exactly the same as Java's due to functional types)
https://github.com/UnitTestBot/UTBotJava/issues/852

2022-09-03 19:34 UTC, ArsenHD commented on utbot-framework/src/main/kotlin/org/utbot/engine/util/lambda/LambdaConstructionUtils.kt
> +        .drop(capturedArgumentTypes.size)
Turns out `lambdaMethod.parameterTypes` is an array, so there is no way to obtain a view on some portion of it. That's why we will have to leave it like that.

2022-09-03 20:26 UTC, ArsenHD commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/UtilMethods.kt
> +): Result<String> = runCatching {
Done. Here's the [taks](https://github.com/UnitTestBot/UTBotJava/issues/853)

2022-09-18 16:53 UTC, Damtev approved these changes
LGTM

2022-09-18 16:53 UTC, merged