Primitive Stream wrappers (no laziness and source mutations support)
UnitTestBot/UTBotJava pull request #871
Opened 2022-09-07 11:55 UTC by Damtev

Adds wrappers for primitive Streams as #548 does, but does not reflect lazy behavior and does not support stream's source mutations as default Java Streams do. 

Fixes #146.

2022-09-25 11:10 UTC, CaelmBleidd requested changes

2022-09-25 11:10 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/collections/Collection.java
> +        return stream();
Shouldn't we have `stream` with `isParallel = true` here?

2022-09-25 11:10 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/Arrays.java
> +        if (startInclusive < 0 || endExclusive < startInclusive || endExclusive > size) {
It should be `if (startInclusive < 0 || endExclusive <= startInclusive || endExclusive > size) {`, shouldn't it?

2022-09-25 11:10 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +        assume(data.length == elementData.end);
Why do we need it? If it is really required now, there is a bug here

2022-09-25 11:10 UTC, CaelmBleidd commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +    @Disabled("TODO UtArrayApplyForAll translation error https://github.com/UnitTestBot/UTBotJava/issues/630")
This one is already fixed

2022-09-26 08:34 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/DoubleStream.java
> +        }
Because there is no implementation for `double[]` source and `Double[]` destination.

2022-09-26 08:43 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/LongStream.java
> +        Long[] data = new Long[size];
Because primitive streams cannot store primitive arrays - they need to store an array of objects because a primitive stream could be created from any collection, for example, a list of strings.

2022-09-26 08:54 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +        // as mapper can produce infinite streams, we cannot process it symbolically
Actually, an infinite stream may be produced by one of the following methods: `generate`, `iterate`, and correspondingly `concat`. So, the passed `mapper` may use one of these functions and accordingly create an infinite stream. 

As you can see, there are no more methods that use such functions, so none of them may create an infinite stream.

2022-09-26 08:58 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +                    Double tmp = sortedElements[j];
It might be, but it is unnecessary. It will just add additional wrap/unwrap actions.

2022-09-26 09:07 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +        return result == null ? OptionalDouble.empty() : OptionalDouble.of(result);
There cannot be a function that produces `null` because `DoubleBinaryOperator` produces a primitive `double`.

2022-09-26 10:37 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/StreamWrappers.kt
> +        val parametersArrayModel = resolveElementsAsArrayModel(wrapper)?.transformElementsModel()
Yes, to transform array of wrappers to array of primitives for primitive streams

2022-09-26 10:46 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/collections/Collection.java
> +        return stream();
It is not required due to documentation:
```java
Returns a possibly parallel Stream with this collection as its source. It is allowable for this method to return a sequential stream.
```

2022-09-26 10:48 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/Arrays.java
> +        if (startInclusive < 0 || endExclusive < startInclusive || endExclusive > size) {
It is just from the documentation:
```
Throws: ArrayIndexOutOfBoundsException – if startInclusive is negative, endExclusive is less than startInclusive, or endExclusive is greater than the array size
```

2022-09-26 15:05 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/DistanceStatistics.kt
> +            executionStackAccumulatedDistanceToReturn += distanceToReturn
Actually, there are no functional changes, only a bit renaming

2022-09-27 09:22 UTC, CaelmBleidd requested changes

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +        // as mapper can produce infinite streams, we cannot process it symbolically
Can `mapToObj` do it?

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
>          return sum;
When do you return an infinity? 

> the sum will be infinite or NaN

![image](https://user-images.githubusercontent.com/31047452/192484942-64fa5680-0331-464c-9318-3c0eb3e71d1f.png)

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/StreamWrappers.kt
> +     * (int to Integer, etc.), and throws an error otherwise.
Integer to int?

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +            data[i] = mapper.applyAsInt(elementData.get(i));
Why can we remove `disableClassCastExceptionCheck` now?

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
> +    @Disabled("TODO UtArrayApplyForAll translation error https://github.com/UnitTestBot/UTBotJava/issues/630")
Still the same

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +import org.jetbrains.annotations.NotNull;
What for?

2022-09-27 09:22 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/ObjectWrappers.kt
> +     * Checks is there a symbolic implementation for [method].
checks if there is...?

2022-09-27 09:32 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
> +import org.jetbrains.annotations.NotNull;
It is an automatic Idea sorting

2022-09-28 08:25 UTC, CaelmBleidd approved these changes

2022-09-28 08:25 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt
> +        }
Discussed. It is better to add a requirement for the default type not to be an instance of the object type. And change `actualType` in the condition to the default one.

2022-09-28 08:30 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +        setGenericTypeToTypeOfValue(elementData, 0.0);
It will not work well, because a profit is only for the compile-time constant but here a wrapper type is required.

2022-09-28 08:37 UTC, Damtev commented on utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
> +        // as mapper can produce infinite streams, we cannot process it symbolically
Yes, it can, but we cannot check it easily - decided to ignore such cases, added comments

2022-09-28 15:31 UTC, merged