Improve settings, part 1
UnitTestBot/UTBotJava pull request #898
Opened 2022-09-09 12:43 UTC by EgorkaKulikov

# Description

Fixes # ([753](https://github.com/UnitTestBot/UTBotJava/issues/753))

## Type of Change

- Minor bug fix (non-breaking small changes)
- 
# How Has This Been Tested?

## Manual Scenario 

Settings appearance requires the mentioned issue, there is no regress in functionality

2022-09-14 22:46 UTC, Vassiliy-Kudryashov approved these changes

2022-09-15 05:39 UTC, Markoutte commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/Domain.kt
> +        displayName = "Fail",
Is it correct?

2022-09-15 05:43 UTC, Markoutte requested changes
Please, see a comment

2022-09-15 09:06 UTC, Markoutte approved these changes

2022-09-15 09:39 UTC, merged