Add an option to show library classes' graphs in visualization
UnitTestBot/UTBotJava pull request #947
Opened 2022-09-16 13:57 UTC by CaelmBleidd

# Description

I added an option to enable library classes' graphs visualization.

Fixes #946 

## Type of Change
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

Not applicable.

## Manual Scenario 

Set `org.utbot.framework.UtSettings#getShowLibraryClassesInVisualization` in `true` and run generation using the plugin on it. Look at the visualization.  Proof:  

# Checklist (remove irrelevant options):
- [ ] The change followed the style guidelines of the UTBot project
- [ ] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existing one is altered
- [ ] No new warnings
- [ ] All tests pass locally with my changes

2022-09-16 15:55 UTC, dtim requested changes
Please look at the conditions, it seems that a typo changes the logic.

2022-09-16 15:55 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/GraphViz.kt
> +            val dstInLibraryMethod = stmtToSubgraph[edgeDst] !in libraryGraphs
Should it be `in` instead of `!in`?

2022-09-16 15:55 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/GraphViz.kt
> +            if (!(srcInLibraryMethod || dstInLibraryMethod) || showLibraryClassesInVisualization) {
As for me, the first condition `!(srcInLibraryMethod || dstInLibraryMethod)` seems a bit hard to read.

2022-09-19 08:45 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/GraphViz.kt
> +            if (!(srcInLibraryMethod || dstInLibraryMethod) || showLibraryClassesInVisualization) {
Change it to 
```kotlin
val srcInLibraryMethod = stmtToSubgraph[edgeSrc] in libraryGraphs
val dstInLibraryMethod = stmtToSubgraph[edgeDst] in libraryGraphs
val edgeIsRelatedToLibraryMethod = srcInLibraryMethod || dstInLibraryMethod

if (!edgeIsRelatedToLibraryMethod || showLibraryClassesInVisualization) {
    dotGlobalGraph.addDotEdge(edge)
}
```

What do you think?

2022-09-19 08:50 UTC, dtim commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/GraphViz.kt
> +            if (!(srcInLibraryMethod || dstInLibraryMethod) || showLibraryClassesInVisualization) {
Seems much more readable, thank you.

2022-09-19 08:50 UTC, dtim approved these changes
LGTM

2022-09-19 10:37 UTC, merged