`UtAssembleModel` refactor #812
UnitTestBot/UTBotJava pull request #970
Opened 2022-09-19 15:13 UTC by sergeypospelov

# Description

Refactored API:
- Removed useless `UtExecutableCallModel::returnValue`. It was providing duplicate information accordingly to our use cases. Rewrote these use cases, with relying on another API.
- Changed `UtAssembleModel::instantiationChain` to `UtAssembleModel::instantiationCall`
- Made the primary constructor of `UtAssembleModel` private due to its unclear syntax with mutable lists. Added a more understandable (in my point of view) constructor. Rewrote all the usages of the previous one.
- Updated in-code documentation.
- Fixed an error in the `AssembleModelGenerator` and turned on a test, which checks this error.

Fixes #812

## Type of Change

- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 

# How Has This Been Tested?

## Automated Testing

Turned on `org.utbot.examples.codegen.deepequals.ClassWithCrossReferenceRelationshipTest`

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

2022-09-19 16:13 UTC, Damtev requested changes

2022-09-19 16:13 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/concrete/IterableConstructors.kt
>          // If [valueToConstructFrom] constructed incorrectly (some inner transient fields are null, etc.) this may fail.
Not `valueToConstructFrom` anymore but just `value`

2022-09-19 16:13 UTC, Damtev commented on utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt
>          ).apply {
Looks like we should not have this `apply` anymore

2022-09-19 19:33 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt
> +            "Tracked instance can't be null for call ${instantiationExecutableCall.executable} in model $assembleModel"
Done

2022-09-19 19:33 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt
>          ).apply {
You are right, thank you

2022-09-20 06:16 UTC, SBOne-Kenobi requested changes

2022-09-20 06:16 UTC, SBOne-Kenobi commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +            .takeIf { executableCall == model.instantiationCall }
This statement is unnecessary

2022-09-20 06:16 UTC, SBOne-Kenobi commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +        val initExpr = if (isPrimitiveWrapperOrString(type)) cgLiteralForWrapper(params) else cgCall
Move cgCall creation here

2022-09-20 06:16 UTC, SBOne-Kenobi commented on utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/objects/AssembleModelUtils.kt
> +    mutableListOf<UtStatementModel>()
Remove

2022-09-20 06:40 UTC, sergeypospelov commented on utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt
> +            .takeIf { executableCall == model.instantiationCall }
Thank you

2022-09-20 06:45 UTC, SBOne-Kenobi approved these changes
LGTM

2022-09-20 09:08 UTC, Damtev approved these changes
LGTM

2022-09-20 09:37 UTC, merged