Switch to kts
UnitTestBot/UTBotJava pull request #976
Opened 2022-09-20 08:33 UTC by denis-fokin

# Description

Scripts important for multi-language support are switched to kts

Fixes #975

## Type of Change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Automated Testing

CI

## Manual Scenario 

No specific manual scenario.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

2022-09-20 15:05 UTC, dtim commented on utbot-api/build.gradle.kts
> +  id("com.github.johnrengelman.shadow") version "7.1.2"
We have `shadowJarVersion` in `gradle.properties`. Maybe it would be more consistent to use it everywhere instead of a string literal?

2022-09-21 07:14 UTC, denis-fokin commented on utbot-framework-test/build.gradle
>      implementation group: 'org.mockito', name: 'mockito-core', version: '4.2.0'
Let's do it as a separate step in future

2022-09-21 07:16 UTC, denis-fokin commented on utbot-framework/build.gradle
>      implementation group: 'com.jetbrains.rd', name: 'rd-framework', version: '2022.3.1'
I do not want to complicate the enchantment. We have some issues with builds time to time.

2022-09-21 07:32 UTC, IdeaSeeker requested changes

2022-09-21 07:32 UTC, IdeaSeeker commented on utbot-api/build.gradle.kts
> +import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
Please, reindent the file with 4 spaces

2022-09-21 07:32 UTC, IdeaSeeker commented on utbot-intellij/build.gradle.kts
> +            "java",
Please, reformat this line and the next few with 4 spaces

2022-09-21 07:32 UTC, IdeaSeeker commented on utbot-intellij/build.gradle.kts
> +
redundant new lines

2022-09-21 07:32 UTC, IdeaSeeker commented on utbot-maven/build.gradle
> +//inspectClassesForKotlinIC.enabled = false
This is the key logic

2022-09-21 07:33 UTC, IdeaSeeker commented
Why some build.gradle files still exist?

2022-09-21 08:40 UTC, denis-fokin commented on build.gradle.kts
> +        maven ("https://jitpack.io" )
I have updated this

2022-09-21 08:46 UTC, denis-fokin commented on utbot-maven/build.gradle
> +//inspectClassesForKotlinIC.enabled = false
I have brought the lines back and updated

root build gradle -> allprojects -> apply -> plugin("java-library")

from plugin("java").

publishJarPublicationToMavenLocal and publishPluginMavenPublicationToMavenLocal are in java-library plugin

2022-09-21 09:17 UTC, IdeaSeeker commented on utbot-maven/build.gradle
>  configurations {
```suggestion
//file:noinspection GroovyAssignabilityCheck

configurations {
```

2022-09-21 09:47 UTC, denis-fokin commented on utbot-maven/build.gradle
>  configurations {
I have removed all such strings

2022-09-21 12:22 UTC, IdeaSeeker approved these changes

2022-09-21 14:10 UTC, Markoutte commented on utbot-summary/build.gradle.kts
> +    api(project(":utbot-fuzzers"))
It doesn't matter here but do we really need so many `api` calls instead of implementation?

2022-09-22 08:56 UTC, merged