ML path selector
UnitTestBot/UTBotJava pull request #99
Opened 2022-06-01 09:00 UTC by Atos1337

Closes #37

2022-06-04 11:39 UTC, CaelmBleidd requested changes
Some small comment

It's better to request a review for such PRs (with ml and non-ml changes) from someone from ml team as well. I think @amandelpie could help us with it

2022-06-04 11:39 UTC, CaelmBleidd commented on docs/jlearch/execution-state-changes.md
> +# Changes in Execution State
@amandelpie please, review the design documents. It's quite complicated for me to rate them

Also, it is better to use something like Grammarly or more friendly service to check the spelling and other mistakes in docs and comments. I don't point at them in the review.

2022-06-04 11:39 UTC, CaelmBleidd commented on docs/jlearch/execution-state-changes.md
> +# Changes in Execution State
@amandelpie please, review the design documents. It's quite complicated for me to rate them

Also, it is better to use something like Grammarly or a more friendly service to check the spelling and other mistakes. I don't point at them in the review

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                if (it !in visitedStmts && !currentState.isInNestedMethod()) {
Why do we count as new coverage instructions from the MUT only? What about covered methods from the same class?

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                if (it !in visitedStmts && !currentState.isInNestedMethod()) {
Why do we count as new coverage instructions from the MUT only? What about covered methods from the same class?

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                val isNewState = state !in times
Probably, it is better to rename some variables. 
State -> stateHash
Times -> [specifyTime]Time  (spentTime or something, processingTime)

`state !in times` looks odd

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                val isNewState = state !in times
Probably, it is better to rename some variables. 
State -> stateHash
Times -> [specifyTime]Time  (spentTime or something, processingTime)

`state !in times` looks odd

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            queuedSymbolicStateUpdates += typeRegistry.genericTypeParameterConstraint(value.addr, typeStorages)
Non-relevant changes to the commit. Please, either revert such formatting changes or move them into a separate commit

2022-06-04 11:39 UTC, CaelmBleidd commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            queuedSymbolicStateUpdates += typeRegistry.genericTypeParameterConstraint(value.addr, typeStorages)
Non-relevant changes to the commit. Please, either revert such formatting changes or move them into a separate commit

2022-06-07 11:41 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                if (it !in visitedStmts && !currentState.isInNestedMethod()) {
I made this way, because Engine and FeatureProcessor are created for every method, so I thought about consistency in this, but it is good idea for experiments, so I think we can resolve this, then try with your approach and if it is better, then create new PR

2022-06-07 11:42 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                if (it !in visitedStmts && !currentState.isInNestedMethod()) {
above

2022-06-07 11:42 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +                val isNewState = state !in times
duplicate

2022-06-07 12:13 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            queuedSymbolicStateUpdates += typeRegistry.genericTypeParameterConstraint(value.addr, typeStorages)
revert them

2022-06-07 12:30 UTC, amandelpie commented on docs/jlearch/execution-state-changes.md
> +# Changes in Execution State
@CaelmBleidd It's ok, I'll do the review next two days

2022-06-07 13:16 UTC, Atos1337 commented on docs/jlearch/execution-state-changes.md
> +# Changes in Execution State
duplicate

2022-06-07 13:17 UTC, Atos1337 commented on docs/jlearch/execution-state-changes.md
> +# Changes in Execution State
Spelling is corrected

2022-06-10 10:07 UTC, amandelpie requested changes
First part of comments

2022-06-10 10:07 UTC, amandelpie commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +        private val featureKeys = arrayOf(
Probably better to move these features to the property file to make it more universal.

But if it's hardcoded somewhere as a variable names - let it be as implemented

2022-06-10 10:22 UTC, Atos1337 commented on gradle.properties
> +pytorch_native_version=1.9.1
Could not determine the dependencies of task ':utbot-analytics:jar'.
> Could not resolve all files for configuration ':utbot-analytics:runtimeClasspath'.
   > Could not find ai.djl.pytorch:pytorch-native-auto:1.11.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/ai/djl/pytorch/pytorch-native-auto/1.11.0/pytorch-native-auto-1.11.0.pom
       - https://jitpack.io/ai/djl/pytorch/pytorch-native-auto/1.11.0/pytorch-native-auto-1.11.0.pom
     Required by:
         project :utbot-analytics
         
I think not

2022-06-10 10:30 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureExtractorImpl.kt
> +    private val statementStatistics = StatementsStatistics(graph)
Why it is better? I think that init is for initialization part, which can't be written without init {} syntax or with complicated logic. In our case, there is just a constructor call

2022-06-10 10:35 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +        File(saveDir).mkdirs()
I don't think we can handle it. Documentation said:
```
returns true if and only if the directory was created, along with all necessary parent directories; false otherwise
```
So it will return true only on first creation, but during featureProcessing, we usually creates hundreds times.

2022-06-10 11:06 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +        private val featureKeys = arrayOf(
did

2022-06-10 11:07 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +    graph: InterProceduralUnitGraph,
did

2022-06-10 11:07 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureExtractorImpl.kt
> +            add(statementStatistics.statementInMethodCount(executionState)) // cpicnt
did

2022-06-10 11:07 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureExtractorImpl.kt
> +class FeatureExtractorImpl(private val graph: InterProceduralUnitGraph) : FeatureExtractor {
did

2022-06-10 11:07 UTC, Atos1337 commented on gradle.properties
> +djl_api_version=0.16.0
did

2022-06-10 11:24 UTC, amandelpie requested changes
A lot of my comments are related to poor documentation and unclear logic.
I also need a time to debug and reproduce results

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
>          else -> error("Unknown type")
Uknown type of what? It's not informative error message: add information about wrong type and some tips how to fix it

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        if (featureProcess) EngineAnalyticsContext.featureProcessorFactory(globalGraph) else null
Looks like a candidate for init section and handling the problems with the factory initialization by GlobalGraph

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        featureProcessor?.dumpFeatures()
What if we could not dump? Print an error message to the log or handle somehow

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +                                // TODO: enrich with nice description for known issues
Probably better to fix this TODO

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +                                logger.debug(ex) { "Cancellation happened" }
What kind of cancellation is happened? Please describe the exception, the reason of cancelation

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            environment.state.updateIsFork()
rename the method, it looks weird

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +                else -> null
Do we really need to return null here? probably better to throw an exception and write to the log

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/BasePathSelector.kt
> +        utSolver.assertions.isNotEmpty() && utSolver.check(respectSoft = false).statusKind != SAT
Could we more clearly describe the underlying constraints in the human readable language?

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> + * https://files.sri.inf.ethz.ch/website/papers/ccs21-learch.pdf
use the @see tag from KDocs to paste the link like here
          * @see <a href="https://arxiv.org/abs/1512.03385">
         *     Deep Residual Learning for Image Recognition (CVPR 2015)</a>

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> + * @see [GreedySearch]
probably @see is incorrect for usage to refer a class, just use [..] in the body of KDoc

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> +    protected val generatedTestCountingStatistics: GeneratedTestCountingStatistics,
Why is it protected, not public?

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> +    choosingStrategy: ChoosingStrategy,
Mention or use parameter names in the KDoc

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> +        get() = "NNRewardGuidedSelector"
Probably better to use Enum constants instead of String names for classes or use reflection to get short class name

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> +class NNRewardGuidedSelectorWithoutRecalculationWeight(
Suggets to rename withoutWeightsRecalculation

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> + * Calculate weight of execution state every time when it needed. It works slower, but features are always relevant
Slower than what?

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> + * Calculate weight of execution state only when it is offered. It has advantage, because it works faster,
Faster than what?

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> + * Calculate weight of execution state only when it is offered. It has advantage, because it works faster,
Probably better to write: it's a fast model (in comparision  with [class])

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/PathSelectorBuilder.kt
> + * build [SubpathGuidedSelector] using [SubpathGuidedSelectorBuilder]
b->B

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/PathSelectorBuilder.kt
> +        requireNotNull(context.stoppingStrategy) { "StoppingStrategy isn't specified" },
isn't -> is not

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/CPInstSelector.kt
> + * https://github.com/klee/klee/blob/085c54b980a2f62c7c475d32b5d0ce9c6f97904f/lib/Core/Searcher.cpp#L207
Use @see for the external link and don't use the @see to refer on class name

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/ForkDepthSelector.kt
> +        get() = "ForkDepth"
Why this name doesn't contain `Selector` word, looks inconsistent

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/GreedySearch.kt
> +    seed: Int = 0
I have one thought about all seeds used in the ML part - probably better to move all of them to the property file or something else or put into one place.

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/GreedySearch.kt
> +        states.forEach {
refactor (extract the founding the best to the separate method) or provide a good comment for logic hidden here

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/SubpathGuidedSelector.kt
> +    override val name = "NURS:SubpathGuidedSearch"
Why here it's a val, somewhere it looks like a getter and uses different patterns for naming

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/SubpathGuidedSelector.kt
> +        get() = -subpathStatistics.subpathCount(this).toDouble()
unclear calculation logic

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/StatementsStatistics.kt
> + * - number of instructions visited in state’s current method in [statementsInMethodCount]
Very good example of good comment that lights what's happened in the method with complex calculations

2022-06-10 11:24 UTC, amandelpie commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/SubpathStatistics.kt
> +    private fun ExecutionState.getSubpath(length: Int): List<Edge> {
Add some notes about used algorithm to get sub path (link to pseudocode or step-by-step logic)

2022-06-10 11:24 UTC, amandelpie commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/ContestEstimator.kt
>  //    Predictors.smtIncremental = UtBotTimePredictorIncremental()
Should we remove the commented logic?

2022-06-10 11:32 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +    private val featureExtractor = EngineAnalyticsContext.featureExtractorFactory(graph)
I wrote comment above about init sections. I did this by invoke operator to make it more like constructor

2022-06-10 12:17 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +            val outputFile = Paths.get(saveDir, "${UtSettings.testCounter++}.csv").toFile()
It work in each case whether file exists or not, because if it is not exists than we will create it in the next line

2022-06-10 12:21 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> + * Implementation of feature processor, in which we dump each test, so there will be several copies of each state.
Goal: make a weighted dataset, more value for states, which generated more tests. 
Dump process: I think I kinda described it in `jlearch-architecture.md`, when I wrote about dumpFeatures

2022-06-10 12:32 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt
> +            var allTime = 0L
Now, we have one run, of course time can depends on many factors such as GC, but I don't research whether it is statistically valueable or not

2022-06-10 13:00 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/LinearStateRewardPredictor.kt
> +    val weightsArray = weightsFile.readText().splitByCommaIntoDoubleArray()
What is problem if it throw exception? If we can't read a weights, than we can't run our application, so exception is the best way to finish it

2022-06-10 13:02 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/LinearStateRewardPredictor.kt
> +    private val weights = loadWeights(weightsPath)
handled inside function, so I think init section is not necessary

2022-06-10 13:09 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/NNStateRewardPredictorSmile.kt
> +data class NN(val operations: List<(DoubleArray) -> DoubleArray>)
why not data class? It has no logic. Renamed to NeuralNetwork

2022-06-10 13:16 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/NNStateRewardPredictorSmile.kt
> +class NNStateRewardPredictorSmile(modelPath: String = DEFAULT_MODEL_PATH, scalerPath: String = DEFAULT_SCALER_PATH) :
I don't know how to called class in this case, because it is only difference between existing predictors in frameworks, that we used for it

2022-06-10 13:20 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/NNStateRewardPredictorTorch.kt
> +class NNStateRewardPredictorTorch : NNStateRewardPredictor, Closeable {
I don't know but all differences already described in docs, difference between Smile and Torch is Smile and Torch, we just use two different frameworks, but one is more universal and other is faster)

2022-06-10 13:23 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/NNStateRewardPredictorTorch.kt
> +        model.load(Paths.get(UtSettings.rewardModelPath, "model.pt1"))
How you propose to handle it?

2022-06-10 13:39 UTC, Atos1337 commented on utbot-analytics/src/main/kotlin/org/utbot/predictors/NNStateRewardPredictorSmile.kt
> +    private val nn = loadNN(modelPath)
handled inside loadNN, so not necessary to create init {} I think

2022-06-10 13:42 UTC, Atos1337 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    var collectCoverage by getBooleanProperty(false)
delete it

2022-06-10 13:42 UTC, Atos1337 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
> +    CPI_SELECTOR,
What I should document here?)

2022-06-10 13:49 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/analytics/EngineAnalyticsContext.kt
> +            error("Feature processor factory wasn't provided")
Why we need coma?

2022-06-10 13:53 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/analytics/Predictors.kt
> +    var sat: IUtBotSatPredictor<Iterable<UtExpression>> = object : IUtBotSatPredictor<Iterable<UtExpression>> {}
delete it

2022-06-10 13:55 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ExecutionState.kt
> +data class StateAnalyticsProperties(
why? It is just set of fields

2022-06-10 13:56 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ExecutionState.kt
> +    fun updateIsFork() {
yes, and it is update, because by default it is false

2022-06-10 13:57 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ExecutionState.kt
>      val solver: UtSolver by symbolicState::solver
it is not my code, I don't know how to comment them

2022-06-10 13:58 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
>          else -> error("Unknown type")
delete it

2022-06-10 13:59 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        if (featureProcess) EngineAnalyticsContext.featureProcessorFactory(globalGraph) else null
There is no problems and it more consistent to initialize like this, because all other field are initialized without init

2022-06-10 14:01 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +        featureProcessor?.dumpFeatures()
There is no way to not dump, only case is when it is null, so feature processing is disabled, so users don't want messages about this I think

2022-06-10 14:02 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +            environment.state.updateIsFork()
how you propose to rename this?

2022-06-10 14:03 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
> +                else -> null
not my code

2022-06-10 14:03 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/BasePathSelector.kt
> +        utSolver.assertions.isNotEmpty() && utSolver.check(respectSoft = false).statusKind != SAT
not my code, just a formatting

2022-06-10 14:06 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/NNRewardGuidedSelector.kt
> +    protected val generatedTestCountingStatistics: GeneratedTestCountingStatistics,
I think that we should make fields as less visible as we can

2022-06-10 14:09 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/PathSelectorBuilder.kt
> + * build [SubpathGuidedSelector] using [SubpathGuidedSelectorBuilder]
For consistency make b

2022-06-10 14:09 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/PathSelectorBuilder.kt
> +        requireNotNull(context.stoppingStrategy) { "StoppingStrategy isn't specified" },
for consistency made as other builders

2022-06-10 14:13 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/ForkDepthSelector.kt
> +        get() = "ForkDepth"
only NNRewardGuidedSelector contains `Selector`, because it is not `NURS`, all others without this word, so I made it for consistency

2022-06-10 14:13 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/GreedySearch.kt
> +    seed: Int = 0
For consistency make it like in `NonUniformRandomSearch` and `GreedySearch` is not always ML part

2022-06-10 14:14 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/GreedySearch.kt
> +        states.forEach {
Don't understand, this whole method about founding the best

2022-06-10 14:15 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/SubpathGuidedSelector.kt
> +    override val name = "NURS:SubpathGuidedSearch"
make by get()

2022-06-10 14:16 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/selectors/nurs/SubpathGuidedSelector.kt
> +        get() = -subpathStatistics.subpathCount(this).toDouble()
add comment

2022-06-10 14:19 UTC, Atos1337 commented on utbot-junit-contest/src/main/kotlin/org/utbot/contest/ContestEstimator.kt
>  //    Predictors.smtIncremental = UtBotTimePredictorIncremental()
I think no, in first, it is ContestEstimator, in second, it usefull to enable or disable some predictors

2022-06-10 14:59 UTC, Atos1337 commented on utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
>  enum class TestSelectionStrategyType {
It is not my code

2022-06-10 15:58 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ExecutionState.kt
> +    var visitedAfterLastFork: Int = 0,
It seems that I can't add more information, that already exist in its name

2022-06-10 16:09 UTC, Atos1337 commented on utbot-framework/src/main/kotlin/org/utbot/engine/ExecutionState.kt
> +    fun updateIsFork() {
maybe definitely?

2022-06-15 10:28 UTC, CaelmBleidd approved these changes
Please, add a proper description for the request

2022-06-15 10:28 UTC, merged